### PR TITLE
fix: ci

### PR DESCRIPTION
**Pull request by smelukov**
**What kind of change does this PR introduce?**

build related

**Did you add tests for your changes?**

nope

**If relevant, did you update the documentation?**

nope 

**Summary**

Just updated some build related deps to fix CI

**Does this PR introduce a breaking change?**

nope

### CODE REVIEW

**Comment by ematipico** [comment]
Could you macOS from azure pipelines? Azure discontinued the support of those images

**Comment by smelukov** [comment]
I’ll remove this

**Comment by smelukov** [comment]
@ematipico done

**Comment by smelukov** [comment]
@ematipico I can’t merge the PRs by myself 🙈

**Pull request merged**
