### PR TITLE
chore: update dependencies

### PR DESCRIPTION
**Pull request by anshumanv**
**What kind of change does this PR introduce?**
updates deps accross all packages.

**Did you add tests for your changes?**
Yes

**If relevant, did you update the documentation?**
Not needed

**Summary**
- Updated all packages
- We will enable dependabot after this

**Does this PR introduce a breaking change?**
Shouldn't ideally

**Other information**
NA

### CODE REVIEW

**Comment by evilebottnawi** [comment]
Something broken, need investigate and fix it

**Comment by anshumanv** [comment]
Will take a look. 👍

**Comment by anshumanv** [comment]
Test is passing locally but not here 😕 

If anyone has any ideas about this, please suggest.

**Comment by evilebottnawi** [comment]
Problem with `import * as path from 'path';`, just rewrite that line

**Comment by anshumanv** [comment]
> Problem with import * as path from 'path';, just rewrite that line

Problem seems to be something else, looking
image

**Comment by anshumanv** [comment]
nyc upgrade was the issue, breaking change, reverted it. 👍 

Will enable dependabot after this goes in.

**Comment by evilebottnawi** [comment]
@anshumanv please fix conflicts

**Comment by evilebottnawi** [comment]
Let's merge it and continue development

**Comment by evilebottnawi** [comment]
I think we should check each package for unnecessary dependencies and remove them, it's a simple task

**Comment by anshumanv** [comment]
> I think we should check each package for unnecessary dependencies and remove them, it's a simple task

On it. 👍

**Comment by anshumanv** [comment]
Also, enabling dependabot.

**Pull request merged**
