### PR TITLE
Use yarn if available

### PR DESCRIPTION
**Pull request by andrei-zhidkov**
**What kind of change does this PR introduce?**
Feature

**Did you add tests for your changes?**
Yes.

**Summary**
As per #123, it would be nice to use Yarn during `init` if it is available.
This pull request adds a check to determine which package manager to use, and spawns the respective package manager to install dependencies.
Yarn will also be used by the default generator, if possible.

**Does this PR introduce a breaking change?**
No

### CODE REVIEW

**Comment by ematipico** [comment]
It looks fine to me, let's wait @ev1stensberg or @okonet to this what they think about it

**Comment by ev1stensberg** [comment]
Hi! Do you mind rebasing?

**Comment by ev1stensberg** [comment]
https://github.com/webpack/webpack-cli/tree/andrei-zhidkov-feature/use-yarn just mirror this branch , I'll let you fix the conflict yourself ( just copy paste the content of the file at the branch I linked ), so that you'll get the PR submitted 🥂

**Comment by ev1stensberg** [comment]
#189 Congrats on your first contribution @andrei-zhidkov !

**Comment by andrei-zhidkov** [comment]
Whoa, that was faster than I could react.
Thanks for merging, Even!

**Pull request closed without merging**
