### PR TITLE
chore(test): updated tests file names

### PR DESCRIPTION
**Pull request by ematipico**
**What kind of change does this PR introduce?**
Chore, renamed test files 

**Did you add tests for your changes?**
No

**If relevant, did you update the documentation?**
No

**Summary**
Changed test files from `*.spec.js` to `*.test.js`

**Does this PR introduce a breaking change?**
It shouldn't, although locally I had some failing test (not these ones) and I couldn't understand why

**Other information**

### CODE REVIEW

**Comment by ematipico** [comment]
@ev1stensberg do we? All the file names are `*.test.js`, I thought we were consistent in that way

**Comment by ematipico** [comment]
@dhruvdutt why do I have to remove `*.spec.js`? I don't get

**Comment by dhruvdutt** [comment]
Because there would be no files with `spec.js` extension.

**Comment by ematipico** [comment]
I can do it! But first I'd like to know @ev1stensberg point of you.

**Comment by ev1stensberg** [comment]
Keep `.spec`, it's not like it's illegal to use another convention 👍

**Pull request merged**
