### PR TITLE
Fix(init): init entry point fix when path is mentioned

### PR DESCRIPTION
**Pull request by anikethsaha**
**What kind of change does this PR introduce?**

bugfix

**Did you add tests for your changes?**
No

**If relevant, did you update the documentation?**
Not Required

**Summary**
fix https://github.com/webpack/webpack-cli/issues/884
Refactored the `init-genereator.ts` to change the `entry` options in the webpack config file to the one answered if the answer is not empty

**Does this PR introduce a breaking change?**

NA

**Other information**
The `regex ` can be improved to more efficient with something like this
```bash
if(!(/(\'\'|\"\")/g.test(entryOptions))){
...
}
```

### CODE REVIEW

**Comment by anikethsaha** [comment]
@evenstensberg we are getting `entryOptions` from that entry file. They are not the same I guess.

**PS** : I changed the `step to reproduce` in the issue https://github.com/webpack/webpack-cli/issues/884 as the earlier steps were not correct.

**Comment by misterdev** [comment]
Hi @anikethsaha, thanks for the PR :)

#817 is already addressing some of the issues in the `init-generator` and fixes #884 too

**Comment by anikethsaha** [comment]
@misterdev that one looks good. Are you sure about the particular entry property issue https://github.com/webpack/webpack-cli/issues/884 is addressing?. I need to test that but if you say that one is fine then we can go with that :)
Also, your review is pending for https://github.com/webpack/webpack-cli/pull/883 this too, PTAL 👍

**Comment by misterdev** [comment]
Yeah, it fixes the problem you reported about the custom entry point not set in the configuration :)
I would keep #884 open anyway until it is fixed

**Comment by anikethsaha** [comment]
@misterdev let's keep that then 👍

**Pull request closed without merging**
