### PR TITLE
tests: use sync api for fs tests

### PR DESCRIPTION
**Pull request by anshumanv**
**What kind of change does this PR introduce?**
fix

**Did you add tests for your changes?**
Yes

**If relevant, did you update the documentation?**
NA

**Summary**
- Shifted to use sync API for output checking

**Does this PR introduce a breaking change?**

Nope

**Other information**

### CODE REVIEW

**Review by snitin315 — CHANGES_REQUESTED** [review]
CI is red.

**Comment by anshumanv** [comment]
Yes I can see

**Comment by anshumanv** [comment]
Fix in near future

**Review by alexander-akait — COMMENTED** [review]
But async API is faster

**Comment by anshumanv** [comment]
CI time is reduced instead, plus no more nested promises for each file, this seems much more cleanr

**Review by alexander-akait — APPROVED** [review]

**Pull request merged**
