### PR TITLE
build: add bootstrap step in workflow

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**
build

**Did you add tests for your changes?**
NA
**If relevant, did you update the documentation?**
NA
**Summary**

run `yarn lerna bootstrap` on CI.

**Does this PR introduce a breaking change?**
No

**Other information**

### CODE REVIEW

**Review by alexander-akait — COMMENTED** [review]
We should test cache, try to change something for help output and we should got failed CI, then change it again and it should be green

**Comment by snitin315** [comment]
CI is green ✅

**Comment by alexander-akait** [comment]
@snitin315 Let's rebase

**Comment by snitin315** [comment]
I think we need to wait for #2557 as well.

**Pull request merged**
