### PR TITLE
feat: add `WEBPACK_PACKAGE` env var to use custom `webpack` package

### LINKED ISSUE #2551: [FEATURE]: Option to switch between versions of webpack
I'm working on a Vue 2 project, which needs webpack v4 deep in its internals. It seems unlikely I'll be able to update any time soon. However for a new entry point, I'd like to use v5. I was able to install both v4 and v5 using package.json npm aliases:

```json
"webpack": "^4.0.0",
"webpack5": "npm:webpack@^5.28.0",
"webpack-cli": "^4.5.0"
```

It would be wonderful if I could somehow configure `webpack-cli` to use `webpack5` some of the time.

**Describe the solution you'd like**

An environment variable seems like an ok option? Something like: `WEBPACK_PACKAGE=webpack5 npx webpack version`. A wepback-cli option itself could also work, but seems more difficult to implement.

**Describe alternatives you've considered**

- I tried splitting off the new entry point into its own directory, but they have some shared code, so not really an option. The only other option is using v4 exclusively.
- I tried modifying this line: https://github.com/webpack/webpack-cli/blob/6fb1215c8ac82e88ee85861e987b476af47acc61/packages/webpack-cli/lib/webpack-cli.js#L12 to say `this.webpack = require(process.env.WEBPACK_PACKAGE || 'webpack');`, and that did the thing!

**Additional context**

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**
feature

**Did you add tests for your changes?**
Yes

**If relevant, did you update the documentation?**
will send PR to documentation
**Summary**
FIxes #2551 

```
"webpack": "^4.0.0",
"webpack5": "npm:webpack@^5.28.0",
"webpack-cli": "^4.5.0"
```

`webpack` - run webpack 4
`WEBPACK_PACKAGE=webpack5` - run webpack 5

**Does this PR introduce a breaking change?**
No

**Other information**
No

### CODE REVIEW

**Review by alexander-akait — COMMENTED** [review]
Need test, `test/build/custom-webpack/custom-webpack.js` with `module.exports = require('webpack')` and set `WEBPACK_PACKAGE=./custom-webpack.js`

**Comment by snitin315** [comment]
added tests 👍🏻

**Review by alexander-akait — APPROVED** [review]

**Review by anshumanv — APPROVED** [review]

**Comment by snitin315** [comment]
Cache issue?

**Comment by alexander-akait** [comment]
Yep, happens only on windows

**Comment by alexander-akait** [comment]
@snitin315 Let's wait green https://github.com/webpack/webpack-cli/pull/2553 and merge, then rebase

**Comment by anshumanv** [comment]
lets rebase

**Review by anshumanv — APPROVED** [review]

**Review by alexander-akait — APPROVED** [review]

**Pull request merged**
