### PR TITLE
misc(init): use `src/index.js` as entry module by default

### PR DESCRIPTION
**Pull request by vijaykrishnavanshi**
**What kind of change does this PR introduce?**

This PR adapt init command to use ./src/index as default with proper prompt. According to the discussion on issue #321.

**Did you add tests for your changes?**
No, but tests pass locally.

**If relevant, did you update the documentation?**
N/A

**Summary**

Allow webpack-cli to generate config file without much blocking.
Issue #321 

**Does this PR introduce a breaking change?**

No

### CODE REVIEW

**Comment by vijaykrishnavanshi** [comment]
@ev1stensberg but considering the fact that 0CJS will be configurable in future will this be a good idea.
By removing do you mean no entry param in config?

**Comment by PlayMa256** [comment]
@vijaykrishnavanshi yes. Webpack already defaults that to `./src/index`

**Comment by ev1stensberg** [comment]
No entry, that's correct. If there's 0CJS then there's no point setting it if user ignores entry

**Comment by ematipico** [comment]
Is this PR still valid? As far as I understood there's no need to set any default as we have the 0CJS in place that does the job. Worth closing?

**Pull request closed without merging**
