### PR TITLE
docs: update the links branch to next

### PR DESCRIPTION
**Pull request by stu01509**
**What kind of change does this PR introduce?**
docs, update the links branch to next.

**Did you add tests for your changes?**
No

**If relevant, did you update the documentation?**
No

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

### CODE REVIEW

**Review by snitin315 — COMMENTED** [review]
In near future, it will be `master` again. We are near releasing v4.

**Comment by stu01509** [comment]
Hi @snitin315 

Thanks for your comment, so should I close this PR?
Because I found some packages that didn't exist in **next ** branch.

**Comment by snitin315** [comment]
Hmm, all links should be updated once `next` is merged in `master`.

**Review by evilebottnawi — CHANGES_REQUESTED** [review]
No need, thanks

**Pull request closed without merging**
