### PR TITLE
rename bot to cli bot

### PR DESCRIPTION
**Pull request by ev1stensberg**

### CODE REVIEW

**Comment by ev1stensberg** [comment]
@ematipico

**Comment by ev1stensberg** [comment]
hm, okay... So what's the purpose of the name tag then, if its bound to the organization name?

**Comment by ematipico** [comment]
Because you can publish on AWS multiple bots with different names. @sokra suggested to use the bot that we already have since it is already up and running for the current organisation.

**Comment by ev1stensberg** [comment]
Gotcha, okay let's close this, its picky-mcnittywork

**Comment by sokra** [comment]
The propose of the name tag is to avoid two bots acting on the same repo. The deployed bot only operates on repos with the current name in the configuration.

Two bot operating on the same repo can have bad side-effects like bot talking with each other in a infinite loop...

**Comment by ev1stensberg** [comment]
That would be really cool to watch happen @sokra 😆

**Pull request closed without merging**
