### PR TITLE
docs: add more information

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**
Docs

**Did you add tests for your changes?**
NA
**If relevant, did you update the documentation?**
Yes
**Summary**

Add more useful information.

**Does this PR introduce a breaking change?**
No

**Other information**
No

### CODE REVIEW

**Review by anshumanv — COMMENTED** [review]
we can't maintain full documentation in 4 places, I don't think many people will even arrive at this readme.

We should keep this at root if at all we want this here given it's already in the docs page

**Comment by snitin315** [comment]
This readme renders on the official npm page https://www.npmjs.com/package/webpack-cli, nevertheless a link to the official docs https://webpack.js.org/api/cli/ should be present.

**Comment by anshumanv** [comment]
yep link makes sense 👍

**Review by alexander-akait — APPROVED** [review]

**Comment by alexander-akait** [comment]
Sorry, too fast, feel free to send other PR and improve it more

**Pull request merged**
