### PR TITLE
tests(info): add tests for info package arguments/flags

### PR DESCRIPTION
**Pull request by anshumanv**
add tests for info package arguments and flags

**What kind of change does this PR introduce?**
tests: adding tests for all flags of info command

**Did you add tests for your changes?**
Yay

**If relevant, did you update the documentation?**
NA

**Summary**
Adding tests for all flags supported by info command.

**Does this PR introduce a breaking change?**
No

**Other information**

### CODE REVIEW

**Comment by anshumanv** [comment]
Ah cool @rishabh3112, just wanted to add tests for all flags, we can do it either way, having tests for all help in a single place is also cool or dividing help tests in respective packages is okay too I feel since the `help` can focus on the entire cli help command, while these are scoped to respective packages which made more sense to me. 👍

**Comment by anshumanv** [comment]
@evenstensberg @ematipico how do I make info package available while writing flag tests for info or any other commands that we have? Invoking the package via jest just prompts to install the package after it's reported missing, any ideas?

**Comment by ematipico** [comment]
You can use this example: https://github.com/webpack/webpack-cli/tree/next/test/info/shim/node_modules/%40webpack-cli/info

**Comment by anshumanv** [comment]
Great thanks! Will take a look in a while. 👍

**Comment by anshumanv** [comment]
Would love to know if I can cover any other cases in these tests.

**Comment by anshumanv** [comment]
Thank you! 

> test/info/info.multi-args.test.js

I'll just rename this file to `info-multi-args.test.js` avoid inconsistencies.

**Comment by rishabh3112** [comment]
Thanks!

**Pull request merged**
