### PR TITLE
fix: `configs` property for `--devtool`

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**
bugfix

**Did you add tests for your changes?**
Yes
**If relevant, did you update the documentation?**
No
**Summary**

`devtool` can also accept `false`.

**Does this PR introduce a breaking change?**
No

**Other information**
None

### CODE REVIEW

**Review by alexander-akait — COMMENTED** [review]
Only for webpack v5, we already support it

**Comment by snitin315** [comment]
I see then we should remove `negative: true`?

**Comment by snitin315** [comment]
It is allowed for v4 too https://github.com/webpack/webpack/blob/webpack-4/schemas/WebpackOptions.json#L2039

**Comment by alexander-akait** [comment]
yep, okay, let's do it, but I don't want to accept any bugfixes/features (expect security bugs for v4), because when we will drop webpack v4 we will remove these flags

**Comment by snitin315** [comment]
Makes sense 👍🏻

**Review by alexander-akait — APPROVED** [review]

**Comment by alexander-akait** [comment]
Thanks

**Pull request merged**
