### PR TITLE
ci: fix

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**
test, CI

**Did you add tests for your changes?**
updated snapshots.
**If relevant, did you update the documentation?**
No
**Summary**

Update snapshots for `webpack-dev-server@latest`. Fix CI.

**Does this PR introduce a breaking change?**
None

**Other information**
No

### CODE REVIEW

**Comment by snitin315** [comment]
It seems we have different snapshot for different OS

**Review by alexander-akait — DISMISSED** [review]

**Comment by alexander-akait** [comment]
Hm, still unstable, we can sort them for tests

**Review by evenstensberg — DISMISSED** [review]

**Review by alexander-akait — APPROVED** [review]

**Comment by snitin315** [comment]
@alexander-akait can you update the merge setting to 1 approval?

**Comment by alexander-akait** [comment]
@snitin315 Done :+1:

**Pull request merged**
