### PR TITLE
fix: add style and css loader to sass/less/stylus replaces #3172

### PR DESCRIPTION
**Pull request by TheRealSyler**
Same as #3172 but in own feature branch and not broken git history

**What kind of change does this PR introduce?**
Fixes the sass/less/stylus config generation.

**Did you add tests for your changes?**
yes.

**If relevant, did you update the documentation?**
No, no change needed.

**Summary**

Related to #3171 

**Does this PR introduce a breaking change?**
No.

### CODE REVIEW

**Comment by snitin315** [comment]
@TheRealSyler Thanks for the PR, I changed the `base` of this PR to the `next` branch. There is one conflict now, can we fix it? 
We are accepting new features and bug fixes in the `next` branch only.

**Comment by TheRealSyler** [comment]
@snitin315 there should be no conflicts now.

**Review by snitin315 — APPROVED** [review]
LGTM, thank you!

**Review by alexander-akait — APPROVED** [review]

**Comment by alexander-akait** [comment]
Thank you

**Pull request merged**
