### PR TITLE
Swap chalk for turbocolor.

### PR DESCRIPTION
**Pull request by jorgebucaran**
Hello webpack-cli maintainers! 👋 

This PR basically swaps chalk for [Turbocolor](https://github.com/jorgebucaran/turbocolor).

---

**What kind of change does this PR introduce?**

Swaps one library for another that uses the same API, but it's lighter (no deps) and has significantly better load/runtime performance (~>20x faster). 

**Did you add tests for your changes?**

Same tests pass, so should be good.

**If relevant, did you update the documentation?**

I did, is it good?

**Summary**

It should give you a small perf boost as turbocolor loads **_>20x_** faster and applies styles **_>18x_** faster than chalk for the same API (see [benchmarks](https://github.com/jorgebucaran/turbocolor/tree/master/bench#benchmarks)). Node.js >=v4 supported.

<pre>
# Load Time
chalk: 15.190ms
<b>turbocolor: 0.777ms</b>

# All Colors
chalk × 8,729 ops/sec
<b>turbocolor × 158,383 ops/sec</b>

# Chained Colors
chalk × 1,838 ops/sec
<b>turbocolor × 39,830 ops/sec</b>

# Nested Colors
chalk × 4,049 ops/sec
<b>turbocolor × 59,833 ops/sec</b>
</pre>

**Does this PR introduce a breaking change?**
No!

---

Let me know if this is acceptable to you and if I need to change anything. Cheers!

### CODE REVIEW

**Comment by ev1stensberg** [comment]
Hi @jorgebucaran, thanks for the attention and PR! 

I'm going to ask the team first, let me get back to you once we're decided!

**Comment by jorgebucaran** [comment]
Hi @ev1stensberg, thanks sounds good.

**Comment by ematipico** [comment]
Any comparison regarding the sizes of the packages?

**Comment by jorgebucaran** [comment]
@ematipico I usually go to bundlephobia to find out:

- [chalk@2.4.1](https://bundlephobia.com/result?p=chalk@2.4.1) 20.2kB (7.5kB min+gzip)
- [turbocolor@2.2.0](https://bundlephobia.com/result?p=turbocolor@2.2.0) 1.1kB (695 B min+gzip)

**Comment by jorgebucaran** [comment]
@ev1stensberg Feature-wise chalk has more options, but webpack-cli is using none of them and some of those options are not widely supported by terminals. API-wise, they're virtually the same, but let's see one thing.

Chalk supports variadic arguments like:

```js
console.log(chalk.red("Hello", "World"))
```

...whereas turbocolor is a unary function by design. (There are so many ways that [`arguments`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments) can cause a function to be unoptimizable.)

```js
console.log(color.red("Hello" + "World"))

// or 

console.log(color.red("Hello %s"), "World")
```

You can see all the features supported by turbocolor in the [usage section](https://github.com/jorgebucaran/turbocolor#usage).

---

Hope that answers your question :)

**Comment by ev1stensberg** [comment]
Hi @jorgebucaran . Me and my team have discussed a bit, and we don't really see the point of swapping chalk for another library. Chalk is stable and good enough for us as of this date. Thanks for the PR 👍

**Pull request closed without merging**
