### PR TITLE
fix: ci lint

### PR DESCRIPTION
**Pull request by anshumanv**
**What kind of change does this PR introduce?**

CI lint is failing 

**Did you add tests for your changes?**
yep

**If relevant, did you update the documentation?**
no

**Summary**
no

**Does this PR introduce a breaking change?**
no

**Other information**
no

### CODE REVIEW

**Comment by anshumanv** [comment]
introduced in - https://github.com/webpack/webpack-cli/pull/2172

**Review by alexander-akait — APPROVED** [review]

**Review by snitin315 — APPROVED** [review]
Thanks

**Review by jamesgeorge007 — APPROVED** [review]

**Comment by anshumanv** [comment]
Lint passed, I think we can merge and make room for other jobs 😄

**Comment by anshumanv** [comment]
cancelled remaining runs and master job

**Pull request merged**
