### PR TITLE
docs(all): removed hard-coded docs, moved md to /docs

### PR DESCRIPTION
**Pull request by anshumanv**
Removed all the hard-coded docs since we'll setup auto-deployment, moved some md docs to /docs
folder instead for a cleaner root dir.

ISSUES CLOSED: #774

**What kind of change does this PR introduce?**
Docs

**Did you add tests for your changes?**
Yes

**If relevant, did you update the documentation?**
Yes.

**Summary**
* Removed hard-coded docs, moved some markdowns to /docs instead
* Docs will be auto-deployed using Netlify.

**Does this PR introduce a breaking change?**
No

**Other information**

### CODE REVIEW

**Comment by anshumanv** [comment]
@evenstensberg I need to have push access to add the project on Netlify and enable docs generation on every push. I can do that or you can do it instead, works either way.

Also what domain do we take? `webpack-cli-docs.netlify.com` ? or Just `webpack-cli.netlify.com` 🤔

**Comment by evenstensberg** [comment]
Could you make a fork and give us an example first?

**Comment by anshumanv** [comment]
Hey @evenstensberg I already added my fork on netlify to test, here's the latest deploy link

https://app.netlify.com/sites/webpack-cli/deploys/5c8352334fb75f7efd11bacc

All we need to do it remove my fork and add this repo and we're done! 🎉

**Comment by anshumanv** [comment]
> Is this same as this we already have?

Where is this hosted from? Generated docs that live in this repo? 🤔 

We can then opt to push the docs to a separate branch (say gh-pages) on every push so they're the latest imo. Everything remains the same then. What do you think? 😄 

> Instead we can add more content on the site.

Aren't they autogenerated? You mean hardcode?

**Comment by rishabh3112** [comment]
> Where is this hosted from?

from `./docs/` at `master` using github pages.

> We can then opt to push the docs to a separate branch (say gh-pages) on every push so they're the latest imo. Everything remains the same then. What do you think? 😄

master would always be more updated  IMO.

> Aren't they autogenerated? You mean hardcode?

No I mean to add `bin` files too there

**Comment by anshumanv** [comment]
> master would always be more updated IMO.

Yeah, travis will push the updated docs onto gh-pages branch on each commit done on master from where they will be hosted(gh-pages branch). I just find keeping the generated docs with the actual code irrelevant because everytime you generate them you need to edit the changes you mentioned, for the `/bin` we can just use a simple `.md` and keep it with the `INIT`, `SCAFFOLDING` and other md files I believe.

> They are auto-generated and updated at each release by even. But if we need this on each commit we can add this using husky.

Isn't it a lot of manual effort for him? Why need husky when travis can do it in the background (so we don't have to wait for commit everytime, even a simple character removal[or any quick change for instance] will build the docs while committing which won't be nice imo)? 😄 

Also for some reason other routes don't work https://webpack.github.io/webpack-cli/modules/_generate_loader_index_.html

while they work here - https://webpack-cli.netlify.com/modules/_generators_loader_generator_.html

cc @evenstensberg @dhruvdutt

**Comment by rishabh3112** [comment]
> Why need husky when travis can do it in the background (so we don't have to wait for commit everytime, even a simple character removal[or any quick change for instance] will build the docs while committing which won't be nice imo)? 😄

Yeah, if it's possible using Travis then this would be alot better 😎

**Comment by anshumanv** [comment]
Yes exactly, but I'm still in favour of Netlify considering - https://www.netlify.com/github-pages-vs-netlify/ 😎

**Comment by ematipico** [comment]
Sorry if I chime in so suddenly. I think it's common sense to deploy the new docs when we release a new version. If we push at every commit/merge to master, we will publish things that are not published yet (and not yet available)

Surely I'm up to automate the task and to remove the docs from the repository. They shouldn't be tracked.

**Comment by anshumanv** [comment]
Let's find a better solution, later! 😄

**Pull request closed without merging**
