### PR TITLE
chore(travis): move npm ci to install task

### PR DESCRIPTION
**Pull request by DanielRuf**
**What kind of change does this PR introduce?**

Bugfix for build / CI.

**Did you add tests for your changes?** 
No, none needed.

**If relevant, did you update the documentation?**
No.

**Summary**
Currently `npm install` runs on CI in addition to `npm ci`.

Only `npm ci` should run. For this the needed commands should be in the install task.

**Does this PR introduce a breaking change?**

No.

**Other information**

### CODE REVIEW

**Comment by DanielRuf** [comment]
> @DanielRuf The most important CI builds failed. This way your PR can't be merged.
> 
> Please take a look at the CI results from travis (failure) and fix these issues.

This is just the release task so it's fine I guess =)

**Comment by ev1stensberg** [comment]
Could you rebase this?

**Comment by DanielRuf** [comment]
> Could you rebase this?

Done.

**Comment by DanielRuf** [comment]
Mh, Travis was removed from PR / push?

**Comment by DanielRuf** [comment]
Interesting: https://ci.appveyor.com/project/ev1stensberg/webpack-cli/build/818#L727

So a newer release of eslint-plugin-node is installed and needs at least Node.js 8 or later.

**Comment by DanielRuf** [comment]
> npm i -g npm@latest is redundant, look 2 lines up

Yes, because you added it yesterday or so ;-) See https://github.com/webpack/webpack-cli/commit/4cca6553d6ed960c5c7172574afe4bae9ac59eb4

**Comment by DanielRuf** [comment]
> I don't think that's needed. It didn't throw earlier?

The upgrade to Node.js 8? Well, it is needed. See https://travis-ci.org/webpack/webpack-cli/builds/376472056 which is due to the harmony features which came in Node.js 8.

**Comment by DanielRuf** [comment]
https://travis-ci.org/webpack/webpack-cli/jobs/376472060#L1214

**Comment by DanielRuf** [comment]
> we only should publish to npm on pushes to master, not PR's

There is an option for this in Travis CI, see https://docs.travis-ci.com/user/conditional-builds-stages-jobs/

**Comment by ematipico** [comment]
Good to know!

**Pull request merged**
