### PR TITLE
misc(bugfix): fix 'webpack-cli init' creating empty module.exports

### PR DESCRIPTION
**Pull request by jevan0307**
**What kind of change does this PR introduce?**

bugfix

**Did you add tests for your changes?**
No

**If relevant, did you update the documentation?**
No

**Summary**
Fix issue #271 . Fix the bug that command `webpack-cli init` will create a config file with empty module.exports. 

**Does this PR introduce a breaking change?**

No

**Other information**

### CODE REVIEW

**Comment by jevan0307** [comment]
@ev1stensberg I have made a commit based on your comment, please check it again.

**Comment by ev1stensberg** [comment]
#277 fixes this. You can reimplement that solution!

**Comment by jevan0307** [comment]
The new implementation has been committed.

btw, I also found 2 points might cause problems:
1. Yeoman will crashed with package.json with no name field. Since package.json created with `webpack-cli init` doesn't have name field, it might be a trouble in some use cases. This problem is similar to [this issue](https://github.com/Polymer/polymer-cli/issues/247).
2. We may have config files with different base names. However, commands except for `init`, such as `add`, always takes `webpack.config.js` as config file and throw an error when it does not exist. Is it reasonable?

Should I create issues for these two?

**Comment by ev1stensberg** [comment]
webpack-cli isn't responsible for initializing new npm/node libs, that's what `npm init` is about. About the second bullet point, yes.

**Comment by ev1stensberg** [comment]
Seems like there's some missing stuff from the branch I showed you. Do you mind if we merge that and  then you can do this issue instead?

 > We may have config files with different base names. However, commands except for init, such as add, always takes webpack.config.js as config file and throw an error when it does not exist. Is it reasonable?

**Comment by jevan0307** [comment]
Did I miss something in your branch? It is fine for me to merge that and close this pr.
I will create a issue for the new problem and create a new pr for it later.

**Comment by ev1stensberg** [comment]
Awesome sauce, thanks buddy! Hit me up if you need guidance.

**Comment by jevan0307** [comment]
@ev1stensberg I think the assertion in `lib/utils/modify-config-helper.js` when the specified file does not exist is necessary for the command like `add`, like what `lib/commands/migrate.js` has done to handle the error. Since #279 may need the error handler, please check it asap.

**Comment by ev1stensberg** [comment]
You can allow people to add args to the command, take care of the arg and pass it down to the helper

**Pull request closed without merging**
