### PR TITLE
Remove the extractSummary methods in test case

### PR DESCRIPTION
**Pull request by Mistyyyy**
**What kind of change does this PR introduce?**

Test cases about entry and stats

**Did you add tests for your changes?**

already exist

**If relevant, did you update the documentation?**

NA

**Summary**

**Does this PR introduce a breaking change?**

No

**Other information**

NA

### CODE REVIEW

**Comment by Mistyyyy** [comment]
I think before each test run, we should clean the output info which may contain the previous test result. I encountered this problem when I run the test cases, I get the incorrect test results.

**Comment by anshumanv** [comment]
Hi, thanks for your contribution. 

What's the motivation for this change? Is there some discussion that I've missed? :)

**Comment by Mistyyyy** [comment]
@anshumanv The discussion is here #1289

**Comment by ematipico** [comment]
@anshumanv basically the default output of webpack is changed. That nice output should not be here in the CLI (it should be in webpack side). So in one of my previous PRs I removed moved into `--pretty` and doing so I had to revisit most of the tests. These ones slipped from my eyesight and this PR is to fix them!

I am going to make a new PR to remove `--pretty` because we don't need it.

**Pull request merged**
