### PR TITLE
fix(webpack-cli): --progress flag output

### LINKED ISSUE #1551: bug: --progress doesn't ouput everything
**Describe the bug**

`--progress` flag doesn't output everything.

**What is the current behavior?**

`--progress` only prints the 100% compilation stage.

**To Reproduce**
`webpack --progress`.

**Expected behavior**

should print out every detail from 0 to 100% of compilation.

**Screenshots**
Screenshot at 2020-05-16 19-17-03

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

**Additional context**
Looking into it.

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**
FIX

**Did you add tests for your changes?**
No
**If relevant, did you update the documentation?**
No
**Summary**
Fixes #1551 
fixed progress flag output.

## Before 
Screenshot at 2020-05-19 11-38-26

## After
Screenshot at 2020-05-19 11-34-09
Screenshot at 2020-05-19 11-33-47

**Does this PR introduce a breaking change?**
NO

**Other information**

### CODE REVIEW

**Comment by rishabh3112** [comment]
All steps are visible "Before" as well.
The previous line is removed when percentage increases and new line is added to make progress bar look like it is "progressing". In a bigger project (where using `--progress` makes sense) this becomes more evident. So my suggestion would be to keep this particular as it is (or add a new option if it is actually needed for most of the people's use case).

**Comment by snitin315** [comment]
something like `webpack --progress detailed` ?

**Comment by rishabh3112** [comment]
I am -1 on this change as of now. We can do this when we get feature request for this from users.

**Comment by snitin315** [comment]
I agree

**Pull request closed without merging**
