### PR TITLE
chore(actions): add webpack version

### LINKED ISSUE #1149: [Enchancement] Implement webpack installation on CI
**Do you want to request a *feature* or report a *bug*?**
Refactor ( Feature? )

**What is the current behavior?**
`webpack` is installed as a direct dependency ( should be dev dependency ( fix at #1148) ). 
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Install webpack when running CI so that we can test both `webpack v4` and `webpack v5` over CI.

**If this is a feature request, what is motivation or use case for changing the behavior?**
A suggestion by @evilebottnawi 

**Please paste the results of `webpack-cli info` here, and mention other relevant information such as programming language.**
N/A

### PR DESCRIPTION
**Pull request by rishabh3112**
**What kind of change does this PR introduce?**
CI

**Did you add tests for your changes?**
N/A

**If relevant, did you update the documentation?**
No

**Summary**
Closes #1149 

**Does this PR introduce a breaking change?**

**Other information**

### CODE REVIEW

**Comment by ematipico** [comment]
Could you rebase? I believe we can merge it now

**Comment by rishabh3112** [comment]
@ematipico change I made was for GitHub actions, but it seems it is not enabled.

**Comment by ematipico** [comment]
That's now done! Let's merge it for now :)

**Comment by rishabh3112** [comment]
@ematipico the action seems to have a workflow error.
Here is a thread for fixing that through settings https://github.community/t5/GitHub-Actions/Workflow-error-action-not-allowed/td-p/37206

**Comment by ematipico** [comment]
I tried to tick the first option. Let's if it helps

**Comment by rishabh3112** [comment]
Yup that worked.
There was an error from my side in workflow. I have sent a new PR #1170. Sorry 😓.

**Pull request merged**
