### PR TITLE
tests: add test for --watch flag

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**
tests

**Did you add tests for your changes?**
Yes
**If relevant, did you update the documentation?**
NA
**Summary**
added test for `--watch` flag.

**Does this PR introduce a breaking change?**
No

**Other information**
No

### CODE REVIEW

**Comment by snitin315** [comment]
Yes, need to skip for windows, same as `serve` tests.

**Comment by evilebottnawi** [comment]
@snitin315 let's do it and open an issue for windows tests

**Comment by snitin315** [comment]
@evilebottnawi Done. Issue created -> #1878

**Review by evilebottnawi — APPROVED** [review]

**Review by anshumanv — APPROVED** [review]

**Pull request merged**
