### PR TITLE
refactor: use error validation from cli

### PR DESCRIPTION
**Pull request by anshumanv**
**What kind of change does this PR introduce?**
refactor

**Did you add tests for your changes?**
yes

**If relevant, did you update the documentation?**
NA

**Summary**
- We now have error validation in CLI, no need for redundant methods

**Does this PR introduce a breaking change?**
no

**Other information**

### CODE REVIEW

**Review by alexander-akait — DISMISSED** [review]

**Review by snitin315 — DISMISSED** [review]

**Comment by alexander-akait** [comment]
Can't understand why it is failing on windows right now, but works on other os, somebody can try to debug?

**Review by rishabh3112 — APPROVED** [review]

**Comment by rishabh3112** [comment]
> Can't understand why it is failing on windows right now, but works on other os, somebody can try to debug?

mjs tests are failing, could be related to v8 cache again.

**Comment by alexander-akait** [comment]
@rishabh3112 yep, but why it happens on windows and v5 only

**Comment by alexander-akait** [comment]
Please use `master` branch in future, otherwise I can't do rebase

**Review by snitin315 — APPROVED** [review]

**Pull request merged**
