### PR TITLE
refactor: 💡 remove defaults flag

### PR DESCRIPTION
**Pull request by anshumanv**
drop support for defaults flag

**What kind of change does this PR introduce?**

Drop support for defaults flag.

**Did you add tests for your changes?**
Removed corresponding tests

**If relevant, did you update the documentation?**
Yes

**Summary**
- Drop support for defaults flag, via discussion from https://github.com/webpack/webpack-cli/pull/1323

**Does this PR introduce a breaking change?**
Shouldn't break anything.

**Other information**

### CODE REVIEW

**Comment by snitin315** [comment]
One more place to remove => [docs](https://github.com/webpack/webpack-cli/tree/next/packages/webpack-cli#supported-arguments-and-commands)

**Comment by anshumanv** [comment]
Removed 👍

**Comment by evilebottnawi** [comment]
Good job! Thanks!

**Pull request merged**
