### PR TITLE
feat: union generators and utils package

### PR DESCRIPTION
**Pull request by anshumanv**
**What kind of change does this PR introduce?**
fix

**Did you add tests for your changes?**
Not yet

**If relevant, did you update the documentation?**
Yet to

**Summary**
- This package will union utils and generators package, quite a lot of overlap

**Does this PR introduce a breaking change?**
Yes, deprecating a package

**Other information**
/cc @alexander-akait evilebott

### CODE REVIEW

**Review by alexander-akait — COMMENTED** [review]
Looks good, let's fix tests

**Comment by anshumanv** [comment]
Some TS error 😞

**Comment by alexander-akait** [comment]
@anshumanv Can you rebase and fix conflict here (many files was removed so it can be removed from here too)

**Comment by anshumanv** [comment]
yep wip

**Comment by anshumanv** [comment]
Done @alexander-akait, just need fix TS err

**Comment by alexander-akait** [comment]
Let's merge as is, I will finish this PR in the next PR (can't finish work in fork :disappointed: ), we should not do it anymore in future

**Comment by anshumanv** [comment]
Closing in favour of https://github.com/webpack/webpack-cli/pull/2343

**Pull request closed without merging**
