### PR TITLE
[Don't merge] move to yarn workspaces and lerna

### PR DESCRIPTION
**Pull request by sendilkumarn**
This PR tries to convert the repo into monorepo using yarn workspaces and lerna

Let us have a discussion on this 

@ev1stensberg @fokusferit @ematipico

### CODE REVIEW

**Comment by ev1stensberg** [comment]
This might not be ideal, I'm chatting with some folks at chrome to see the best option

**Comment by ematipico** [comment]
Yarn workspaces it's basically a good way to handle lerna multiple projects. Do they can co-exists together?

**Comment by fokusferit** [comment]
I would like to have different dimensions answered here:

- What kind of problem do we want to solve here?
- Is monorepo the only answer to solve that? Maybe there is a "better"/"faster"/"easier" way to solve the problem?
- What are the trade-offs in moving to a monorepo vs. not? Do we really improve/win on different dimensions (speed of development, maintenance, release cycle etc. ?)

I will try to ping some friends from the Go and K8s community as they have experience with monorepo's.

**Comment by ev1stensberg** [comment]
I think we should take a step back and use scoped packages instead. Reopening later, but `lerna` seems like an overkill, w.r.t `Flow`, `packages` and so on compared to having sub-directories with `package.json`s

**Comment by sendilkumarn** [comment]
#261

**Comment by fokusferit** [comment]
Are we now back with monorepo and npx support?

**Comment by ev1stensberg** [comment]
Yep, figured out it was the best option.

**Comment by sendilkumarn** [comment]
Let me open a new PR.

**Pull request closed without merging**
