### PR TITLE
feat: Interactive Plugin

### PR DESCRIPTION
**Pull request by rishabh3112**
**Different from `interactive` at #586**: This PR just adds support for interactive output mode.

**What kind of change does this PR introduce?**
Feature

**Did you add tests for your changes?**

**If relevant, did you update the documentation?**
Not applicable

**Summary**
There are two output modes for `--watch` and `webpack serve`, standard and interactive.
Standard is already supported. This PR aims to implement that.

**Does this PR introduce a breaking change?**
No

**Other information**
/cc @alexander-akait

### CODE REVIEW

**Review by evenstensberg — COMMENTED** [review]
This is just empty code though....

**Comment by rishabh3112** [comment]
> This is just empty code though....


Yeah, I know 😆  . See #1796 closing comment for more info.

**Comment by alexander-akait** [comment]
Yes, let's finish it, although perhaps we should first do major release:
- drop node v12
- drop webpack-dev-server v3
- update deps (there is possible without big changes)

**Comment by rishabh3112** [comment]
>Yes, let's finish it, although perhaps we should first do major release:
> - drop node v12
> -  drop webpack-dev-server v3
> - update deps (there is possible without big changes)
> 

Okay, will do.
Should node version 10 be removed too?

**Comment by alexander-akait** [comment]
Sorry for losing your time, but let's close it due https://github.com/webpack/webpack-cli/issues/586#issuecomment-1528836367

In the future, we should study better and deeper the issues of what we should develop or not, in order not to get into such situations, once again I deeply apologize

**Pull request closed without merging**
