### PR TITLE
feat[utils]: opt to use config schema from core

### PR DESCRIPTION
**Pull request by anshumanv**
**What kind of change does this PR introduce?**

cleanup

**Did you add tests for your changes?**
Not yet

**If relevant, did you update the documentation?**
NA

**Summary**
- Config options are hardcoded which makes it tough to move forward with updates in webpack, use config keys from core directly

**Does this PR introduce a breaking change?**
No

**Other information**

### CODE REVIEW

**Comment by anshumanv** [comment]
Unusual test failing, taking a look

**Comment by evilebottnawi** [comment]
@anshumanv yep, can you look why sometime tests failed?

**Comment by anshumanv** [comment]
@evilebottnawi I checked and it seems the error is specific to this PR(different from random failures) - 
image

Though I'm not sure why would everything break due to this change, runs fine locally.

**Comment by evilebottnawi** [comment]
@anshumanv yep, very strange

**Comment by anshumanv** [comment]
@webpack/cli-team need small help,  can you guys take a look at this? Unable to figure out.

**Comment by snitin315** [comment]
@anshumanv ,
## for webpack@4  config is undefined - 
Screenshot at 2020-07-01 16-56-08

## for webpack@5
Screenshot at 2020-07-01 16-59-17

**Comment by evilebottnawi** [comment]
Need add check `isWebpack5`

**Comment by anshumanv** [comment]
Ah yes got it, thanks for looking @snitin315 @evilebottnawi  👍 
Fix in near future

**Comment by anshumanv** [comment]
@evilebottnawi @snitin315 review ready 👍

**Pull request merged**
