### PR TITLE
docs(contributing): update table of contents

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**

updated CONTRIBUTING.md table-of-contents.

**Did you add tests for your changes?**
NA
**If relevant, did you update the documentation?**
yes
**Summary**
NA

**Does this PR introduce a breaking change?**

**Other information**
NA

### CODE REVIEW

**Comment by snitin315** [comment]
@evilebottnawi can I be a member of the organisation?

**Comment by evilebottnawi** [comment]
@snitin315 It would be great if you fixed something or improved, not only docs. You could show yourself and other contributors could see your abilities

**Comment by snitin315** [comment]
@evilebottnawi I have added some fixes, features, and tests as well.

#1276     #1303    #1290    #1301  #1296

**Comment by evilebottnawi** [comment]
@snitin315 Good job! Let's start by inviting you in slack channel, please write me your email on sheo13666q@gmail . com

**Pull request merged**
