### PR TITLE
fix: respect `NODE_PATH` env variable

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**
bugfix

**Did you add tests for your changes?**
No.

**If relevant, did you update the documentation?**
No.

**Summary**

Fix https://github.com/webpack/webpack-cli/issues/3355

**Does this PR introduce a breaking change?**
No.

**Other information**
No

### CODE REVIEW

**Review by alexander-akait — APPROVED** [review]

**Review by alexander-akait — APPROVED** [review]
Feel free to merge when CI will be green

**Comment by snitin315** [comment]
Rebased.

**Comment by snitin315** [comment]
Something wrong on CI, debugging.

**Comment by alexander-akait** [comment]
Weird

> this.webpack.cli.getArguments()

**Comment by snitin315** [comment]
On windows CI [NODE_PATH is somehow defined](https://github.com/webpack/webpack-cli/actions/runs/3116733842/jobs/5054828493#step:6:9).

**Comment by snitin315** [comment]
@alexander-akait fixed, I moved the check outside of the loop.

**Review by alexander-akait — APPROVED** [review]
Looks good too, but can we add test case?

**Comment by alexander-akait** [comment]
@snitin315 Can you send the same PR for `webpack` itself too?

**Pull request merged**
