### PR TITLE
docs(cli): changed README to notify the beta version

### PR DESCRIPTION
**Pull request by ematipico**
**What kind of change does this PR introduce?**
Documentation

**Did you add tests for your changes?**
Not needed

**If relevant, did you update the documentation?**
Yes

**Summary**
I updated the README file to notify that the documentation will be for only for BETA, with a link to feedback.

**Does this PR introduce a breaking change?**

**Other information**
[Rendered format](https://github.com/webpack/webpack-cli/blob/194b224695a04c595f0b84a40646e427dd371da1/README.md)

### CODE REVIEW

**Comment by rishabh3112** [comment]
Are we keeping init as the name?

**Comment by ematipico** [comment]
I honestly didn't understand what's the plan. I thought it was "create" but the package itself is still called "init". If we have to move it to be "create" so we need to change the package itself. Sounds good?

**Comment by anshumanv** [comment]
init sounds better to me tbh, any motivations for changing it btw?

**Comment by rishabh3112** [comment]
> I honestly didn't understand what's the plan. I thought it was "create" but the package itself is still called "init". If we have to move it to be "create" so we need to change the package itself. Sounds good?

Yup

> init sounds better to me tbh, any motivations for changing it btw?

I don't know. Even changed that and I don't know any reasons on why he did that. Will ask him for more info.

**Pull request merged**
