### PR TITLE
test: fix architecture

### PR DESCRIPTION
**Pull request by anshumanv**
**What kind of change does this PR introduce?**
test reorg

**Did you add tests for your changes?**
yes

**If relevant, did you update the documentation?**
NA

**Summary**
Fix test arch, presently everything is mixed, scope them by commands 
```sh
test
  api
  build
    config
    cache
    name
    progress
    target
    other-options-by-directory
  info
  init
  help
  serve
  watch
  other-commands-by-directory
```

**Does this PR introduce a breaking change?**
No

**Other information**
/cc @alexander-akait

### CODE REVIEW

**Comment by alexander-akait** [comment]
Let's fix CI

**Review by snitin315 — DISMISSED** [review]
LGTM

**Comment by alexander-akait** [comment]
And couple more, the next task is migrate on `execa` everywhere https://github.com/webpack/webpack-cli/blob/master/test/utils/test-utils.js#L48 + migrate on `async` (it is faster), so all tests will need refactor from `const {} = run()` to `const {} = await run()`

**Comment by anshumanv** [comment]
yep let's do it incrementally

**Pull request merged**
