### PR TITLE
chore: bump serve package

### PR DESCRIPTION
**Pull request by anshumanv**
Fixes https://github.com/webpack/webpack-cli/issues/1814

**What kind of change does this PR introduce?**

bump

**Did you add tests for your changes?**
No need

**If relevant, did you update the documentation?**
NA

**Summary**

Bump serve package for release, old release is not compatible with latest cli it seems

**Does this PR introduce a breaking change?**
No

**Other information**

### CODE REVIEW

**Review by rishabh3112 — COMMENTED** [review]
@evenstensberg please do a `lerna publish` once. We should release all packages together.

**Comment by anshumanv** [comment]
Should I bump all packages?

**Comment by rishabh3112** [comment]
> Should I bump all packages?

It will be automatically done upon `lerna publish`.

**Comment by anshumanv** [comment]
read the docs, yep lerna will take care of all bumps, closing

Let's publish

**Pull request closed without merging**
