### PR TITLE
feat: respect the `infrastructureLogging.level` option

### LINKED ISSUE #2019: [Question] How to remove logging in watch mode?
I find cli always printing message(ex: Compilation finished, watching files for updates) in v4.

But I only need the error message.

So how to close the success message in v4?

### PR DESCRIPTION
**Pull request by alexander-akait**
**What kind of change does this PR introduce?**

feature

**Did you add tests for your changes?**

No change existing, WIP

**If relevant, did you update the documentation?**

No

**Summary**

fixes #2019

**Does this PR introduce a breaking change?**

No, it is feature

**Other information**

No

### CODE REVIEW

**Review by piecyk — APPROVED** [review]
Looks good.

**Comment by alexander-akait** [comment]
Need a lot of changes in tests :disappointed: WIP

**Comment by piecyk** [comment]
> Need a lot of changes in tests 😞 WIP

Yep, that's why the #2036 pr had so many changes.

**Comment by alexander-akait** [comment]
/cc @snitin315 we need more tests refactor:
- each tests should check `exitCode`/`stderr`/`stdout`
- some tests from `core-flag` is invalid (i.e. used invalid value)
- we need avoid `fs` checks there it is unnecessary

you can help me with this

**Comment by snitin315** [comment]
Yes I can help. Should I do it in this PR or separate?

**Comment by alexander-akait** [comment]
> separate

**Review by snitin315 — DISMISSED** [review]

**Comment by alexander-akait** [comment]
Hata macos and watching, we really need to stability this tests

**Pull request merged**
