### PR TITLE
Refactor for readability (v2 branch)

### PR DESCRIPTION
**Pull request by kingdaro**

### CODE REVIEW

**Comment by ev1stensberg** [comment]
I'll fix the conflicts, thank you so much @kingdaro !

**Comment by ev1stensberg** [comment]
Oh, wait, correct. Made some modifications to the add generator. Could you do that too? For the remove and update generator, just resolve the conflicts by setting it to your commit

**Comment by kingdaro** [comment]
Resolving conflicts, and in update-generator and remove-generator, the linter is complaining about something being used called `RawList`. Where's that from?

**Comment by ev1stensberg** [comment]
`const RawList = require("webpack-addons").rawList`, comment it out if it's complaining on unused, need to work on those generators later anyways, so for ease, you could just have it export the class for now, like in the conflict

**Comment by kingdaro** [comment]
Just to be 100% certain, here's the contents of the file: https://gist.github.com/kingdaro/f298dc8b7abf7ec8589ab6b23405e588

So the bottom bit is what's coming from `v2`, and the top is what's currently in my cleanup commit. I want the one on the bottom, yes?

**Comment by ev1stensberg** [comment]
yep, that's correct

**Comment by ev1stensberg** [comment]
Done @kingdaro ? No changes to `add` ?

**Comment by kingdaro** [comment]
Yeah, that was a mistake, fixed now. Should be good to go 👍

**Pull request merged**
