### PR TITLE
chore: update release script

### PR DESCRIPTION
**Pull request by evilebottnawi**
**What kind of change does this PR introduce?**

**Did you add tests for your changes?**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

### CODE REVIEW

**Review by anshumanv — APPROVED** [review]

**Comment by anshumanv** [comment]
wrong branch?

**Comment by evilebottnawi** [comment]
@anshumanv no, I merge next into master

**Comment by anshumanv** [comment]
Gotcha I thought we'll make master as v3 and make next as master, how do we access v3 code?

**Comment by evilebottnawi** [comment]
we don't need v3 anymore :smile: we have v4

**Comment by evilebottnawi** [comment]
Anyway we can create v3 branch using git checkout, but I think it is unnecessary

**Review by anshumanv — APPROVED** [review]

**Comment by evilebottnawi** [comment]
We need looking for how we can speed up our build, because wait 30 minutes is very very very long :disappointed:

**Comment by anshumanv** [comment]
We validate full schema and every single flag on 3 platforms with 3 node version so I'm not surprised 😄

**Pull request merged**
