### PR TITLE
tests: add tests for cli plugin resolver

### PR DESCRIPTION
**Pull request by anshumanv**
**What kind of change does this PR introduce?**

tests

**Did you add tests for your changes?**
yes

**If relevant, did you update the documentation?**
no

**Summary**
no

**Does this PR introduce a breaking change?**
no

**Other information**
/cc @alexander-akait

### CODE REVIEW

**Review by rishabh3112 — COMMENTED** [review]
Need CI fix, rest looks good.

**Review by alexander-akait — APPROVED** [review]

**Comment by anshumanv** [comment]
random failures 😫 rerunning

**Comment by alexander-akait** [comment]
Let's ignore, I will investigate to this in the future

**Comment by anshumanv** [comment]
Thanks

**Pull request merged**
