### PR TITLE
docs: add core-team link to CODE_OF_CONDUCT.md

### LINKED ISSUE #1328: core-team link in CODE_OF_CONDUCT not present
**Describe the bug**

[core-team link not present](https://github.com/webpack/webpack-cli/blob/next/CODE_OF_CONDUCT.md)

**What is the current behavior?**

link not present

**To Reproduce**
1. Go to 'https://github.com/webpack/webpack-cli/blob/next/CODE_OF_CONDUCT.md'
2. observe in written , '@webpack/core-team'
3. observe that link isn't present

**Expected behavior**

I believe that like '@webpack/cli-team', '@webpack/core-team' link should also work.

**Screenshots**

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

**Additional context**

### PR DESCRIPTION
**Pull request by Parikshit-Hooda**
**What kind of change does this PR introduce?**
docs: add a missing link to code_of_conduct.md

**Did you add tests for your changes?**
not required.

**If relevant, did you update the documentation?**
not required.

**Summary**
add https://github.com/orgs/webpack/teams/core-team to @webpack-core phrase

motivation: missing link fix.

**Does this PR introduce a breaking change?**

no

**Other information**
resolves #1328

### CODE REVIEW

**Comment by anshumanv** [comment]
You can also make it bold like it's done for the `cli-team`

**Comment by snitin315** [comment]
[https://github.com/orgs/webpack/teams/core-team](https://github.com/orgs/webpack/teams/core-team)

Do we have to a member of team to access the link? It's giving me a 404 error.

**Comment by anshumanv** [comment]
> Do we have to a member of team to access the link? It's giving me a 404 error.

I think you need to be a member of the org to access teams, in that case not sure if it makes sense to linkify the team links since outsiders won't be able to access them.

**Comment by evilebottnawi** [comment]
Thanks

**Pull request merged**
