### PR TITLE
fix : fix comment typo in webpack.config.js template file

### PR DESCRIPTION
**Pull request by wana4**
**What kind of change does this PR introduce?**

fix typo in webpack.config.js
`obout` -> `about`

### CODE REVIEW

**Review by anshumanv — APPROVED** [review]

**Review by snitin315 — DISMISSED** [review]
Good catch, Thanks!!

**Review by jamesgeorge007 — DISMISSED** [review]

**Comment by snitin315** [comment]
@wana4 Can you accept CLA ?

**Review by rishabh3112 — DISMISSED** [review]

**Review by rishabh3112 — APPROVED** [review]
Fixed commit message

**Comment by wana4** [comment]
> @wana4 Can you accept CLA ?

Done.

**Review by evenstensberg — APPROVED** [review]
lgtm

**Review by snitin315 — APPROVED** [review]

**Review by anshumanv — APPROVED** [review]
Thanks

**Comment by rishabh3112** [comment]
Thanks

**Pull request merged**
