### PR TITLE
chore: ignore tests from npm

### PR DESCRIPTION
**Pull request by anshumanv**
**What kind of change does this PR introduce?**

fix

**Did you add tests for your changes?**
NA
**If relevant, did you update the documentation?**

**Summary**
Fix https://github.com/webpack/webpack-cli/pull/2561
Fix https://github.com/webpack/webpack-cli/issues/2560

**Does this PR introduce a breaking change?**
No

**Other information**

### CODE REVIEW

**Review by alexander-akait — DISMISSED** [review]

**Review by snitin315 — DISMISSED** [review]

**Review by jamesgeorge007 — COMMENTED** [review]
I think we should have it at the package level.

**Comment by anshumanv** [comment]
> I think we should have it at the package level.

What are the gains?

**Comment by alexander-akait** [comment]
Ideally in future we should move all tests from `__tests__` to `test/api`

**Comment by alexander-akait** [comment]
Right now we can apply this fix as temporary

**Comment by jamesgeorge007** [comment]
I don't think having `.npmignore` at the project root would work here being a monorepo. 

```js
!**/*__tests__
```

https://github.com/webpack/webpack-cli/blob/f26ebc105e140992639864fa01950454abd716ac/packages/webpack-cli/package.json#L25

**Comment by anshumanv** [comment]
> I don't think having .npmignore at the project root would work here being a monorepo.

investigating

**Comment by anshumanv** [comment]
Ah they're coming from tests in utils

image

**Comment by anshumanv** [comment]
yeah I think it makes sense to have npmignore in `webpack-cli` package

**Review by alexander-akait — COMMENTED** [review]
Can you test it manually using `npm pack`?

**Comment by anshumanv** [comment]
Turns out npmignore can't override files property in package.json, excluded the tests from the files property in package.json

image

/cc @jamesgeorge007 @alexander-akait

**Comment by anshumanv** [comment]
> Can you test it manually using npm pack?

@alexander-akait done above

**Comment by alexander-akait** [comment]
@anshumanv Maybe we need remove `npmignore`

**Comment by anshumanv** [comment]
yep I think we can remove as it's not being picked up

**Comment by alexander-akait** [comment]
Approve for this

**Comment by anshumanv** [comment]
yep lets resolve it late

**Review by snitin315 — APPROVED** [review]

**Comment by anshumanv** [comment]
@webpack/cli-team need review

**Review by jamesgeorge007 — APPROVED** [review]

**Pull request merged**
