### PR TITLE
docs(contributing): adds prebuild instructions

### PR DESCRIPTION
**Pull request by misterdev**
Adds few lines to `CONTRIBUTING.md` about the undocumented `boostrap` npm script that should be run to set up the project

### CODE REVIEW

**Comment by TheLarkInn** [comment]
Wow thanks a bunch for this! I was looking for this myself earlier and didn't even realize it wasn't in CONTRIBUTING.md

**Comment by misterdev** [comment]
Happy to help!

**Comment by dhruvdutt** [comment]
@mikesherov Can you please sign the CLA?

**Comment by mikesherov** [comment]
You mean @misterdev

**Comment by misterdev** [comment]
I see it is already signed :)
screenshot 2019-02-27 at 17 01 56

Anyway I've renewed my signature ;)

**Comment by misterdev** [comment]
I've indented those instructions to make them even with #768

**Comment by evenstensberg** [comment]
We're currently freezing PR's until our tests are fixed, sorry for the delay

**Pull request merged**
