### PR TITLE
Remove Async

### PR DESCRIPTION
**Pull request by Kumaravinash9**
**What kind of change does this PR introduce?**
Remove async 

**Did you add tests for your changes?**
No
**If relevant, did you update the documentation?**
NO
**Summary**

**Does this PR introduce a breaking change?**
No

**Other information**

### CODE REVIEW

**Review by anshumanv — CHANGES_REQUESTED** [review]
Can you fix lint and sign CLA?

**Comment by anshumanv** [comment]
Also please read commit guidelines

**Comment by Kumaravinash9** [comment]
Problem comes with Prettier .

**Comment by alexander-akait** [comment]
Smoketests was removed, because they duplicate logic for simple tests, anyway thanks for the PR

**Pull request closed without merging**
