### PR TITLE
fix: multi compiler progress output

### PR DESCRIPTION
**Pull request by alexander-akait**
**What kind of change does this PR introduce?**

bug fix

**Did you add tests for your changes?**

No, but we need after we will fix a problem in webpack

**If relevant, did you update the documentation?**

No need

**Summary**

fixes https://github.com/webpack/webpack-cli/issues/3604

**Does this PR introduce a breaking change?**

No

**Other information**

There is a bug inside webpack:
```
TypeError: Cannot read properties of undefined (reading 'then')
    at /home/akait/IdeaProjects/webpack-cli/node_modules/webpack/lib/ProgressPlugin.js:358:27
    at Hook.eval [as callAsync] (eval at create (/home/akait/IdeaProjects/webpack-cli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:8:17)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/akait/IdeaProjects/webpack-cli/node_modules/tapable/lib/Hook.js:18:14)
    at /home/akait/IdeaProjects/webpack-cli/node_modules/webpack/lib/Compiler.js:1192:33
    at finalCallback (/home/akait/IdeaProjects/webpack-cli/node_modules/webpack/lib/Compilation.js:2787:11)
    at /home/akait/IdeaProjects/webpack-cli/node_modules/webpack/lib/Compilation.js:3092:11
    at Hook.eval [as callAsync] (eval at create (/home/akait/IdeaProjects/webpack-cli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/akait/IdeaProjects/webpack-cli/node_modules/tapable/lib/Hook.js:18:14)
    at /home/akait/IdeaProjects/webpack-cli/node_modules/webpack/lib/Compilation.js:3085:38
    at eval (eval at create (/home/akait/IdeaProjects/webpack-cli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:17:1)

Node.js v18.12.0
```

looks like cache was not design for multi compiler mode, we need to fix it

### CODE REVIEW

**Comment by snitin315** [comment]
Yeah, it looks like to straightforward as we assumed.

**Comment by alexander-akait** [comment]
Don't have ideas how to fix it properly... We need multi compiler and apply plugin, but don't have a hook for it, we can use `handler`, but it will loose ability to set options, it was not design for this, very bad

**Comment by alexander-akait** [comment]
And we can't just create `compiler`, because it require `callback` for `watch`, I told Tobias what it was bad design for multi compiler plugins

**Comment by alexander-akait** [comment]
Okay, I found solution, but it still need improve some things on webpack side

**Comment by alexander-akait** [comment]
After we shipped some new things to webpack (I will send a PR soon), we will need to update webpack here, run CI again and we can emrge

**Comment by snitin315** [comment]
@alexander-akait so does that mean this feature will not work with older version of webpack v5? We would need to mention it in docs.

**Comment by alexander-akait** [comment]
I don't undestand why github doesn't show my sent commits

**Pull request closed without merging**
