### PR TITLE
feat: add alias `a` for `analyze` option

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**
feature

**Did you add tests for your changes?**
Yes
**If relevant, did you update the documentation?**

**Summary**

add alias `a` for `analyze` option

**Does this PR introduce a breaking change?**
No

**Other information**
No

### CODE REVIEW

**Review by evenstensberg — APPROVED** [review]

**Comment by alexander-akait** [comment]
@snitin315 I think we should implement short alias for all flags, let's do it, it should be not hard, just put this logic in `makeOption`

**Comment by snitin315** [comment]
Yep, lets do it.

**Comment by rishabh3112** [comment]
> I think we should implement short alias for all flags, let's do it, it should be not hard, just put this logic in makeOption

Definitely should automate this! Although a heads up, algorithm for this should make sure flags which are already assigned an alias don't change if we add or remove flags. This is because, unstable alias will result in bad DX (a potential breaking change in every new flag addition).
Example:
`--serve` is assigned `-s`
`--save` is now added
`--save` should not be assigned `-s`, `--serve` should continue to have `-s` alias.

This should also hold true even if we rename a flag imo (eg. if `--serve` is renamed to `--dev-server`, alias should remain `-s` only).

**Comment by alexander-akait** [comment]
Yes, we should respect existing short alias, but it is not hard

**Review by evenstensberg — COMMENTED** [review]
Could you rebase?

**Comment by alexander-akait** [comment]
@snitin315 Do we really need this? What do you think?

**Comment by snitin315** [comment]
@alexander-akait I think alias for all options are not needed, only for popular options.

**Comment by alexander-akait** [comment]
Yeah, let's close maybe I will find time to autogenerate short keys for all options, we just need to create a script and json file and generate them to avoid overlapping, but no one request it, so let's close

**Pull request closed without merging**
