### PR TITLE
tests: check for lock file creation

### PR DESCRIPTION
**Pull request by jamesgeorge007**
**What kind of change does this PR introduce?**
test update

**Did you add tests for your changes?**
This is a test update.

**If relevant, did you update the documentation?**
Nope

**Summary**
Follow up of #1478 

**Does this PR introduce a breaking change?**
Nope

**Other information**
N/A

### CODE REVIEW

**Comment by jamesgeorge007** [comment]
> If we're doing this we need to also include init tests

bb19844

**Comment by jamesgeorge007** [comment]
@anshumanv checking for `node_modules` directory seems to solve the issue.

**Comment by jamesgeorge007** [comment]
Inconsistent behavior 🤔

**Comment by anshumanv** [comment]
Exactly, that's why I had to leave this out

**Comment by rishabh3112** [comment]
@anshumanv @jamesgeorge007,
I am writing this to be the common thread for anyone writing tests for scaffolding sub packages (plugin, init, loader, etc.) can refer to.

There are various sources in code that are causing the problem, some of them are:

- Errors and inconsistency in utils written for scaffolding (used by init, plugin, etc)

- Inconsistent install time for packages on the CI container itself.

- Errors while installation of packages on CI, adrupts installation of packages as well as causes non generation of lock file.


So I would advice to not include tests for files and folders related to installation of packages (lockfile, node_modules, etc) until it is fixed. Meanwhile, I am trying to fix them. If you have ideas on this, you can help out by sending suggestions to my PR :).

/cc @evilebottnawi

**Comment by jamesgeorge007** [comment]
Closing in regard to #1508

**Pull request closed without merging**
