### PR TITLE
misc(dep): add webpack 4 as peer dependency

### LINKED ISSUE #295: webpack is not listed as a peer
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
you can install webpack-cli witghout webpack and get no warning

**If the current behavior is a bug, please provide the steps to reproduce.**
npm install webpack-cli on an empty project

**What is the expected behavior?**
An npm peer requirement warning

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**

### PR DESCRIPTION
**Pull request by dhruvdutt**
**What kind of change does this PR introduce?**
Dependencies definition, Fixes #295 

**Summary**
Adds webpack 4 as a peer dependency

**Does this PR introduce a breaking change?**
No

**Other information**
Followed same versioning as [webpack-dev-server](https://github.com/webpack/webpack-dev-server/blob/master/package.json#L42)

### CODE REVIEW

**Comment by ematipico** [comment]
Why a beta version has been added  as peer dependency?

**Comment by dhruvdutt** [comment]
@ematipico 
> Followed same versioning as [webpack-dev-server](https://github.com/webpack/webpack-dev-server/blob/master/package.json#L42)

Are there any features that came after beta which are required by cli?

**Comment by ev1stensberg** [comment]
This is correct, latest webpack should be the one we're targeting

**Comment by ematipico** [comment]
Alpha and beta are releases that talks by themselves, they are still not officials. I think the package.json should state `webpack: ^4.0.0` as peer dep.

**Pull request merged**
