### PR TITLE
tests: for --optimization-mangle-exports & --optimization-used-exports

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**
tests, fix

**Did you add tests for your changes?**
yes
**If relevant, did you update the documentation?**
NA
**Summary**
with the new release of webpack 5 new flags `--optimization-mangle-exports` & `--optimization-used-exports` are supported now. handling test cases for the same.

**Does this PR introduce a breaking change?**
No

**Other information**

### CODE REVIEW

**Comment by anshumanv** [comment]
@evilebottnawi do we need test with mangleExports in config as raised in https://github.com/webpack/webpack-cli/issues/1677? If not we can close the config PR.

**Comment by evilebottnawi** [comment]
@anshumanv more tests are better

**Comment by anshumanv** [comment]
Okay, will keep it open, edited your comment @snitin315

**Comment by evilebottnawi** [comment]
Please regenerate lock file

**Comment by anshumanv** [comment]
Cant regenerate because we're on webpack latest, for next it's only generated while installing in CI. Hence when webpack releases with updated terser rerunning in all PRs will fix. /cc @snitin315

**Comment by evilebottnawi** [comment]
@anshumanv Can you try to do it?

**Comment by snitin315** [comment]
I just did no changes in lockfile as of now.

**Comment by anshumanv** [comment]
Closing in favour of https://github.com/webpack/webpack-cli/pull/1732

**Comment by anshumanv** [comment]
@snitin315 quick question, what's the approach you followed to trace this back? Just curious

**Comment by snitin315** [comment]
Theese flags or the terser warning?

**Comment by anshumanv** [comment]
terser warning

**Comment by snitin315** [comment]
`webpack --node-args --trace-depriciation`

**Pull request closed without merging**
