### PR TITLE
chore: v3.3.4

### PR DESCRIPTION
**Pull request by evenstensberg**
CI Test Run for v.3.3.4

### CODE REVIEW

**Comment by ematipico** [comment]
It's `v3.3.4`

**Comment by evenstensberg** [comment]
Gotcha, will tag it as that

**Comment by ematipico** [comment]
Also, from the change log, looks like there are new features. Should it be `3.4.0`?

**Comment by evenstensberg** [comment]
No, those are for monorepo pkgs, hard to maintain a changelog for each of those, maybe we should introduce a new flag in the changelog generator called `mono:`, wdyt?

**Pull request merged**
