### PR TITLE
chore: create package run (WIP)

### PR DESCRIPTION
**Pull request by rishabh3112**
**What kind of change does this PR introduce?**
refactor, Moves executer to it's own package

**Did you add tests for your changes?**
Will be moving tests to the repo in this PR itself, for now there is a dummy test.

**If relevant, did you update the documentation?**
No, will write documentation for the package in this PR itself.

**Summary**
As suggested by Emanuele, I am moving the executer to it's seperate package.

**Does this PR introduce a breaking change?**
No

**Other information**
Tasks needed to be done here
- [ ] Move Tests
- [ ] Write documentation
- [ ] Release package to npm

### CODE REVIEW

**Comment by rishabh3112** [comment]
@ematipico should I keep the new package as `peer` or direct dependency to the `webpack-cli` package ?

**Comment by ematipico** [comment]
I don't know yet. I still have to understand how's the whole user flow.

**Comment by evilebottnawi** [comment]
Why we need that package? What is use case? As I see it makes no sense to use this package without webpack-cli. Therefore, separate it into two packages makes no sense

**Comment by rishabh3112** [comment]
This was suggested by @ematipico to separate it from main package to reduce dependency of main package.

For more context, you may look at https://github.com/webpack/webpack-cli/issues/1261 and the PR where I implemented it.

**Comment by rishabh3112** [comment]
I think about it overall and shifting it to it's own package will not be helpful in reducing main package size. So, I am closing this PR.
Thanks everyone!

**Pull request closed without merging**
