### PR TITLE
fix(bin): extension detection (#724)

### PR DESCRIPTION
**Pull request by lakatostamas**
**What kind of change does this PR introduce?**
bugfix

**Did you add tests for your changes?**
No, but I created test repositories: 
https://github.com/lakatostamas/webpack-babel
https://github.com/lakatostamas/webpack-ts

**Summary**
Issue: https://github.com/webpack/webpack-cli/issues/724
This commit introduced a bug in the default config file discovery: https://github.com/webpack/webpack-cli/pull/693/commits/b61220edb1bb7a61cf9ee7370e7aa752143e7684#diff-daabbe74e88640829a3ad9e9899efd8cR79
Before this commit, the extension of `webpack.config.ts` was `.ts` in the default configFile discovery, but after this commit, it became just `ts` (without `.`). `webpack.config.babel.js` extension is `js` now, but it should be `.babel.js`. With this pull request, I introduce a fix, which gets the name of the default config file and removes the `webpack.config` or `webpackfile` from it.
I don't know how to add tests when the extension of webpack config is not `js`. I haven't found any example, but if you tell me how to do it, I would happily add some tests to cover these cases.

**Does this PR introduce a breaking change?**
No

### CODE REVIEW

**Comment by zzh8829** [comment]
This should fix the problem of .babel.js discussed in https://github.com/webpack/webpack/issues/5960
Looks like the error was actually introduced in https://github.com/webpack/webpack-cli/commit/14ec0a5acf5fbe47bd04be0ec2712d6f355907eb#diff-daabbe74e88640829a3ad9e9899efd8cR90

**Comment by ematipico** [comment]
We should add a bin test for that, if possible

**Comment by ematipico** [comment]
I personally prefer install an additional devDependency and make sure that we don't break those kind of scenarios. After all this is a package used by lot of people :) what do you think?

**Comment by lakatostamas** [comment]
Okay, that makes sense. I added `webpack.config.ts` test

**Pull request merged**
