### PR TITLE
Correct linking from NPM pages

### PR DESCRIPTION
**Pull request by constgen**
**What kind of change does this PR introduce?**

Fix links to `OPTIONS.md` and to Homepage when open from NPM site https://www.npmjs.com/package/webpack-cli

**Did you add tests for your changes?**

No

**If relevant, did you update the documentation?**

Kind of

**Summary**

When open homepage it navigates to root project when it should navigate to the package

When open `OPTIONS.md` it just returns 404

**Does this PR introduce a breaking change?**

No

**Other information**

No

### CODE REVIEW

**Review by alexander-akait — COMMENTED** [review]
Why?

**Comment by constgen** [comment]
Steps to reproduce the issue
1. Open https://www.npmjs.com/package/webpack-cli
2. Scroll to the very bottom of the page
3. Click on `OPTIONS.md` link
4. 404 page is open

**Comment by snitin315** [comment]
I will take care of it.

**Pull request closed without merging**
