### PR TITLE
feat: add mjs support

### PR DESCRIPTION
**Pull request by rishabh3112**
**What kind of change does this PR introduce?**
Feature

**Did you add tests for your changes?**
Yup
**If relevant, did you update the documentation?**
No
**Summary**
New PR that supersedes #1786 

**Does this PR introduce a breaking change?**
No

**Other information**
Fresh start

### CODE REVIEW

**Comment by alexander-akait** [comment]
Yep, WIP on this

**Comment by alexander-akait** [comment]
Found the problem - `v8-compile-cache`, doesn't support dynamic `import`, I will add `DISABLE_V8_COMPILE_CACHE` env for tests and put this in the issue as temporary workaround

**Comment by rishabh3112** [comment]
Confirm this. Will update the PR accordingly as native import works too without `v8-compile-cache`.

**Comment by alexander-akait** [comment]
@rishabh3112 don't touch this PR, I am working on it

**Comment by rishabh3112** [comment]
> @rishabh3112 don't touch this PR, I am working on it

I am already done with native import + added env variable to github actions locally 😞 
If you like I can push that.

**Comment by alexander-akait** [comment]
> I am already done with native import + added env variable to github actions locally disappointed

What do you mean?

**Comment by alexander-akait** [comment]
Tests should be fine now, I don't know how to better fix bug in `v8-compile-cache`, maybe we should move it inside webpack-cli and fix bug

**Comment by rishabh3112** [comment]
> What do you mean?

I was done with required changes at that point of changes with a different approach. Yours is better so never mind 🙂 

> Tests should be fine now, I don't know how to better fix bug in v8-compile-cache, maybe we should move it inside webpack-cli and fix bug

Yup seems way to go.

**Comment by alexander-akait** [comment]
Very weird, it works locally, but throw an error on CI, even for node@14, tests in webpack-cli is pain

**Comment by rishabh3112** [comment]
Seems to be passing everywhere on atleast (few are still running) now. Will look into it if this run fails.

**Comment by alexander-akait** [comment]
Bug on `nyc` side, don't have ideas how we can fix it now, let's fix it late, I will put it in TODO, maybe we need `babel` for nyc

**Comment by alexander-akait** [comment]
Anyway es configuration is not supported fully due `v8-compile-cache` bug, I think I will resolve it for the next release

**Pull request merged**
