### PR TITLE
feat: next major version

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**

**Did you add tests for your changes?**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

### CODE REVIEW

**Review by alexander-akait — DISMISSED** [review]

**Comment by alexander-akait** [comment]
@snitin315 Feel free to merge

**Comment by snitin315** [comment]
I wIll use this branch to merge all changes for the next version. Then merge this PR at last.

**Comment by alexander-akait** [comment]
@snitin315 Can you list all remains todos and which packages we need to update it to have everything up to date

**Comment by alexander-akait** [comment]
@snitin315 can you rebase?

**Comment by snitin315** [comment]
@alexander-akait yes, for some reason I am unable to access github on my laptop.

**Comment by snitin315** [comment]
@alexander-akait Following TODOs are pending:

- https://github.com/webpack/webpack-cli/blob/9539ea1c8a5276c3ca46ee983b379b3ede74ad40/packages/webpack-cli/src/webpack-cli.ts#L1949
- https://github.com/webpack/webpack-cli/blob/9539ea1c8a5276c3ca46ee983b379b3ede74ad40/test/serve/invalid-schema/invalid-schema.test.js#L25

I'm not sure what we need to do in 1st todo regarding --config, can you please explain?

**Review by alexander-akait — APPROVED** [review]

**Pull request merged**
