### PR TITLE
Upgrade to Jest 19

### PR DESCRIPTION
**Pull request by okonet**
**What kind of change does this PR introduce?**
build related change

**Did you add tests for your changes?**

N/A

**If relevant, did you update the documentation?**

N/A

### CODE REVIEW

**Comment by okonet** [comment]
@ev1stensberg could you please look into the failing tests? Something with mocks I guess.

**Comment by ev1stensberg** [comment]
Sure. Mind waiting 1:30h? I'm doing Google Hashcode right now

**Comment by ev1stensberg** [comment]
My guess is that you removed the rootpath, so it can't find relative paths to the mock folder

**Comment by okonet** [comment]
No, it was failing with the config in place. It's not needed in this form BTW since these are defaults.

**Comment by ev1stensberg** [comment]
checking them out now, giveme some mins

**Comment by okonet** [comment]
I'll rebase and merge.

**Pull request merged**
