### PR TITLE
tests: fix tests as per v4

### PR DESCRIPTION
**Pull request by rishabh3112**
**What kind of change does this PR introduce?**
bugfix and tests

**Did you add tests for your changes?**
yes
**If relevant, did you update the documentation?**
n/a
**Summary**
The tests are broken. An attempt to fix them and add new ones

**Does this PR introduce a breaking change?**
adhesive changes

**Other information**

### CODE REVIEW

**Comment by rishabh3112** [comment]
Is there an alternative to `--output-library` and `--output-library-target` in the new CLI @evenstensberg?

**Comment by evenstensberg** [comment]
We actually need to change up all these tests

**Comment by rishabh3112** [comment]
Yes, that's what this PR is for.
I am asking whether new flags would be added now in future ?

**Comment by rishabh3112** [comment]
May I know the reason for closing draft ?

**Comment by evenstensberg** [comment]
We gotta do further work here before proceeding.

**Comment by rishabh3112** [comment]
Okay, what kindof work? If it's test related, it's a fine place to do that 😅.

**Pull request closed without merging**
