### PR TITLE
feat: add support for dev containers

### PR DESCRIPTION
**Pull request by rishabh3112**
**What kind of change does this PR introduce?**
Development experience

**Did you add tests for your changes?**
N/A

**If relevant, did you update the documentation?**
Yes

**Summary**
Add support for dev containers for letting contributors to quickly setup development environment.
https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers

**Does this PR introduce a breaking change?**
No

**Other information**
No

### CODE REVIEW

**Review by alexander-akait — COMMENTED** [review]
We need to add small docs how to use it, but I am afraid nobody will use it

**Comment by rishabh3112** [comment]
> We need to add small docs how to use it, but I am afraid nobody will use it

Added documentation to the `CONTRIBUTING.md`, only that extension is needed if user has docker.

**Review by alexander-akait — APPROVED** [review]
Feel free to merge

**Review by snitin315 — APPROVED** [review]

**Pull request merged**
