### PR TITLE
feat: bump CI Node to 14

### PR DESCRIPTION
**Pull request by anshumanv**
**What kind of change does this PR introduce?**
build

**Did you add tests for your changes?**
NA

**If relevant, did you update the documentation?**
NA

**Summary**

Trying running CI on Node 14

**Does this PR introduce a breaking change?**
No

**Other information**

### CODE REVIEW

**Comment by anshumanv** [comment]
Some tests failing on v14 @evilebottnawi need to be fixed

**Comment by evilebottnawi** [comment]
@anshumanv feel free to start working on this

**Comment by anshumanv** [comment]
@evilebottnawi issue in https://github.com/nodejs/node/issues/32987#issuecomment-635726114 need update shelljs

**Review by evilebottnawi — COMMENTED** [review]
Do our users have warnings on Node@14 too?

**Review by evilebottnawi — COMMENTED** [review]
Can you try to run `yarn upgrade` and send the fixed lock file?

**Comment by anshumanv** [comment]
> Do our users have warnings on Node@14 too?

Yep seems to pop up from shelljs
image

**Comment by evilebottnawi** [comment]
`0.8.4` fixed it, so we should just bump our deps in lock file

**Comment by anshumanv** [comment]
Yep already, https://github.com/webpack/webpack-cli/pull/1731 need fix typescript build then 😞

**Comment by evilebottnawi** [comment]
It should be easy, we don't use many types

**Comment by anshumanv** [comment]
https://github.com/webpack/webpack-cli/pull/1885 should fix it

**Comment by anshumanv** [comment]
Yep the error is gone, now just need fix CI with new warning messages in Node 14

**Review by evilebottnawi — APPROVED** [review]
/cc @webpack/cli-team

**Review by rishabh3112 — APPROVED** [review]

**Pull request merged**
