### PR TITLE
chore: bump interpret for .mjs support

### PR DESCRIPTION
**Pull request by anshumanv**
**What kind of change does this PR introduce?**

chore

**Did you add tests for your changes?**
Yes

**If relevant, did you update the documentation?**
NA

**Summary**
Interpret has added .mjs support in latest version so bumping it then will be working on mjs support + tests

**Does this PR introduce a breaking change?**
No

**Other information**

### CODE REVIEW

**Comment by evilebottnawi** [comment]
Fail :confused:

**Comment by anshumanv** [comment]
> Fail 😕

Need update terser because a warning is coming from it which is failing the tests

**Comment by evilebottnawi** [comment]
WIP on terser

**Comment by anshumanv** [comment]
Yes, running into some issue with mjs files, will update once resolved

**Review by evenstensberg — COMMENTED** [review]
Could you rebase?

**Review by evenstensberg — COMMENTED** [review]
needs rebase

**Review by evenstensberg — CHANGES_REQUESTED** [review]
Needs test & rebase

**Comment by evilebottnawi** [comment]
@anshumanv high priority before release, thanks for helping

**Comment by anshumanv** [comment]
yes today 👍

**Comment by evenstensberg** [comment]
Nice

**Comment by anshumanv** [comment]
Running into little problem while adding tests for mjs config, I'm using rechoir to setup the environment and it uses require syntax to read any config format, even tried adding a package.json file with type `module` but seeing this 😞 @evilebottnawi @evenstensberg do you have any ideas about this?

`
"[webpack-cli] Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/anshumanv/Code/GitHub/webpack-cli/test/config-format/mjs/webpack.config.mjs
        at Module.load (internal/modules/cjs/loader.js:980:11)
        at Function.Module._load (internal/modules/cjs/loader.js:875:14)
        at Module.require (internal/modules/cjs/loader.js:1022:19)
        at require (internal/modules/cjs/helpers.js:72:18)
        at ConfigGroup.requireConfig (/Users/anshumanv/Code/GitHub/webpack-cli/packages/webpack-cli/lib/groups/ConfigGroup.js:86:22)
        at ConfigGroup.resolveConfigFiles (/Users/anshumanv/Code/GitHub/webpack-cli/packages/webpack-cli/lib/groups/ConfigGroup.js:162:41)
        at ConfigGroup.run (/Users/anshumanv/Code/GitHub/webpack-cli/packages/webpack-cli/lib/groups/ConfigGroup.js:206:20)
        at WebpackCLI._handleGroupHelper (/Users/anshumanv/Code/GitHub/webpack-cli/packages/webpack-cli/lib/webpack-cli.js:212:46)
        at /Users/anshumanv/Code/GitHub/webpack-cli/packages/webpack-cli/lib/webpack-cli.js:245:30
        at async WebpackCLI.runOptionGroups (/Users/anshumanv/Code/GitHub/webpack-cli/packages/webpack-cli/lib/webpack-cli.js:242:9) {
      code: 'ERR_REQUIRE_ESM'
    }"
`

**Comment by evilebottnawi** [comment]
@anshumanv we should use `await import()` to load `mjs`, need think how we can implement this

**Review by evenstensberg — COMMENTED** [review]
Could you push the testcase?

**Review by evilebottnawi — COMMENTED** [review]
We use `require` to load config, right?

**Comment by evilebottnawi** [comment]
Maybe https://github.com/davidtheclark/cosmiconfig/issues/224#issuecomment-560112802?

**Comment by evilebottnawi** [comment]
Alternative solutions https://github.com/standard-things/esm

**Comment by rishabh3112** [comment]
**Update**
`await import()` is not working as it's functionality is reverted in node.
I have created a seperate PR with `esm` package (which also fails locally).
These two are only options for now that I could find except using `babel` which is not a good idea as whole package is in cjs.

**Comment by anshumanv** [comment]
Closing in favour of #1786

**Pull request closed without merging**
