### PR TITLE
ci: add Node 17

### PR DESCRIPTION
**Pull request by nschonni**
**What kind of change does this PR introduce?**

**Did you add tests for your changes?**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

This is a duplicate of https://github.com/webpack/webpack-cli/pull/3014, but seeing if the comment that the latest core changes have addressed this are true

### CODE REVIEW

**Review by alexander-akait — COMMENTED** [review]
We should exclude Node.js v17 for webpack v4 and webpack-dev-server v3

**Comment by nschonni** [comment]
> We should exclude Node.js v17 for webpack v4 and webpack-dev-server v3

Done

**Comment by alexander-akait** [comment]
Feel free to ping me when CI will be green

**Comment by nschonni** [comment]
@alexander-akait got a failure, but maybe I misunderstood your comment about the exclusions. Should it be all webpack 4, and all devserver-3 jobs on 17, or just that one combo I currently excluded

**Comment by alexander-akait** [comment]
All webpack v4 should not be run on Node.js v17, and all webpack-dev-server v3 pipelines should not be run on Node.js v17

**Comment by nschonni** [comment]
@alexander-akait looks like it's happy now

**Pull request merged**
