### PR TITLE
feat(chore): Added update-notifier package

### PR DESCRIPTION
**Pull request by jamesgeorge007**
**What kind of change does this PR introduce?**
feature

**Summary**

[update-notifier](npmjs.com/package/update-notifier) as from the docs, inform users of updates in a non-intrusive way. 
 

**Did you add tests for your changes?**
Nope

**If relevant, did you update the documentation?**
Nope

### CODE REVIEW

**Comment by jamesgeorge007** [comment]
@evenstensberg @anshumanv Thoughts :thinking:

**Comment by jamesgeorge007** [comment]
@evenstensberg @anshumanv Thoughts :thinking:

**Comment by ematipico** [comment]
What's the frequency of this message? Is it shown also on CI?

**Comment by jamesgeorge007** [comment]
@ematipico Didn't get you :thinking:

**Comment by ematipico** [comment]
1. The message shown by the library: does it appear also in the CI? (travis, azure)
2. Could you set up the interval? https://www.npmjs.com/package/update-notifier#options-and-custom-message

**Comment by jamesgeorge007** [comment]
> The message shown by the library: does it appear also in the CI? (travis, azure)

  Not sure :thinking:

**Comment by jamesgeorge007** [comment]
@ematipico What causes the CI build to fail :thinking:

**Comment by ematipico** [comment]
I do agree too

**Comment by jamesgeorge007** [comment]
@evenstensberg @ematipico Are we gonna have this feature included within the next release :thinking:

**Comment by jamesgeorge007** [comment]
@evenstensberg @ematipico Are we gonna have this feature included with the next release :thinking:

**Comment by evenstensberg** [comment]
Aye

**Comment by evenstensberg** [comment]
Thanks for your Pull Request though, if you want, I can find something else that we need to have in this version of the CLI?

**Comment by jamesgeorge007** [comment]
@evenstensberg May I know the reason why you don't prefer to have this feature included even in the future :thinking: Everyone else accepted this to be a cool addition :confused:

**Comment by jamesgeorge007** [comment]
> Thanks for your Pull Request though, if you want, I can find something else that we need to have in this version of the CLI?

Yes of course :clap:

**Comment by evenstensberg** [comment]
We're gonna have this in the new CLI version, but this one is more conservative with respect to introducing more dependencies. Thanks! I'll find something later this week (have to catch up on a lot of PRs)

**Comment by evenstensberg** [comment]
https://github.com/webpack/webpack-cli/issues/746 this one is up for grabs

**Pull request closed without merging**
