### PR TITLE
chore: regenerate lock file

### PR DESCRIPTION
**Pull request by anshumanv**
**What kind of change does this PR introduce?**

chore

**Did you add tests for your changes?**
No

**If relevant, did you update the documentation?**
NA

**Summary**
regenerated lock file to test in CI

**Does this PR introduce a breaking change?**
No

**Other information**

### CODE REVIEW

**Comment by anshumanv** [comment]
ts build is failing lemme see

**Comment by evilebottnawi** [comment]
Yes, cache on register side :disappointed:

**Comment by evilebottnawi** [comment]
Let's add workaround for CI for webpack@5, `yarn add terser-webpack-plugin --dev ` (only for webpack@5)

**Comment by anshumanv** [comment]
okay will do

**Comment by anshumanv** [comment]
Added here - https://github.com/webpack/webpack-cli/pull/1732

**Comment by anshumanv** [comment]
yep in near future

**Comment by anshumanv** [comment]
Closed in favour of https://github.com/webpack/webpack-cli/pull/1885

**Pull request closed without merging**
