### PR TITLE
fix: union generators and utils package

### PR DESCRIPTION
**Pull request by anshumanv**
**What kind of change does this PR introduce?**
fix

**Did you add tests for your changes?**
Not yet

**If relevant, did you update the documentation?**
Yet to

**Summary**
- This package will union utils and generators package, quite a lot of overlap

**Does this PR introduce a breaking change?**
Yes, deprecating a package

**Other information**
/cc @alexander-akait evilebott

### CODE REVIEW

**Comment by alexander-akait** [comment]
@anshumanv Can you finish it?

**Comment by anshumanv** [comment]
yep will get back on this in a while

**Comment by alexander-akait** [comment]
Please focus on it, I want to do it before today release

**Comment by anshumanv** [comment]
Closed in favour of - https://github.com/webpack/webpack-cli/pull/2289

**Pull request closed without merging**
