### PR TITLE
fix: union webpack-scaffold and generators package

### PR DESCRIPTION
**Pull request by anshumanv**
**What kind of change does this PR introduce?**
fix

**Did you add tests for your changes?**
Not yet

**If relevant, did you update the documentation?**
Yet to

**Summary**
- Union webpack-scaffold and generators package
- rm unused utils

**Does this PR introduce a breaking change?**
- Yep, this package is deprecated

**Other information**

### CODE REVIEW

**Review by evilebottnawi — COMMENTED** [review]
Let's fix tests

**Comment by anshumanv** [comment]
yep

**Comment by anshumanv** [comment]
@evilebottnawi tests good

**Review by evilebottnawi — DISMISSED** [review]

**Review by snitin315 — CHANGES_REQUESTED** [review]
Can we update the readme? 

https://github.com/webpack/webpack-cli#utilities

**Comment by anshumanv** [comment]
> Can we update the readme?

Updated a lot more instances to prevent future potential one liners 👍

**Review by snitin315 — APPROVED** [review]
Thanks!

**Review by rishabh3112 — APPROVED** [review]
Looks good to me.
Apart from that, we will need to update our [`webpack-scaffold-starter`](https://github.com/rishabh3112/webpack-scaffold-starter) to accommodate this change. Feel free to send pull request there as well.

**Review by evilebottnawi — APPROVED** [review]

**Pull request merged**
