### PR TITLE
tests: Fix mixed spaces/tabs in stdin.js

### PR DESCRIPTION
**Pull request by Zarthus**
**What kind of change does this PR introduce?**
It fixes mixed tabs/spaces in a single test file.

**Did you add tests for your changes?**
No

**If relevant, did you update the documentation?**
Irrelevant.

**Summary**

Reading through the changelog for v3.0.5 it was quite clear to notice one of the files was indented with two spaces, I normalized it to tabs.

**Does this PR introduce a breaking change?**
No

### CODE REVIEW

**Comment by Zarthus** [comment]
I did a quick grep within the tests/ directory for '  ' without any finds, so it looked OK for me.

**Comment by dhruvdutt** [comment]
@Zarthus Thanks for your contribution. :tada:  These things are really hard to notice. :eye: Glad you fixed it.

**Comment by ematipico** [comment]
Thank you!!

**Pull request merged**
