### PR TITLE
Bugfix/skip broken tests

### PR DESCRIPTION
**Pull request by ematipico**
**What kind of change does this PR introduce?**
Bugfix tests

**Did you add tests for your changes?**
Yes

**If relevant, did you update the documentation?**
Not needed

**Summary**
Skipping a test that is not finished. It should be deleted though.

**Does this PR introduce a breaking change?**
No

**Other information**

### CODE REVIEW

**Comment by evenstensberg** [comment]
@dhruvdutt PTAL

**Comment by dhruvdutt** [comment]
@ematipico Can you please fix the commitlint?

**Comment by ematipico** [comment]
@dhruvdtt the problem is that for some reason Travis is trying to lint all the commits from master! I think I will try again with another PR...

**Comment by dhruvdutt** [comment]
@ematipico Just don't you just squash all the commits of this PR?

**Comment by ematipico** [comment]
There's just one commit of mine, I can't squash any further. I will try with a fresh new repo and fresh new PR.

**Pull request merged**
