### PR TITLE
fix: add configuration for mode option none

### LINKED ISSUE #1302: bug: unit test failing for mode option none
**Describe the bug**

bug found due to -> #1301 

Screenshot from 2020-03-08 15-40-10

**What is the current behavior?**

**Expected behavior**

the test should pass, recived value should be = `"none"`

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

**Additional context**
Looking into it.

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**

Fixes #1302 

**Did you add tests for your changes?**
corresponding test ->  #1301 
**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

NO
**Other information**

### CODE REVIEW

**Comment by ematipico** [comment]
This is confusing. Why don't you add the fix inside the PR where you created the test?

**Comment by snitin315** [comment]
> This is confusing. Why don't you add the fix inside the PR where you created the test?

Actually I checked out a new branch before jumping into the issue. I realized it later after fixing the bug, Sorry for the confusion I created. It won't happen again in the future.

Screenshot from 2020-03-09 15-06-25

**Comment by ematipico** [comment]
It's not a problem, but it's so confusing that I don't know what I have to do 😅  could you please help?

**Comment by snitin315** [comment]
You can merge this pull request then I will rebase the test PR, and that will fix everything.

**Pull request merged**
