### PR TITLE
feat: display monorepos in info output

### PR DESCRIPTION
**Pull request by anshumanv**
**What kind of change does this PR introduce?**

feat

**Did you add tests for your changes?**
yes

**If relevant, did you update the documentation?**
Not yet

**Summary**
- Displaying workspace info would be useful to know if the issue is related to webpack-cli or the monorepo tool that the user is using

**Does this PR introduce a breaking change?**

no

**Other information**
no

### CODE REVIEW

**Review by alexander-akait — APPROVED** [review]

**Review by rishabh3112 — APPROVED** [review]

**Review by jamesgeorge007 — APPROVED** [review]

**Review by snitin315 — APPROVED** [review]

**Comment by anshumanv** [comment]
no way to test it since CI doesn't have any workspaces I think, but seems to work locally, anyone has ideas on how to test?

**Comment by snitin315** [comment]
Maybe create a mock workspace if possible?

**Comment by anshumanv** [comment]
It is very strange though, https://github.com/tabrindle/envinfo/blob/main/src/helpers/monorepos.js says it looks for local package json and so it should show up, will check in depth

**Comment by anshumanv** [comment]
It only looks for monorepos in current dir (not project root), if we want to test we'll have to cwd to project root and then run info there

**Review by alexander-akait — APPROVED** [review]

**Pull request merged**
