### PR TITLE
chore(deps): lockdown versions

### PR DESCRIPTION
**Pull request by dhruvdutt**
**What kind of change does this PR introduce?**

**Did you add tests for your changes?**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

### CODE REVIEW

**Comment by evenstensberg** [comment]
@dhruvdutt could you try to check which of the packages needs to be updated for the CI's to succeed?

https://stackoverflow.com/questions/44316064/gyp-err-build-error-stack-error-make-failed-with-exit-code-2

**Comment by evenstensberg** [comment]
Gotta fix that babel issue on tsc by disabling it, then this is green I think

**Comment by dhruvdutt** [comment]
Babel issue is fixed. Only Node 12 is failing now.
Trying to fix it with updating other packages.

**Comment by evenstensberg** [comment]
Great, I’ll do a review as quickly as possible

**Comment by evenstensberg** [comment]
If you're gonna close a PR I suggest you update this one instead of cold-closing one of our contributors that are actively maintaining the project @dhruvdutt

**Comment by evenstensberg** [comment]
Could you rebase?

**Comment by evenstensberg** [comment]
@anshumanv feel free to replicate this PR and submit a new one

**Pull request closed without merging**
