### PR TITLE
fix: remove silent flag

### PR DESCRIPTION
**Pull request by anshumanv**
**What kind of change does this PR introduce?**

chore

**Did you add tests for your changes?**
Yes

**If relevant, did you update the documentation?**
Yes

**Summary**

- Delet silent flag.
- Silent flag doesn't work now and flags from core can handle it.

**Does this PR introduce a breaking change?**
Yes, this was present in v3

**Other information**

Ref - https://github.com/webpack/webpack-cli/pull/1325#issuecomment-660466342

### CODE REVIEW

**Comment by anshumanv** [comment]
> How we can disable all output now?

this doesn't work right now anyways so, no way to do it right now, once core flags are in we can use `--no-stats`

**Comment by snitin315** [comment]
> > How we can disable all output now?
> 
> this doesn't work right now anyways so, no way to do it right now, once core flags are in we can use `--no-stats`

We already support `--no-stats` + we can always do `--stats=none`, something I'm missing?

**Comment by evilebottnawi** [comment]
Just not, here is other problem to disable all output you need to disable logging too

**Comment by anshumanv** [comment]
> Just note, here is other problem to disable all output you need to disable logging too

Yes, we should rethink and intercept logging to not log anything

**Comment by anshumanv** [comment]
For that I think we should first align all the logging, that we do.

In some places we're doing console.error, in some we're writing to process.stdout and in some places we're using the logger.

What do you suggest @evilebottnawi @snitin315?

**Comment by snitin315** [comment]
I think we should use `logger` only.

**Comment by evilebottnawi** [comment]
Agree, we should use `logger`, it is allow to disable logging on CLI side too

**Comment by anshumanv** [comment]
> Agree, we should use logger, it is allow to disable logging on CLI side too

Will handle it 👍

**Pull request merged**
