### PR TITLE
refactor: generators

### PR DESCRIPTION
**Pull request by rishabh3112**
**What kind of change does this PR introduce?**
refactor and type fixes

**Did you add tests for your changes?**
No

**If relevant, did you update the documentation?**
No

**Summary**
- Standardize the templates location for `init-generator`
- Created template location for `addon-generator`
- Cleanup and remove duplicate code by refactoring writing section
- Explicit mention types in `configtest`
- Add types for changes done to generator

**Does this PR introduce a breaking change?**
No

**Other information**
No

### CODE REVIEW

**Review by alexander-akait — CHANGES_REQUESTED** [review]
Don't forget to add them in `files`

**Comment by rishabh3112** [comment]
> Don't forget to add them in `files`

I didn't get what you said.

**Comment by alexander-akait** [comment]
look at the `files` field in `package.json`, because we should publish additional directories with package too

**Comment by rishabh3112** [comment]
Sure, will do.

**Comment by snitin315** [comment]
Canceled the run because it would have failed for `webpack@latest`

**Review by alexander-akait — APPROVED** [review]

**Review by snitin315 — APPROVED** [review]

**Review by anshumanv — APPROVED** [review]

**Review by jamesgeorge007 — DISMISSED** [review]

**Review by snitin315 — CHANGES_REQUESTED** [review]
Need to fix CI

**Pull request merged**
