### PR TITLE
docs: update jsdoc

### PR DESCRIPTION
**Pull request by dhruvdutt**
**What kind of change does this PR introduce?**

**Did you add tests for your changes?**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

### CODE REVIEW

**Comment by ev1stensberg** [comment]
Swap this to next branch

**Comment by ev1stensberg** [comment]
Would probably be better to open a new PR on this

**Comment by dhruvdutt** [comment]
I'm getting weird errors like this when I run `npm run jsdoc` on `next` branch. It works fine for `master` branch.

> FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

@ev1stensberg Can you try if it works for you?

**Comment by ev1stensberg** [comment]
Look up which paths jsdoc is looking for as well as if you have a existing docs folder

**Pull request merged**
