### PR TITLE
Remove typos and minor errors in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by Aloneduckling**
**What kind of change does this PR introduce?**
Remove typos and minor errors in CONTRIBUTING.md

**Did you add tests for your changes?**
NA
**If relevant, did you update the documentation?**
Yes
**Summary**
Remove typos and minor errors in CONTRIBUTING.md

**Does this PR introduce a breaking change?**
NA

**Other information**

### CODE REVIEW

**Comment by alexander-akait** [comment]
Please rebase your fork and accept CLA

**Comment by Aloneduckling** [comment]
I have removed some minor grammatical errors and typos in this PR in the CONTRIBUTING.md file.

**Comment by Aloneduckling** [comment]
> Please rebase your fork and accept CLA



> Please rebase your fork and accept CLA

I have accepted CLA. How do I rebase my fork of this repo

**Comment by snitin315** [comment]
@Aloneduckling - https://medium.com/@topspinj/how-to-git-rebase-into-a-forked-repo-c9f05e821c8a

**Comment by Aloneduckling** [comment]
> @Aloneduckling - https://medium.com/@topspinj/how-to-git-rebase-into-a-forked-repo-c9f05e821c8a

@snitin315 thanks, I did it

**Comment by snitin315** [comment]
Always create PR against master.

**Comment by Aloneduckling** [comment]
> Always create PR against master.

Alright will do it from now

**Comment by snitin315** [comment]
You have created PR from your `origin:master` to `upstream:docs-serve` branch,  There are no new changes 😞

**Comment by snitin315** [comment]
Please create a new PR with your changes. I did a rebase on my PR #2438 which is using `docs-serve` branch.

**Comment by Aloneduckling** [comment]
Alright I will create a PR from my `origin:master` to `webpack-cli:maser` is this okay?

**Comment by snitin315** [comment]
That is okay for a single PR. You can also refer to the branching model as explained in Contributing guide - https://github.com/webpack/webpack-cli/blob/master/.github/CONTRIBUTING.md#naming-a-branch

**Pull request merged**
