### PR TITLE
docs: correct use of individual package in node env

### PR DESCRIPTION
**Pull request by hemal7735**
**What kind of change does this PR introduce?**
README docs

**Did you add tests for your changes?** NA

**If relevant, did you update the documentation?** NA

**Summary**
I found out while playing around with the examples given in the doc.
We transpile the `ts` files using babel which converts 

`export default [func/variables]` 
to 
``` bash
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = default_1
```

**Does this PR introduce a breaking change?** No

### CODE REVIEW

**Comment by hemal7735** [comment]
@dhruvdutt can you review please?

**Comment by ematipico** [comment]
Although this is a bug!
In a nodejs environment we don't have the concept of `.default` because we just use `CommonJS` file resolution!

**Comment by hemal7735** [comment]
How will we fix the TypeScript compilation for that? Isn't this the work of babel? 
In `CommonJS` we don't have the concept of `.default`, however we do have the concept of exporting more than one things, and in this case, it is a simple default.
In package - `serve`, we export many things, in that case, we will need to use this, or `serve` will need the same structure as rest of the packages.

**Comment by ematipico** [comment]
> basarat.gitbooks.io/typescript/docs/tips/defaultIsBad.html

That's an opinion and everything is relative. That's not the issue here.

@hemal7735 No, we use TypeScript for compiling the code. What I would expect from the compilation is something like this:

Before
```js
export default something() {}
```

After 
```js
module.exports = something() {}
```

Instead, TypeScript does something dumb and consider `default` as the name of the configure when instead it's a particular syntax.

**Comment by hemal7735** [comment]
> @hemal7735 No, we use TypeScript for compiling the code. What I would expect from the compilation is something like this:
> 
> Before
> 
> ```js
> export default something() {}
> ```
> 
> After
> 
> ```js
> module.exports = something() {}
> ```
> 
> Instead, TypeScript does something dumb and consider `default` as the name of the function when instead it's a particular syntax.
> Probably there's a configuration for that.

It will still do if we have both `default` and `named` exports. But yeah, I got your point that it should do 
```js
module.exports = something() {}
```
if default is the only export. Maybe it's a feature request for both babel and tsc 😅

**Pull request merged**
