### PR TITLE
chore(package): update jest-cli to version 23.0.1

### PR DESCRIPTION
**Pull request by dhruvdutt**
Closes #465

**What kind of change does this PR introduce?**

**Did you add tests for your changes?**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

### CODE REVIEW

**Comment by ev1stensberg** [comment]
Let greenkeeper do this.

**Comment by dhruvdutt** [comment]
@ev1stensberg Yes, greenkeeper does the commit but we have to manually open the PR (like this) if a version change happens after an open PR.

Check [this comment](https://github.com/webpack/webpack-cli/pull/465#issuecomment-392346814). "Update to this version instead :rocket:"
image

**Comment by ev1stensberg** [comment]
update package lock as well

**Pull request merged**
