### PR TITLE
chore: update webpack to 5.12.2

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**
update webpack, fix ci issues

**Did you add tests for your changes?**
WIP
**If relevant, did you update the documentation?**
YES
**Summary**

update webpack

**Does this PR introduce a breaking change?**
No

**Other information**
Fixes  https://github.com/webpack/webpack-cli/pull/2333

### CODE REVIEW

**Comment by anshumanv** [comment]
Already - https://github.com/webpack/webpack-cli/pull/2333

**Review by anshumanv — COMMENTED** [review]
Need to also update entry-flag test

**Comment by snitin315** [comment]
Yes WIP.

**Review by alexander-akait — APPROVED** [review]
Feel free to merge when CI will be green

**Review by anshumanv — APPROVED** [review]

**Review by jamesgeorge007 — APPROVED** [review]

**Pull request merged**
