### PR TITLE
misc(remove code): remove unused code

### PR DESCRIPTION
**Pull request by evenstensberg**
**What kind of change does this PR introduce?**

Removes unused code

**Did you add tests for your changes?**
N/A
**If relevant, did you update the documentation?**
N/A
**Summary**
Removes unused code.
**Does this PR introduce a breaking change?**
N/A
**Other information**
N/A

### CODE REVIEW

**Comment by evenstensberg** [comment]
Could someone fix CI?

**Comment by snitin315** [comment]
I will fix it 👍

**Review by evilebottnawi — APPROVED** [review]
/cc @snitin315 Do you work on it?

**Comment by snitin315** [comment]
@evilebottnawi Yes here #1801 , one major issue is that help output is not working with `webpack@beta.30` though its working fine with `webpack@latest`. See CI logs for more info.

**Review by snitin315 — APPROVED** [review]

**Pull request merged**
