### PR TITLE
Fixes 206

### PR DESCRIPTION
**Pull request by sumit-gupta91**
**What kind of change does this PR introduce?**
fixes-206

**Did you add tests for your changes?**
No

### CODE REVIEW

**Comment by sumit-gupta91** [comment]
Hi @ev1stensberg not able to figure out why travis CI failed, can you please help me out here ?

**Comment by ev1stensberg** [comment]
Hi! Will review later, got errands to do today. Thank you so much for your PR!

**Comment by ev1stensberg** [comment]
@sumit-gupta91 there's some issues with travis, could you give an absolute link of the issue that you're fixing?

**Comment by sumit-gupta91** [comment]
Hi @ev1stensberg, here is the link [https://github.com/webpack/webpack-cli/issues/206]

**Comment by ev1stensberg** [comment]
@sumit-gupta91 I think that's a wrong link, gave 404

**Pull request closed without merging**
