### PR TITLE
feat: install required packages for loading command automatically

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**
feature

**Did you add tests for your changes?**
WIP in tests
**If relevant, did you update the documentation?**
NA
**Summary**

https://github.com/webpack/webpack-cli/pull/2809#issuecomment-870755830

**Does this PR introduce a breaking change?**
No

**Other information**
No

### CODE REVIEW

**Comment by snitin315** [comment]
smoke tests passing locally 😞.

**Review by alexander-akait — COMMENTED** [review]
hm, do you think it is better do for all commands? I think it will be good for init only, but I am fine with install all by default

**Comment by snitin315** [comment]
Yes, we should do it for all.

**Comment by alexander-akait** [comment]
@snitin315 Do we need this, I just checked and we don't ask about installation when I use `webpack init`

**Pull request closed without merging**
