### PR TITLE
chore: upgrade eslint plugins

### PR DESCRIPTION
**Pull request by anshumanv**
**What kind of change does this PR introduce?**
chore: upgrade eslint plugins

**Did you add tests for your changes?**
NA

**If relevant, did you update the documentation?**
NA

**Summary**
wip

**Does this PR introduce a breaking change?**

no

**Other information**

### CODE REVIEW

**Comment by anshumanv** [comment]
types fix is wip

**Comment by alexander-akait** [comment]
@anshumanv can you rebase and continue PR (also please use master)

**Comment by anshumanv** [comment]
yes wip

**Comment by alexander-akait** [comment]
Can you use `master`?

**Comment by anshumanv** [comment]
Opened https://github.com/webpack/webpack-cli/pull/2443

Closing this

**Pull request closed without merging**
