### PR TITLE
Added yarn lock file to gitignore

### LINKED ISSUE #454: Add yarn.lock to .gitignore or add yarn's lock file in project
**Is your feature request related to a problem? Please describe.**
Since we are using yarn in webpack for most of parts (everywhere we setup using simple `yarn` command). When anyone run `yarn`, additional lock file is added to project, which shouldn't be done everytime anyone run 'yarn'.. We can either ignore 'package-lock' as it is generated by npm and keep only yarn.lock in our project directory or we can ignore 'yarn.lock' and  keep only 'package-lock.json' in directory..
**Describe the solution you'd like**
Add yarn.lock to .gitignore or a better thing would be to add package-lock.json to .gitignore since most of our developers use yarn anyway..
I can send a PR, once i get opinion on which file to ignore and which to keep.

### PR DESCRIPTION
**Pull request by nveenjain**
**What kind of change does this PR introduce?**
Refactoring
**Did you add tests for your changes?**
N/A
**If relevant, did you update the documentation?**
N/A
**Summary**
Added yarn lock file to .gitignore. Fixes #454 
**Does this PR introduce a breaking change?**
No

### CODE REVIEW

**Comment by ev1stensberg** [comment]
Could you rebase?

**Comment by nveenjain** [comment]
wait, why did we change current branch to next? It is not a breaking change :sweat_smile:

**Comment by ev1stensberg** [comment]
It's the current develop branch

**Comment by ev1stensberg** [comment]
Thanks!

**Pull request merged**
