### PR TITLE
feat(init): add features and refactor

### PR DESCRIPTION
**Pull request by rishabh3112**
**What kind of change does this PR introduce?**
Feature and refactors

**Did you add tests for your changes?**
Yes, WIP

**If relevant, did you update the documentation?**
No

**Summary**
Part of #1509 
- Addition of `--force` flag to force config generation (in case of 0CJS as well).

**Does this PR introduce a breaking change?**
No.

**Other information**
**Work In Progress**,

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@rishabh3112 @webpack/cli-team  Sometimes CI failed, can you investigate?

**Comment by rishabh3112** [comment]
@evilebottnawi It occurs when even 100s timeout isn't enough some tests of `init`, which is due to time variation which occurs due to installation of packages, dependent on speed(installation or/and write) of CI containers.

**Comment by evilebottnawi** [comment]
@rishabh3112 Let's move `jest.setTimeout(120000);` to `setupTest.js` using `setupFilesAfterEnv: ['<rootDir>/setupTest.js'],`

**Comment by evilebottnawi** [comment]
@rishabh3112 Ready for merge?

**Comment by rishabh3112** [comment]
Yes

**Pull request merged**
