### PR TITLE
feat: add `--unix-socket` flag

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**
feature

**Did you add tests for your changes?**
Yes
**If relevant, did you update the documentation?**
WIP
**Summary**

Fix https://github.com/webpack/webpack-cli/issues/2752

**Does this PR introduce a breaking change?**
No

**Other information**
No

### CODE REVIEW

**Comment by snitin315** [comment]
I think we also need to refactor some code in webpack-dev-server v4. 

Screenshot 2021-06-04 at 3 00 41 PM

https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L573

Maybe something like - 

```diff
- const parsedIP = ipaddr.parse(address);
+ if (ipaddr.isValid(address)) { 
+     parsedIP = ipaddr.parse(address);
+ }
```

**Review by alexander-akait — COMMENTED** [review]
Let's start with refactoring, move logic from https://github.com/webpack/webpack-cli/blob/master/packages/serve/src/startDevServer.ts into https://github.com/webpack/webpack-cli/blob/master/packages/serve/src/index.ts, it will allow reduce unnecessary checks

**Comment by snitin315** [comment]
I think we can close in favor of `webpack serve --ipc`?

/cc @alexander-akait

**Comment by alexander-akait** [comment]
Yes, i was wrong, we need to do it on webpack dev server side, sorry

**Pull request closed without merging**
