### PR TITLE
Refactor generator logic for readability

### PR DESCRIPTION
**Pull request by kingdaro**
Promise flattening + some formatting changes for readability

### CODE REVIEW

**Comment by ev1stensberg** [comment]
Hey @kingdaro , could you pick the changes instead of adding commits from the old PR? 
I.E, just the 3 latest commits, and use `git pull` or `git rebase feature/add`to resync? Alternatively you can use a new branch and then pick the changes there

**Comment by kingdaro** [comment]
Sure thing, wasn't sure how to do this properly.  Thanks for the patience :)

**Comment by ev1stensberg** [comment]
@kingdaro no worries, will you do it now? I can hold of any work on the branch until you're done, so you'd avoid conflicts 👍

**Comment by kingdaro** [comment]
Yeah, working on it now.

**Comment by kingdaro** [comment]
I'm going to try again another time. I don't know what I did wrong, but I don't think I have the mental capacity to fix it right now. Thanks for your time, though.

**Comment by ev1stensberg** [comment]
open a new branch, `git rebase origin feature/add` and then copy paste everything from the last 3 commits

**Comment by ev1stensberg** [comment]
Hi @kingdaro ! Would you take another look? ❤️

**Comment by kingdaro** [comment]
Hey @ev1stensberg , I'm willing to take another look now. I'm going to open another pull request with the changes from this PR. Hopefully it'll go a little more smoothly this time 🙂

**Pull request closed without merging**
