### PR TITLE
docs: create initial CHANGELOG.md file

### PR DESCRIPTION
**Pull request by avivr**
Add CHANGELOG.md file.
Generated using cz-conventional-changelog cli tool.

This address issue #130

### CODE REVIEW

**Comment by ev1stensberg** [comment]
@avivr Hey! Thanks for the PR! I think we can simplify this a lot for the first changelog. What do you say @okonet ?

**Comment by ev1stensberg** [comment]
Hey Aviv! I'd suggest you just to put up a blank one for us to fill. Found a default one at webpack-defaults. Thanks! 

---

# Change Log

All notable changes to this project will be documented in this file. See [standard-version](https://github.com/conventional-changelog/standard-version) for commit guidelines.

x.x.x / <year>-<month>-<day>
==================

  * Bug fix -
  * Feature -
  * Chore -
  * Docs -

**Comment by avivr** [comment]
thanks for the feedback @ev1stensberg , i wasn't aware of webpack-defaults.
I changed it to match the CHANGELOG from the templates folder, hope that's what you meant.

**Comment by ev1stensberg** [comment]
Yup! I'll push some changes to this branch later, and I'll merge :)

**Comment by ev1stensberg** [comment]
Hmm, seems like you didn't join the collab list. Sorry about that @avivr .. Could you make a new PR for `v.1.3.1` using https://github.com/conventional-changelog/standard-version ? Seems like they generated the same changelog as in the initial PR, but I cut some commits that weren't needed there.

**Pull request merged**
