### PR TITLE
feat: use webpack.config as default name in dev scaffold

### LINKED ISSUE #707: Enh: Name of webpack config should default to `webpack.config.js`
**What is the current behavior?**
I noticed that in the default setup, that a "webpack.dev.js" file was created. By default webpack looks for webpack.config.js at the root of a project. For the sake of cleanliness and easy to write scripts, we should be outputting webpack.config.js as the default. For dev and prod versions (I'll put in a separate issue for this).

**Please paste the results of `webpack-cli info` here, and mention other relevant information**
Versions

```
"dependencies": {
    "webpack-cli": "^3.1.2"
  },
"devDependencies": {
    "@webpack-cli/init": "^0.1.2",
}
```

### PR DESCRIPTION
**Pull request by evenstensberg**
**What kind of change does this PR introduce?**

Fixes #707 
**Did you add tests for your changes?**
Ya
**If relevant, did you update the documentation?**
N/A
**Summary**
Changes default name of config in scaffolding

**Does this PR introduce a breaking change?**
N/a

**Other information**

### CODE REVIEW

**Comment by anshumanv** [comment]
Can I send a quick PR to rename the prod config to `webpack.production.js` as explained in the issue or is there a different approach? @evenstensberg

**Comment by evenstensberg** [comment]
let's go for prod and dev

**Comment by anshumanv** [comment]
The issue outlines to go for `production` and `development` do we drop that?

**Comment by evenstensberg** [comment]
I don’t think it did. @TheLarkInn is that true or not?

**Pull request merged**
