### PR TITLE
feat: create-webpack-app

### PR DESCRIPTION
**Pull request by rishabh3112**
**What kind of change does this PR introduce?**

**Did you add tests for your changes?**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

### CODE REVIEW

**Review by alexander-akait — COMMENTED** [review]
Can we add smoke test? Yes, it will be failed here, but I am do first release after this and we will look at tests

**Comment by rishabh3112** [comment]
Yup sure, will do

**Review by evenstensberg — COMMENTED** [review]
I don't see the point of naming an internal command/tool that is invoked through webpack-cli to something that indicates being a standalone tool..

**Comment by alexander-akait** [comment]
@evenstensberg Earlier I described the problem, shorty - when you use `npx webpack init`, it is not work (try to use it), because webpack-cli is not a part of webpack and `npm` doesn't install it (so you got not found package error), so we need to use other name, to provide better DX

**Comment by rishabh3112** [comment]
@alexander-akait should we wait for #2862 to get merged here?
Reason: It would be a difficult merge else as it has refactors in handler logic as well.

**Comment by alexander-akait** [comment]
Reviewed :+1:

**Comment by rishabh3112** [comment]
> Reviewed 👍

Thanks!

**Comment by rishabh3112** [comment]
As #2862 is merged, I will continue working on this now!

**Comment by rishabh3112** [comment]
TODO: Move new templates into create webpack app repo.

**Review by evenstensberg — COMMENTED** [review]
@rishabh3112 could you pick up the work on this again?

**Comment by rishabh3112** [comment]
@evenstensberg there roadmap for the same currently? If not lets finalize that first. This PR is anyway very old now.

**Review by evenstensberg — COMMENTED** [review]
gsoc project is doing this, closing

**Pull request closed without merging**
