### PR TITLE
test: enable skipped help tests

### PR DESCRIPTION
**Pull request by anshumanv**
**What kind of change does this PR introduce?**
test

**Did you add tests for your changes?**
yes

**If relevant, did you update the documentation?**
NA

**Summary**
enables skipped helps tests which were flaky on CI

**Does this PR introduce a breaking change?**
no

**Other information**

### CODE REVIEW

**Review by alexander-akait — COMMENTED** [review]
Still broken?

**Comment by anshumanv** [comment]
> Still broken?

stdout is clipped for some reason when using verbose so snapshot doesn't seem to contain all flags, this is also the case with generate docs script, not all flags are generated.

/cc @snitin315 any idea?

**Comment by alexander-akait** [comment]
I think here problem in sync execa, https://github.com/nodejs/node/issues/19218

**Comment by alexander-akait** [comment]
Somebody have macos? Need manually test

**Comment by anshumanv** [comment]
> Somebody have macos? Need manually test

yes, lets try async

**Comment by snitin315** [comment]
> > Still broken?
> 
> stdout is clipped for some reason when using verbose so snapshot doesn't seem to contain all flags, this is also the case with generate docs script, not all flags are generated.
> 
> /cc @snitin315 any idea?

Yes, some issue with macOS.

**Comment by alexander-akait** [comment]
@snitin315 So you have this problem locally, right?

**Comment by snitin315** [comment]
Yes on macOS works fine with Linux.

**Comment by anshumanv** [comment]
@alexander-akait skipped on macOS for now, async doesn't help 😞

**Comment by alexander-akait** [comment]
Can you try to remove `process.exit` for help output?

**Comment by anshumanv** [comment]
wow @alexander-akait thanks for help ⭐ 

Seems like CLA is stuck

**Comment by alexander-akait** [comment]
Let's ignore

**Pull request merged**
