### PR TITLE
bugfix: make startup message user friendly

### LINKED ISSUE #206: Feature: More user friendly startup message
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
`Insecure about some of the questions?` are vaguely written, and it would be better to have a more neutral / empathic message on startup.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
A better introduction to the `init-generator`
**If this is a feature request, what is motivation or use case for changing the behavior?**
User Experience 

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**

### PR DESCRIPTION
**Pull request by sumit-gupta91**
**What kind of change does this PR introduce?**
fixes #206 

**Did you add tests for your changes?**

**If relevant, did you update the documentation?**

**Summary**
display help option on startup
add log symbols for log level

**Does this PR introduce a breaking change?**

**Other information**

### CODE REVIEW

**Comment by ev1stensberg** [comment]
After all this is done, do `npm run prepare` before commiting, so that we get the `dist` folder updated as well!

**Comment by ev1stensberg** [comment]
Hi @sumit-gupta91 ! Do you need help on this?

**Comment by sumit-gupta91** [comment]
Hi @ev1stensberg, no help needed, was busy doing some errands just updating the PR

**Comment by sumit-gupta91** [comment]
Hi @ev1stensberg, in package.json there is no prepare script, so I am not able to update dist folder. I would require some input on better understanding of lib and dist folder. I read this article [https://medium.com/@_kamlesh_/anatomy-of-js-module-systems-and-building-libraries-fadcd8dbd0e](url).

**Comment by ev1stensberg** [comment]
Okay @sumit-gupta91 no worries! Here's what I propose:
0. Create a new branch, if you've got github desktop, sync v2 branch against your fork, if not, then this one is good: https://help.github.com/articles/syncing-a-fork/ ( remember you need to sync against the `v2` branch.
1. Open this in a new PR.
2. Go to `lib/generators/init-generator`
3. Paste the things you've done
4. Then install the dep you've added ( we're using yarn ) 

If you're having trouble getting this to work, send me a message at twitter! (https://twitter.com/ev1stensberg )

**Pull request closed without merging**
