### PR TITLE
tests(webpack-cli): add test for entry flag

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**

tests.

**Did you add tests for your changes?**

Yes.

**If relevant, did you update the documentation?**

NA
**Summary**
Added tests for `--entry` flag

**Does this PR introduce a breaking change?**
NO

**Other information**

### CODE REVIEW

**Comment by evilebottnawi** [comment]
CI is red

**Comment by snitin315** [comment]
> CI is red

Looking into it.

**Comment by snitin315** [comment]
CI is Green now.

**Comment by rishabh3112** [comment]
Good work!

**Pull request merged**
