### PR TITLE
ci: add Node.js v21

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**
CI

**Did you add tests for your changes?**
No
**If relevant, did you update the documentation?**
No
**Summary**
add Node.js v21

**Does this PR introduce a breaking change?**
No

**Other information**
No

### CODE REVIEW

**Comment by alexander-akait** [comment]
We should improve our test and don't use `punycode` module anymore :smile:

**Comment by snitin315** [comment]
We are not using it directly, I think it's coming from some dependency, I'll check.

**Comment by alexander-akait** [comment]
@snitin315 I think we need prepare the next major release here

**Comment by alexander-akait** [comment]
@snitin315 Drop old Node.js version (i.e. 18.12.0 minimum), bump all deps and drop support webpack-dev-server@3 support

**Comment by alexander-akait** [comment]
You can start the `next` branch, also we have one/two easy TODOs in our code

**Comment by snitin315** [comment]
I'll prepare for major release.

**Comment by alexander-akait** [comment]
Magic with Node.js@21

**Pull request merged**
