### PR TITLE
chore: update typescript and fix build

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**
fix

**Did you add tests for your changes?**
No
**If relevant, did you update the documentation?**
No
**Summary**

Fix https://github.com/webpack/webpack-cli/pull/3262

Update typescript to v4.7.2

**Does this PR introduce a breaking change?**

No

**Other information**
No

### CODE REVIEW

**Review by alexander-akait — DISMISSED** [review]

**Comment by alexander-akait** [comment]
Let's fix tests too, I think it is due update

**Comment by snitin315** [comment]
Something is wrong, [CI is failing here](https://github.com/webpack/webpack-cli/runs/6602551747?check_suite_focus=true#step:9:281). 

We may need to update ts-node (https://github.com/facebook/jest/issues/12655#issuecomment-1094070691) but it dropped node v10 support.

**Comment by alexander-akait** [comment]
@snitin315 Yep, can we do it here?

**Comment by snitin315** [comment]
I think yes. We have `node >= 10.13.0` in package.json but we don't seem to have any workflow on CI for node v10

**Review by rishabh3112 — APPROVED** [review]

**Pull request merged**
