### PR TITLE
Add `funding` key to package.json

### PR DESCRIPTION
**Pull request by mondeja**

### CODE REVIEW

**Comment by mondeja** [comment]
@linux-foundation-easycla I've signed the CLA.

**Review by evenstensberg — COMMENTED** [review]
Looks good. Could you sign the CLA?

**Comment by mondeja** [comment]
I've signed it:

**Comment by alexander-akait** [comment]
Sorry we don't need this in `root` package.json, because it is internal and no one downloade it

**Comment by mondeja** [comment]
Ok, would you accept a PR to add it to all packages?

**Comment by alexander-akait** [comment]
Yeah, but I think we already have it, but you can check and send a PR if you found packages without it

**Pull request closed without merging**
