### PR TITLE
fix: do not run CI on docs changes

### PR DESCRIPTION
**Pull request by anshumanv**
**What kind of change does this PR introduce?**
fix

**Did you add tests for your changes?**
no

**If relevant, did you update the documentation?**
no

**Summary**
Running CI for docs changes is useless and takes up CI time unnecessarily

**Does this PR introduce a breaking change?**
no

**Other information**
/cc evilebot @alexander-akait

### CODE REVIEW

**Comment by snitin315** [comment]
I think we should still check for `lint`

**Comment by anshumanv** [comment]
Lint doesn't validate markdown here so nope

**Comment by alexander-akait** [comment]
I agree, I think we need remark-lint here

**Comment by alexander-akait** [comment]
Let's close, no need, we should focus on reduce tests time

**Pull request closed without merging**
