### PR TITLE
fix: 🐛 defaults flag behaviour

### PR DESCRIPTION
**Pull request by anshumanv**
✅ Closes: #1322

**What kind of change does this PR introduce?**
Fix the application of default flags

**Did you add tests for your changes?**
Yes, enabled

**If relevant, did you update the documentation?**
Not needed

**Summary**
- Fix the bug in the approach we use webpack-merge to apply default config.

**Does this PR introduce a breaking change?**
No.

**Other information**

### CODE REVIEW

**Comment by snitin315** [comment]
@anshumanv can you resolve conflicts?

**Comment by anshumanv** [comment]
Do we wish to support this @webpack/cli-team?

**Comment by evilebottnawi** [comment]
@anshumanv we need investigate what does this option do, most likely we will remove it

**Comment by anshumanv** [comment]
@evilebottnawi when passed, default config is merged with the supplied config by the user https://github.com/webpack/webpack-cli/blob/dfb9a9142706751617eb38dc9f3e00f8e c750ec9/packages/webpack-cli/lib/utils/development-config.js or https://github.com/webpack/webpack-cli/blob/dfb9a9142706751617eb38dc9f3e00f8ec750ec9/packages/webpack-cli/lib/utils/production-config.js

Not sure of the use case

**Comment by anshumanv** [comment]
Should we remove it then?

**Comment by evilebottnawi** [comment]
Yes, no need, let's remove, webpack already have good default values

**Comment by anshumanv** [comment]
Okay, closing and removing in next PR. 👍

**Pull request closed without merging**
