### PR TITLE
feat: install init as global dep

### PR DESCRIPTION
**Pull request by manu-chroma**
Closes https://github.com/webpack/webpack-cli/issues/564

I am a little confused on how to test this change. Like how to reference my local ``webpack-cli`` installation in some other test folder where I can invoke the ``init`` command

### CODE REVIEW

**Comment by manu-chroma** [comment]
Thanks @ev1stensberg 🥂 

Which file should I search for the dep lookup?

**Comment by ev1stensberg** [comment]
Its the require resolve in this file, but invoking a addon might also be tested, that logic is under the init pacakge. I advice you to experiment a bit yourself, add some test commands like npm link to ensure that it works

**Comment by evenstensberg** [comment]
Thanks for fixing this @manu-chroma 💙

**Comment by manu-chroma** [comment]
Hey, thanks for finishing this up. Apologies for not completing this one myself, I'll make sure that I do, in the future! 😃

**Pull request merged**
