### PR TITLE
chore(deps): pin dependencies

### LINKED ISSUE #697: Lock versions of the dependencies
Due to the recent problems happened to the npm world, I'd propose to lock all the versions of our dependencies and development dependencies 

It's not a bulletproof solution must at least it's something

Before: 
```json
"chalk": "^2.4.1" 
```
After:
```json
"chalk": "2.4.1"
```

### PR DESCRIPTION
**Pull request by dhruvdutt**
**What kind of change does this PR introduce?**
Dependencies pinning

**Did you add tests for your changes?**
N/A

**If relevant, did you update the documentation?**
N/A

**Summary**

**Does this PR introduce a breaking change?**
No

**Other information**
Fixes #697

### CODE REVIEW

**Comment by ematipico** [comment]
There's a failing test... Does that mean that pinning the dependencies caused a different behaviour of the library? That's odd. We should fix it

**Comment by evenstensberg** [comment]
It's from uglify/terser test, which PR changed that again? Was recently done

**Comment by ematipico** [comment]
There's an open PR but it's still open

**Comment by evenstensberg** [comment]
If it doesnt fail at that then merging that would be nice

**Comment by evenstensberg** [comment]
Let’s do this properly Dhruvdut...

**Pull request merged**
