### PR TITLE
ci: use `yarn --frozen-lockfile` to install dependencies

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**
CI.

**Did you add tests for your changes?**
No
**If relevant, did you update the documentation?**

**Summary**

use `yarn --frozen-lockfile` to avoid writing `yarn.lock` on CI, just like `npm ci`

**Does this PR introduce a breaking change?**
None

**Other information**
No

### CODE REVIEW

**Comment by alexander-akait** [comment]
hm weird, I think yarn by default do it...

**Comment by snitin315** [comment]
There is related discussion on https://github.com/yarnpkg/yarn/issues/4147

**Comment by snitin315** [comment]
`webpack` repo also use `--frozen-lockfile`.

https://github.com/webpack/webpack/blob/64f2bdb7a99c94e61ff142afbc353cb9ea1a2f7d/.github/workflows/test.yml#L42

**Comment by alexander-akait** [comment]
@snitin315 I might accidentally forget something to merge, just ping me

**Pull request merged**
