### PR TITLE
Refactor arg parser

### PR DESCRIPTION
**Pull request by alexander-akait**
**What kind of change does this PR introduce?**

refactoring

**Did you add tests for your changes?**

Yes

**If relevant, did you update the documentation?**

No need

**Summary**

Full refactor

**Does this PR introduce a breaking change?**

No

**Other information**

WIP on each command

### CODE REVIEW

**Review by anshumanv — APPROVED** [review]
LGTM, we can merge on green CI 💯

**Comment by alexander-akait** [comment]
Remain to finish:
- refactor `help`/`--help`/`-h`
- auto install sub command + auto install webpack-dev-server for `webpack serve`
- show possible `--argument` for all commands, only `webpack`

**Comment by anshumanv** [comment]
> auto install sub command + auto install webpack-dev-server for webpack serve

You mean something like `yarn add -D webpack-dev-server` on first invocation of serve command?

**Comment by alexander-akait** [comment]
Yep

**Comment by alexander-akait** [comment]
auto installation solved + improve perf

**Comment by alexander-akait** [comment]
Solved: show possible arguments for all commands, not only for `webpack`

Tomorrow I will fix `help` and we can merge

**Comment by alexander-akait** [comment]
Solved - refactor `help`/`--help`/`-h`

With the limitation - now we use `commader` help output.

Props:
- less deps
- simple logic
- respect all terminals
- no problems with width

Cons:
- less colors
- less text for flags
- no help for `webpack --mode --help`, it is invalid and no one tool support it, if we need return this behaviour we need implement new command for this, for example `webpack help-option <option-name>`


Need: 
- fix some tests
- TODOs after refactor
- few edge cases

**Comment by alexander-akait** [comment]
I think I will fix tests tomorrow and merge it, after this - I will refactor other PRs and do release

**Comment by alexander-akait** [comment]
Sorry for delay, will finish it tomorrow

**Comment by alexander-akait** [comment]
Sorry for delay, finished, wait CI green

**Comment by alexander-akait** [comment]
Again problems with color, can't understand why, need investigate

**Comment by alexander-akait** [comment]
Our tests utils is trash - no good watch tests, no buffer options, using execa and buggy spawn sync instead execa, whole day of fixing this

**Comment by alexander-akait** [comment]
Coverage was decreased due problems with tests, I will fix it after merge it + union packages + refactor tests utils (migrate on execa)

**Comment by alexander-akait** [comment]
Hope nothing was broken

**Pull request merged**
