### PR TITLE
fix: defer setting default entry to core

### PR DESCRIPTION
**Pull request by anshumanv**
**What kind of change does this PR introduce?**
We're setting own default entry while core does this already so remove that logic.

**Did you add tests for your changes?**
Yes

**If relevant, did you update the documentation?**
LMK if there are places which need updates

**Summary**
- Do not set own default entry
- Update tests

**Does this PR introduce a breaking change?**
No

**Other information**
Fixes https://github.com/webpack/webpack-cli/issues/1852

### CODE REVIEW

**Review by evilebottnawi — DISMISSED** [review]
Big thanks!

/cc @webpack/cli-team

**Review by snitin315 — DISMISSED** [review]

**Comment by evilebottnawi** [comment]
@anshumanv CI failed :disappointed:

**Comment by anshumanv** [comment]
Ah minor issue, fixed 👍

**Comment by evilebottnawi** [comment]
Feel free to merge after CI will be green :star:

**Review by evilebottnawi — APPROVED** [review]
Feel free to merge after CI will be green

**Review by rishabh3112 — APPROVED** [review]

**Review by gairTanm — COMMENTED** [review]
Don't really understand all of it, but the default entry issue seems fixed :+1:

**Pull request merged**
