### PR TITLE
feat: show '--node-env' in minimum help output

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**
feature

**Did you add tests for your changes?**
already present.

**If relevant, did you update the documentation?**
Yes
**Summary**
Show `--node-env` in minimum help output as it is custom flag provided by CLI. `--help=verbose` lists too many options not easy to find `--node-env` between them.

Screenshot at 2021-02-04 16-49-34

**Does this PR introduce a breaking change?**
No

**Other information**
No

### CODE REVIEW

**Review by alexander-akait — DISMISSED** [review]

**Comment by alexander-akait** [comment]
@snitin315 Can you rebase?

**Review by alexander-akait — APPROVED** [review]

**Review by anshumanv — COMMENTED** [review]
we can assert on it in help output test

**Comment by alexander-akait** [comment]
I think we need to use snapshots for `help` and `output`, it will allow us to see all the changes.

**Comment by anshumanv** [comment]
yep snapshot is better

**Pull request merged**
