### PR TITLE
chore: remove duplicate build script

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**
chore

**Did you add tests for your changes?**
No
**If relevant, did you update the documentation?**
No
**Summary**

 remove duplicate build script

**Does this PR introduce a breaking change?**
No

**Other information**
No

### CODE REVIEW

**Comment by alexander-akait** [comment]
Something wrong with coverage :confused: But not related to this PR

**Comment by snitin315** [comment]
Hmm, need to look into it.

**Comment by alexander-akait** [comment]
I think we run it twice, so coverage was wrong

**Comment by alexander-akait** [comment]
Let's merge

**Comment by rishabh3112** [comment]
This PR should not have been merged.

> Something wrong with coverage confused But not related to this PR
Yup, we are not creating sourcemaps after this PR, which is required for testing ts files.

**Pull request merged**
