### PR TITLE
chore: remove output dir after test completion

### PR DESCRIPTION
**Pull request by anshumanv**
**What kind of change does this PR introduce?**

chore

**Did you add tests for your changes?**
Yes

**If relevant, did you update the documentation?**
NA

**Summary**

rm generated output dir in test

**Does this PR introduce a breaking change?**
No

**Other information**

### CODE REVIEW

**Comment by anshumanv** [comment]
Still exist locally and in CI

**Comment by jamesgeorge007** [comment]
> Still exist locally and in CI

This is the case with couple of other test suites as well, might be a good idea to update them as part of this PR.

**Comment by anshumanv** [comment]
If we decide to move forward with this, then yes

/cc @evilebottnawi

**Comment by evilebottnawi** [comment]
@anshumanv we still have problems with some tests?

**Comment by anshumanv** [comment]
> @anshumanv we still have problems with some tests?


They randomly fail but this is unrelated, this will cleanup stale test data

**Comment by evilebottnawi** [comment]
@anshumanv feel free to merge

**Comment by anshumanv** [comment]
I'll add in remaining tests, then 👍

**Comment by anshumanv** [comment]
Actually this strategy is poor and bad design, doesn't scale as well. Will come up with a better approach.

**Comment by anshumanv** [comment]
Opened #1667 with a better approach

**Pull request closed without merging**
