### PR TITLE
tests: cache

### PR DESCRIPTION
**Pull request by alexander-akait**
**What kind of change does this PR introduce?**

tests

**Did you add tests for your changes?**

Yes

**If relevant, did you update the documentation?**

No need

**Summary**

Complex cache test

**Does this PR introduce a breaking change?**

No

**Other information**

No

### CODE REVIEW

**Review by anshumanv — DISMISSED** [review]
💯

**Review by rishabh3112 — DISMISSED** [review]

**Comment by alexander-akait** [comment]
Can't understand what is the problem with macos :confused:

**Comment by alexander-akait** [comment]
Found a problem, I will fix it tomorrow

**Comment by alexander-akait** [comment]
Not sure whay coverage is decrase, because I added more tests, I think it is randomly, we will focus on coverage in future

**Pull request merged**
