### PR TITLE
Removing development version of node from travis configuration

### PR DESCRIPTION
**Pull request by ematipico**
**What kind of change does this PR introduce?**
Build related change

**Did you add tests for your changes?**
No

**If relevant, did you update the documentation?**
No

**Summary**
Removed version 7 of node as it is a development version

**Does this PR introduce a breaking change?**
No

### CODE REVIEW

**Comment by ematipico** [comment]
Random failure...

**Comment by ematipico** [comment]
Weird, at first a build failed. Well, that's good!

**Comment by ematipico** [comment]
Actually the scope of the PR was to remove version seven of node because it's s development version. Not an official one. The random failing build was about this specific PR.

**Comment by ev1stensberg** [comment]
Let's just keep it like this, one extra runner doesn't hurt

**Pull request closed without merging**
