### PR TITLE
chore(publishing): add semantic-release

### PR DESCRIPTION
**Pull request by ev1stensberg**
**What kind of change does this PR introduce?**

**Did you add tests for your changes?**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

### CODE REVIEW

**Comment by sendilkumarn** [comment]
Oops my bad, but I guess for adding semantic-release this is enough.

**Comment by ev1stensberg** [comment]
PTAL @webpack/cli-team

**Comment by ev1stensberg** [comment]
Let's squash this PR, rebasing would be redundant

**Comment by ematipico** [comment]
It's still failing

**Comment by ematipico** [comment]
image

**Pull request merged**
