### PR TITLE
chore: add pnpm as binary in info

### PR DESCRIPTION
**Pull request by rishabh3112**
**What kind of change does this PR introduce?**
chore / feat

**Did you add tests for your changes?**
WIP

**If relevant, did you update the documentation?**
N/A

**Summary**
Added pnpm as required binary. 
Although pnpm isn't supported in envinfo, still this PR has required use case.

**Does this PR introduce a breaking change?**
Nope

**Other information**

### CODE REVIEW

**Comment by rishabh3112** [comment]
# Tasks
- Created issue as `envinfo` for support. (https://github.com/tabrindle/envinfo/issues/216) (Waiting for reply)
- Create PR at `envinfo`
- Update PR after support is published
- Add tests
- Merge

**Review by evenstensberg — APPROVED** [review]
Lgtm meanwhile here, but not RTM (ready to merge)

**Comment by rishabh3112** [comment]
Made a friendly ping on the issue at `envinfo`. Lets see...

**Comment by rishabh3112** [comment]
The PR on `envinfo` has been inactive for a while, and main maintainer is inactive for over a long time given **last publish on npm was over a year ago**.

image

I guess we can patch it into a fork and deploy it, wdyt @alexander-akait? if yes I will do that.

**Comment by rishabh3112** [comment]
One last try I have pinged him on PR, lets see.

**Comment by rishabh3112** [comment]
Got a review there, would be working on that now.

**Pull request closed without merging**
