### PR TITLE
fix: updated getPackageManager logic

### PR DESCRIPTION
**Pull request by karanb1**
**issue closed: #941** 

**What kind of change does this PR introduce?**
Enhancement

**Did you add tests for your changes?**
No
**If relevant, did you update the documentation?**
Not relevant
**Summary**
This PR updates the getPackageManager logic.

**Does this PR introduce a breaking change?**

**Other information**

### CODE REVIEW

**Comment by snitin315** [comment]
You should create an issue first (for the maintainers and developers to review if valid)and then make a corresponding PR.

**Comment by karanb1** [comment]
@snitin315 should I close this PR and make a new one?

**Comment by snitin315** [comment]
Don't close it now , let's wait for others to review. In the meantime what you can do is create an issue for the same .

**Comment by jamesgeorge007** [comment]
Possible duplicate of #1162

**Comment by ematipico** [comment]
Currently this utility has been moved inside the package `@webpack-cli/package-utils`. I changed the logic there. 

Thank you for the work you've done here in the PR but I can't take this code because the code doesn't take into account projects with a fresh installation (no lock files)

**Comment by ematipico** [comment]
I am going to close this PR as it refers to an old code. Feel free to create a new one.

**Pull request closed without merging**
