### PR TITLE
docs: update cli options

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**
docs

**Did you add tests for your changes?**
No
**If relevant, did you update the documentation?**
yes
**Summary**
update docs

**Does this PR introduce a breaking change?**
No

**Other information**
No

### CODE REVIEW

**Review by alexander-akait — APPROVED** [review]
I think we need automate this

**Comment by snitin315** [comment]
I will see if we can automate it, we need to trigger it for webpack release/update

**Comment by alexander-akait** [comment]
Yep, thanks for help

**Review by rishabh3112 — APPROVED** [review]
Looks good.

**Review by anshumanv — APPROVED** [review]

**Pull request merged**
