### PR TITLE
chore: update contributing docs, add script

### LINKED ISSUE #619: DOCS: contributing setup: rimraf dep needed before running npm bootstrap
**Describe the bug**
**What is the current behavior?**

If the user does not have ``rimraf`` installed before running ``npm bootstrap``, 
``sh: 1: rimraf: not found`` error is thrown. 

This dependency should be specified in https://github.com/webpack/webpack-cli/blob/master/CONTRIBUTING.md.

### PR DESCRIPTION
**Pull request by dhruvdutt**
**What kind of change does this PR introduce?**
Docs and guide update

**Did you add tests for your changes?**
N/A

**If relevant, did you update the documentation?**
Yes

**Summary**
Simplifies setup process, add `postinstall` script to bootstrap packages.

**Does this PR introduce a breaking change?**
No

**Other information**
Closes #619

### CODE REVIEW

**Comment by manu-chroma** [comment]
Hey, I am just curious that if we run ``bootstrap`` as the ``postinstall`` script, 
won't ``bootstrap`` (using ``clean:all``) cleanup all the packages we just installed and re-install them again? 
I understand it will use the local cache 2nd time around but still why the redundancy?

**Comment by ev1stensberg** [comment]
To run bootstrap one needs to do that to prevent lerna from making a corrupt installation from what I understood

**Comment by SimenB** [comment]
Tried to run install in this repo, and the fact that `postinstall` calls `bootstrap` which calls `install` which calls `postinstall` when done, means the installation is currently in an infinite loop.

**Comment by ev1stensberg** [comment]
Fixed now, sorry for the inconvenience

**Comment by dhruvdutt** [comment]
Sorry for the inconvenience, guys. Should have cleaned up the script.

Thank you very much @ev1stensberg for fixing it. 💙

**Comment by ev1stensberg** [comment]
I didnt fix it, a rm rf needs to be done I think, was a quick fix, but 2 lines with same code is redundant, should probably make a «clean» script and use that instead

**Pull request merged**
