### PR TITLE
docs(contributing): add example commit message

### LINKED ISSUE #1340: Example for commit-message template  in CONTRIBUTING.md
**Is your feature request related to a problem? Please describe.**
It took me time to find an example commit-message when I was making my first commit to this repo.

**Describe the solution you'd like**
An example commit-message in CONTRIBUTING.md would be nice under the 'commit message format' section

**Describe alternatives you've considered**
none.

**Additional context**
I intend to copy the one already present and being used in [webpack-dev-middle contributing file](https://github.com/webpack/webpack-dev-middleware/blob/master/.github/CONTRIBUTING.md#-webpack-contrib-commit-conventions)

### PR DESCRIPTION
**Pull request by Parikshit-Hooda**
**What kind of change does this PR introduce?**

docs(contributing): add commit message example to help contributors/developers

**Did you add tests for your changes?**
not required

**If relevant, did you update the documentation?**
not required

**Summary**

adding example for a commit message will save (possible)surfing to find an example of a commit message that the repo accepts

**Does this PR introduce a breaking change?**

no

**Other information**
resolves #1340

### CODE REVIEW

**Comment by Parikshit-Hooda** [comment]
@snitin315 is this right? Should I always push to 'next'? I believe I read somewhere that working branch is 'master' thatswhy I was trying to push there.

**Comment by snitin315** [comment]
> @snitin315 is this right? Should I always push to 'next'? I believe I read somewhere that the working branch is 'master' that why I was trying to push there.

by default `master` is the `default branch`,  but for the `beta version` of CLI, we are using `next` branch.

**Comment by snitin315** [comment]
Also, Fix CI.

**Comment by anshumanv** [comment]
Example is fine but we suggest committing using the commit script which does the commit as per your answers to the prompt, so not really sure if this will aid new developers since they need not worry about the format and just need to follow the prompt, but good to have!

**Comment by Parikshit-Hooda** [comment]
@anshumanv i just attempted a force-push using the 'npm run commit' to fix commitlint issue. Not an ideal practice. Also, I suggest highlighting the practice of using the script in contributing.md file. I went through it and somehow missed this practice. what do you think?

**Comment by snitin315** [comment]
Its already highlighted I guess. `yarn commit`

**Comment by Parikshit-Hooda** [comment]
> Its already highlighted I guess. `yarn commit`

I meant putting it as a note, etc. I clearly missed it.

**Comment by snitin315** [comment]
Maybe you weren't careful enough while reading COUNTRIBUTING.md that's why missed it.

It's pretty clear to see 😅

**Comment by Parikshit-Hooda** [comment]
apparently. i guess i don't want others to miss it too and go make poor commits.

**Comment by anshumanv** [comment]
> apparently. i guess i don't want others to miss it too and go make poor commits.

Not needed, DRY principle.

**Comment by anshumanv** [comment]
Conflicts, also not sure if we need an example, the format is pretty well laid out with references. Should suffice. Will wait for others' opinion.

**Review by evenstensberg — APPROVED** [review]

**Review by evilebottnawi — APPROVED** [review]

**Pull request closed without merging**
