### PR TITLE
chore: add node v17 to CI

### PR DESCRIPTION
**Pull request by rishabh3112**
**What kind of change does this PR introduce?**
adds v17 to CI

**Did you add tests for your changes?**
N/A

**If relevant, did you update the documentation?**
N/A

**Summary**
Add node v17 to CI

**Does this PR introduce a breaking change?**
Nope

**Other information**
N/A

### CODE REVIEW

**Comment by alexander-akait** [comment]
Still broken :disappointed:

**Comment by rishabh3112** [comment]
> Still broken 😞

Reason as I already said above: https://github.com/webpack/webpack-cli/pull/3014#issuecomment-949509545

**Comment by alexander-akait** [comment]
@rishabh3112 webpack already has patches, try to regenerate lock file

**Comment by nschonni** [comment]
Added in https://github.com/webpack/webpack-cli/pull/3056

**Pull request closed without merging**
