### PR TITLE
chore: add script to run `webpack-cli` locally

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**
chore

**Did you add tests for your changes?**
NO
**If relevant, did you update the documentation?**
No
**Summary**

Add script to run cli locally with `yarn run webpack-cli` or `npm run webpack-cli`.

**Does this PR introduce a breaking change?**
No

**Other information**
None

### CODE REVIEW

**Review by anshumanv — COMMENTED** [review]
What are the use cases? We can already run from local by linking

**Comment by alexander-akait** [comment]
Yep, you can run `webpack` inside repo (in root) and yarn run local version

**Comment by anshumanv** [comment]
hmm that already work for me by linking
image

**Comment by alexander-akait** [comment]
You don't need to link, because `lerna bootstrap` do it :smile:

**Comment by snitin315** [comment]
For some unknown reason it wasn't working. All good now 👍

**Comment by anshumanv** [comment]
Great, closing

**Comment by alexander-akait** [comment]
@snitin315 try to run `yarn lerna boostrap` and `webpack --help`

**Comment by snitin315** [comment]
> @snitin315 try to run `yarn lerna boostrap` and `webpack --help`

Perfect, Thanks!

**Pull request closed without merging**
