### PR TITLE
tests(plugin & loader): refactor tests

### PR DESCRIPTION
**Pull request by evenstensberg**
**What kind of change does this PR introduce?**

Disables tests for migrate, plugin and loader (scaffolding)

**Did you add tests for your changes?**
Yea

**If relevant, did you update the documentation?**
No
**Summary**

Since yarn will be fighting against the test cases to finish installing lockfiles for each testcase, I've disabled these.

**Does this PR introduce a breaking change?**
No

**Other information**
N/A

### CODE REVIEW

**Comment by evenstensberg** [comment]
Cc @snitin315

**Comment by evilebottnawi** [comment]
Previously we disable almost tests, I'm not going to let the situation repeat again, we had to spend a lot of time to restore this

**Comment by snitin315** [comment]
I will look into this.

**Review by evilebottnawi — APPROVED** [review]
/cc @webpack/cli-team

**Review by rishabh3112 — APPROVED** [review]

**Pull request merged**
