### PR TITLE
fix: show `--analyze` in minimum help output

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**
fix

**Did you add tests for your changes?**
yes
**If relevant, did you update the documentation?**
yes
**Summary**
show `--analyze` in minimum help output

**Does this PR introduce a breaking change?**
No

**Other information**
No

### CODE REVIEW

**Review by rishabh3112 — APPROVED** [review]

**Review by alexander-akait — COMMENTED** [review]
Do you think we need this in our basic help?

**Comment by snitin315** [comment]
@alexander-akait  yes, We should show it as `analyze` is a custom option provided via `CLI` like `env`, `json` etc.

**Comment by alexander-akait** [comment]
Let's do it for next, to avoid extra rebasing, don't think it is very high priority for current version

**Comment by snitin315** [comment]
Yes we can do it for next 👍🏻

**Comment by snitin315** [comment]
Fixed in `next`

**Pull request closed without merging**
