### PR TITLE
tests: check for proper exit code

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**
tests

**Did you add tests for your changes?**
yes
**If relevant, did you update the documentation?**
no
**Summary**

Check for proper exit codes.

**Does this PR introduce a breaking change?**
No

**Other information**
No

### CODE REVIEW

**Review by evilebottnawi — APPROVED** [review]
Good job, we should always check exit code

**Review by anshumanv — APPROVED** [review]
🌟

**Pull request merged**
