### PR TITLE
docs: fix typo in --defaults description

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**

typo fix

**Did you add tests for your changes?**
NA
**If relevant, did you update the documentation?**
YES
**Summary**
~~aggresively~~  aggressively 

**Does this PR introduce a breaking change?**
NO

**Other information**
NA

### CODE REVIEW

**Comment by snitin315** [comment]
I think we should add a snapshot test for `--help`. What do you say?

**Comment by jamesgeorge007** [comment]
> I think we should add a snapshot test for `--help`. What do you say?

I think what we have now  for `help` would suffice.

**Comment by anshumanv** [comment]
We'll be removing this flag as per discussion in https://github.com/webpack/webpack-cli/pull/1323
Closing

**Comment by snitin315** [comment]
> We'll be removing this flag as per discussion in #1323
> Closing

I'm happy to send a PR for that as well, if you agree.

**Comment by anshumanv** [comment]
WIP

**Pull request closed without merging**
