### PR TITLE
Feature: Add AST transforms to generator

### PR DESCRIPTION
**Pull request by pksjce**
This PR provides a way to provide transformations to each of the proposed generators.

For eg - the default generator is the `init-generator`. Each generator consists of two files. 
1. Generator specific file `<generator-name>-generator.js`
2. Transforms specific file. `<generator-name>-transforms.js`

Pending tasks

- [ ] - Write test cases

### CODE REVIEW

**Comment by ev1stensberg** [comment]
Thanks for picking up the stick @pksjce, I'll rebase this shortly against the current branch. Are you available to work on the cli this week?

**Comment by pksjce** [comment]
Yep. I seem to have figured out how your approach works. So managed to hack together transforms. This gives a basic structure as to how we could integrate transformations together. 
I rebased this with the new refactor PR you opened up. 
Could you test this  branch out? It console logs the generated config.

**Comment by ev1stensberg** [comment]
@pksjce Could you update your branch against master?

**Comment by ev1stensberg** [comment]
Closing, let's continue this on my new WIP branch :)

**Pull request closed without merging**
