### PR TITLE
chore: increase jest timeout

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**
increase timeout

**Did you add tests for your changes?**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

### CODE REVIEW

**Comment by snitin315** [comment]
All checks passed i will trigger CI once again to check stability.

**Comment by rishabh3112** [comment]
@snitin315 you can re-trigger CI from `actions` tab itself now :)

**Comment by snitin315** [comment]
@rishabh3112 passing again. I will re-trigger one last time.

**Comment by snitin315** [comment]
All green :smile:

**Pull request merged**
