### PR TITLE
Refactor general logic for readability

### PR DESCRIPTION
**Pull request by kingdaro**

### CODE REVIEW

**Comment by ev1stensberg** [comment]
Oh wait, could you take this to the `feature/add` branch?

**Comment by ev1stensberg** [comment]
Don't worry about the `add`, `remove` and `update` generators, would need a fix later when everything is added anyways!

**Comment by kingdaro** [comment]
Sure thing, just a second.

**Comment by ev1stensberg** [comment]
Cherry picked your commit on init generator, just do the rest, sorry for the mess

**Comment by ev1stensberg** [comment]
Make sure to resync against the `v2` branch

**Comment by kingdaro** [comment]
I was going to make a new PR, is this correct?

**Comment by ev1stensberg** [comment]
Yupp

**Pull request merged**
