### PR TITLE
chore(package-lock): sync

### PR DESCRIPTION
**Pull request by dhruvdutt**
**Summary**

Sync `package-lock.json` nested deps minor upgrades

### CODE REVIEW

**Comment by dhruvdutt** [comment]
So that we can use yarn locally and git won't mess with `yarn.lock`

**Comment by ev1stensberg** [comment]
Webpack-cli uses npm, no yarn involved.

**Comment by dhruvdutt** [comment]
Hmmm, I was using yarn to install deps.
I just cleaned `yarn.lock` and `node_modules` and ran `npm i` which did some minor updates in `package-lock.json`.

**Comment by ev1stensberg** [comment]
Not really needed, thanks for the PR tho! Can I suggest some issues that you can work with?

**Comment by dhruvdutt** [comment]
@ev1stensberg sure, you can suggest me issues.

Also, can you please list the bugs with `add` command? Is it something that I can try?

**Comment by ev1stensberg** [comment]
Look at the general improvements issues, like I mentioned before on Twitter

**Pull request closed without merging**
