### PR TITLE
Better output

### PR DESCRIPTION
**Pull request by ematipico**
**What kind of change does this PR introduce?**
Work in progress of  #717

This PR introduces the following changes:
- `compiler.js` => `Compiler.js` as class. I holds all the same methods as before. It also holds a class `CompilerOutput.js` which is responsible to generate the wanted output
- `CompilerOutput.js`: this class is responsible to output based on certain options. At the moment I left the "fancy" compilation but I think this fancy way of showing the results should be "opt-in" by passing an argument. Or we should provide a way to switch back to the old output. I also prepared some other functions for emit the normal output and the JSON one.
- I fixed eslint around some files. We were using a plugin that was not needed for the JS files.

**Did you add tests for your changes?**
Not yet, will do

**If relevant, did you update the documentation?**
No, I am awaiting feedback

**Summary**
The output must contain at least all the information emitted by the method `stats.getOutput`. 
Hopefully I managed to put all of them but I need to try it with some other project.

**Does this PR introduce a breaking change?**

Nope

**Other information**
Screenshot 2020-01-30 at 15 42 20

### CODE REVIEW

**Comment by ematipico** [comment]
@rishabh3112 I can remove the header's width so the table will be narrower:

Screenshot 2020-01-31 at 09 16 38

**Comment by ematipico** [comment]
Honestly, I'd want to propose an argument called `--output-pretty` which will emit this output. And  if we don't pass anything, we keep the standard webpack output. What do you think?

**Comment by rishabh3112** [comment]
> Honestly, I'd want to propose an argument called --output-pretty which will emit this output. And if we don't pass anything, we keep the standard webpack output. What do you think?

Yes, we should do this work this way.

I experimented with your work a little to make pretty output more compact.
image
image
WDYT?

**Comment by ematipico** [comment]
I love it!!

**Comment by rishabh3112** [comment]
@ematipico I added that change to your branch :)

**Comment by rishabh3112** [comment]
I thought and I think we can do other way around. Like add a `--verbose` flag for standard output and give this output by default.

**Comment by ematipico** [comment]
`--verbose` is not the standard output. The standard output is always stripped/limited to a certain number of lines (it doesn't contain all the modules). So we should get a default, standard and verbose. We are release a major version, so we could use this as default and we need also a way to opt-in the standard one using another argument that is not `--verbose`

**Comment by rishabh3112** [comment]
So what could be a possible flag name?
`--output-standard`?

**Comment by ematipico** [comment]
Sounds good!

**Comment by ematipico** [comment]
@rishabh3112 I'd say we can make a different PR to add that new flag

**Comment by rishabh3112** [comment]
Thanks and Cheers!

**Pull request merged**
