### PR TITLE
chore: update base branch info

### PR DESCRIPTION
**Pull request by jamesgeorge007**
**What kind of change does this PR introduce?**
refactoring

**Did you add tests for your changes?**
N/A

**If relevant, did you update the documentation?**
Yup

**Summary**
Update base branch information within contributing guidelines document.

**Does this PR introduce a breaking change?**
N/A

**Other information**
N/A

### CODE REVIEW

**Comment by jamesgeorge007** [comment]
Since we've made `next` as the default branch, I guess this makes sense :thinking:

**Comment by jamesgeorge007** [comment]
cc @evenstensberg @ematipico

**Comment by jamesgeorge007** [comment]
cc @evenstensberg

**Comment by ematipico** [comment]
This is just temporary as we want to start focusing on release a new version. We will switch back to master once we release a new major version.

**Pull request closed without merging**
