### PR TITLE
feat: next

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**

Breaking changes. Prepare for webpack-cli v5 🎉 

**Did you add tests for your changes?**
Yes.

**If relevant, did you update the documentation?**
Yes.

**Summary**

Prepare for the next major release.

**Does this PR introduce a breaking change?**
Yes.

**Other information**
 
   - [x] drop node v10, v12
   - [x] drop webpack v4
   - [x] drop webpack-dev-server v3
   - [x] remove `--prefetch`
   - [x] remove `--hot`
   - [x] remove `migrate` command
   - [x] update all deps to the latest
   - [x] --entry require --entry-reset before (need add test(s)) https://github.com/webpack/webpack-cli/pull/3372
   - [x] --target require --target-reset before (need add test(s)) https://github.com/webpack/webpack-cli/pull/3347
   - [x] refactor build tests - avoid using scripts/prepareSuite.js and put all deps in top package.json + rename tests https://github.com/webpack/webpack-cli/pull/3409
   - [x] node-env should be renamed?
   - [ ] simplify logic for `getBuiltInOptions` and remove extra map/reduce/etc and avoid using builtInOptionsCache
   - [ ] make stable CLI API for public usage
   - [ ] avoid unnecessary process.exit()
   - [ ] resolve TODOs wherever possible.
   - [x] remove the webpack version in favor of webpack info (https://github.com/webpack/webpack-cli/pull/3370)

### CODE REVIEW

**Review by evenstensberg — DISMISSED** [review]

**Review by alexander-akait — DISMISSED** [review]

**Comment by snitin315** [comment]
Let's keep it open untill all the breaking changes are merged to he next branch.

**Review by rishabh3112 — COMMENTED** [review]
Any status update on this?

**Comment by snitin315** [comment]
> Any status update on this?

@rishabh3112 I've added a the task list in the PR description.

**Comment by alexander-akait** [comment]
@snitin315 Some things can be postponed, like:
```
- simplify logic for getBuiltInOptions and remove extra map/reduce/etc and avoid using builtInOptionsCache
- avoid unnecessary process.exit()
- resolve TODOs wherever possible.
 ```
 
 We should look at code, if we will not have breaking change, we can postpone it and solve late, I think we should do release soon, because we need to drop nodev12 for webpack-dev-server too

**Comment by alexander-akait** [comment]
hm, give me time to undestand why do I even need this

**Comment by snitin315** [comment]
@alexander-akait This was requested from users in https://github.com/webpack/webpack-cli/issues/2362

**Comment by alexander-akait** [comment]
@snitin315 Oh, I wanted to rename `node-env`, because it is confising, many developers using `node-env` think that it will change `process.env.NODE_ENV` inside `webpack.config.js`, but it only change `process.env.NODE_ENV` in code, that is why I think we need another name for this. What do you think?

**Comment by snitin315** [comment]
@alexander-akait In that case it makes sense to update the name, we can also mention this explicitly in docs.

How about `--runtime-node-env`?

**Comment by snitin315** [comment]
> --define:process.env.NODE_ENV

How about `--define-process-node-env`/`--define-process-env-node-env`

**Comment by alexander-akait** [comment]
`--define-process-env-node-env` looks good for me, in future we can implement `--define-*` supporing for more options

**Comment by alexander-akait** [comment]
@snitin315 Regarding

> update all deps to the latest

What is left?

**Comment by snitin315** [comment]
> @snitin315 Regarding
> 
> > update all deps to the latest
> 
> What is left?

@alexander-akait Only updating commander.js to v9 is left.

**Comment by alexander-akait** [comment]
@snitin315 Great, feel free to ask help if you will have problems with it

**Comment by snitin315** [comment]
> [ ] make stable CLI API for public usage

@alexander-akait What do we want to change in the API?

**Comment by alexander-akait** [comment]
@snitin315 Can you show me where you take this task? I need context to remeber it :smile:

**Comment by snitin315** [comment]
@alexander-akait This was in old next https://github.com/webpack/webpack-cli/pull/2879

**Comment by alexander-akait** [comment]
@snitin315 Got it, I mean we should add tests cases where developer programatically run `WebppackCLI` and can run `build`/`serve`/etc commands without problems

**Comment by snitin315** [comment]
Maybe we can postpone it too then.

**Comment by alexander-akait** [comment]
@snitin315 Yeah, I think soo, anything else we need to finish before merge and release? Maybe ESM?

**Comment by snitin315** [comment]
Yes. Only ESM is left.

**Comment by alexander-akait** [comment]
Great, thank you

**Comment by snitin315** [comment]
@alexander-akait I feel we can merge this after CI is green. We should do `Rebase and Merge` to preserve commit history.

Screenshot 2022-11-08 at 8 41 24 AM

**Comment by alexander-akait** [comment]
@snitin315 Yeah, we should not lose changelog generation :+1:

**Comment by snitin315** [comment]
@alexander-akait We can release it now 👍🏻

**Comment by snitin315** [comment]
@alexander-akait I feel we can merge 👍🏻

**Pull request merged**
