### PR TITLE
feat(init): display available options as part of help information

### PR DESCRIPTION
**Pull request by jamesgeorge007**
**What kind of change does this PR introduce?**
Enhancement

**Did you add tests for your changes?**
Nope

**If relevant, did you update the documentation?**
N/A

**Summary**
Added `flags` entry for `init` subcommand.
Screenshot 2020-11-09 at 6 50 03 PM

**Does this PR introduce a breaking change?**
Nope

**Other information**
N/A

### CODE REVIEW

**Review by evilebottnawi — APPROVED** [review]

**Comment by evilebottnawi** [comment]
@jamesgeorge007 Ideally we should do it for all sub commands, feel free to send more PRs to fix it

**Comment by evilebottnawi** [comment]
@jamesgeorge007 I think we should add test for help for this command, to avoid problem with coverage

**Review by snitin315 — APPROVED** [review]

**Comment by jamesgeorge007** [comment]
Good to land?

**Comment by snitin315** [comment]
Yes LGTM.

**Pull request merged**
