### PR TITLE
tests(generators): plugins util tests

### PR DESCRIPTION
**Pull request by Loonride**
**What kind of change does this PR introduce?**

tests

**Did you add tests for your changes?**

Yes

**If relevant, did you update the documentation?**

No

**Summary**

generators plugins util tests

**Does this PR introduce a breaking change?**

No

**Other information**

### CODE REVIEW

**Comment by Loonride** [comment]
> Some tests seem to fail, can you check?

It seems like a bad test run, nothing in my changes is causing the problem as far as I can tell

**Comment by anshumanv** [comment]
> It seems like a bad test run, nothing in my changes is causing the problem as far as I can tell

Yes just saw, unrelated serve test is failing. Re-running should fix.

**Comment by Loonride** [comment]
Let me push another commit, I forgot to test one case anyway

**Comment by anshumanv** [comment]
Unusual, init-generator tests seem to be timing out now.

**Pull request merged**
