### PR TITLE
chore: fix typos across the project

### LINKED ISSUE #1305: bug: Typos present in the project
**Describe the bug**

There are very typos present in the project at the moment. few are as follows: -

Screenshot from 2020-03-09 22-04-32

**What is the current behavior?**

**Expected behavior**

Fix typos.

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

**Additional context**
Working on it.

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**

Fixes #1305 

**Did you add tests for your changes?**
NA
**If relevant, did you update the documentation?**
NA
**Summary**
Fixed all typos.

**Does this PR introduce a breaking change?**

NO
**Other information**
NA

### CODE REVIEW

**Comment by ematipico** [comment]
Please don't change the change logs. These are auto generated and from the commits

**Comment by ematipico** [comment]
@snitin315 Also the files under `docs` folder are auto generated, it doesn't help changing the typos manually

**Comment by snitin315** [comment]
@ematipico @rishabh3112 I used [misspell](https://github.com/client9/misspell) to find typos.

**Comment by snitin315** [comment]
> @snitin315 Also the files under `docs` folder are auto generated, it doesn't help changing the typos manually

Okay, I will leave the docs files unchanged.

**Comment by snitin315** [comment]
> It would be better to automate detecting these grammatical changes by integrating it into CI.

I did find something which can be integrated [https://typoci.com/](https://typoci.com/)

Screenshot from 2020-03-10 16-50-33

**Pull request merged**
