### PR TITLE
feat!: add `--define-process-env-node-env` option

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**
Feature + Refactor

**Did you add tests for your changes?**
Yes.

**If relevant, did you update the documentation?**
Yes.

**Summary**

Add new `--define-process-env-node-env` option

**Does this PR introduce a breaking change?**

BREAKING_CHANGE: `--node-env` option was removed in favor of the`--define-process-env-node-env` option

**Other information**
No

### CODE REVIEW

**Review by evenstensberg — APPROVED** [review]
lgtm

**Review by alexander-akait — APPROVED** [review]

**Comment by CreativeTechGuy** [comment]
Hey @snitin315, is there any thread explaining the logic behind this change? It seems really random and I cannot find an existing standard that this is conforming to. Thanks! 😃

**Comment by snitin315** [comment]
@CreativeTechGuy It was discussed here https://github.com/webpack/webpack-cli/pull/3279#issuecomment-1280763714

**Comment by CreativeTechGuy** [comment]
Appreciate it! But that comment you actually linked is incorrect. I even tested it with the latest release.

Running `webpack --define-process-env-node-env production` will set `process.env.NODE_ENV === "production"` in `webpack.config.js`

And I've been using that feature for a while now and I'm pretty sure even back to Webpack 4 it worked that way although I may me misremembering that far back.

So it is actually now even more confusing, since it definitely does the thing that it was renamed to avoid people thinking that it did. haha

**Comment by snitin315** [comment]
@CreativeTechGuy can you a test case to verify?

**Comment by CreativeTechGuy** [comment]
@snitin315, yup! I created a separate issue to discuss this further and it has a very easy repro. #3503

**Pull request merged**
