### PR TITLE
refactor: core

### PR DESCRIPTION
**Pull request by alexander-akait**
**What kind of change does this PR introduce?**

refactoring, resolve TODO

**Did you add tests for your changes?**

Will be added after fix entry bug in webpack

**If relevant, did you update the documentation?**

Yes, for webpack@5, you need to use `--entry-reset` or `--target-reset` before passing new entries or targets, i.e.

**webpack.config.js**

```js
module.exports = { 
  entry: './src/my-entry.js'
};
```

To override `entry`:
- when you use `webpack@5` you need to run `webpack --entry-reset --entry './src/other-entry.js'`
- when you use `webpack@4` you need to run `webpack --entry './src/other-entry.js'`

**Summary**

Avoid extra actions for webpack@5

**Does this PR introduce a breaking change?**

No

**Other information**

No

### CODE REVIEW

**Comment by alexander-akait** [comment]
Let's put this in the next release

**Comment by evenstensberg** [comment]
This might need a rebase

**Review by evenstensberg — COMMENTED** [review]
Maybe we should start off in a new branch?

**Comment by alexander-akait** [comment]
@evenstensberg I think we can close this

@snitin315 Am I right and we already move most of these changed into the `next` branch

**Comment by snitin315** [comment]
@alexander-akait yes. We can close this.

**Pull request closed without merging**
