### PR TITLE
Adding tasks for publishing results

### PR DESCRIPTION
**Pull request by vagisha-nidhi**
**What kind of change does this PR introduce?**

This PR is related to the issue #694 
The PR helps to publish test results for reporting in Azure Pipelines.

**Did you add tests for your changes?**
No

**If relevant, did you update the documentation?**

**Summary**

Azure Pipelines provides excellent reporting capabilities that can be leveraged by this PR.
An example report is shown in the image below.
image
A screenshot for code coverage : 
image

**Does this PR introduce a breaking change?**

No
**Other information**

### CODE REVIEW

**Comment by hemal7735** [comment]
LGTM 👍 
@vagisha-nidhi can you also provide some screenshot for coverage if possible?

**Comment by vagisha-nidhi** [comment]
@hemal7735 Sure. I have added the screenshot in the description. Can we requeue the travis CI integration?

**Comment by vagisha-nidhi** [comment]
@evenstensberg Can we requeue the travis CI? There seems no evident reason why this would fail.

**Comment by ematipico** [comment]
@vagisha-nidhi the commit message doesn't follow the pattern, that's why the CI is failing. https://github.com/webpack/webpack-cli/blob/master/CONTRIBUTING.md#commit-message-format-1

If you can rewrite your message, it would be great. If you can't, *it's not a problem*, we can rewrite the commit message when you we will merge your PR into master! :)

**Comment by evenstensberg** [comment]
Do you have a link of this working atm? Can't seem to find it

**Comment by ematipico** [comment]
https://dev.azure.com/webpack/webpack/_build/results?buildId=761&view=ms.vss-test-web.test-result-details

On master branch is there, "Tests" tab

**Comment by rishabh3112** [comment]
For each PR here
image

**Pull request merged**
