### PR TITLE
refactor: migrate help group

### PR DESCRIPTION
**Pull request by anshumanv**
**What kind of change does this PR introduce?**

refactor 

**Did you add tests for your changes?**
Yes

**If relevant, did you update the documentation?**
NA

**Summary**
Cleans up HelpGroup, cleanup fn args, remove instance from CLI

**Does this PR introduce a breaking change?**
No

**Other information**

### CODE REVIEW

**Comment by anshumanv** [comment]
yep fixing in a while (today fix)

**Comment by anshumanv** [comment]
should be fixed now 🤞

**Review by evilebottnawi — APPROVED** [review]
/cc @webpack/cli-team

**Review by rishabh3112 — APPROVED** [review]
Lets merge after green 🚀

**Review by jamesgeorge007 — APPROVED** [review]

**Review by snitin315 — APPROVED** [review]

**Pull request merged**
