### PR TITLE
fix: watch mode and options

### LINKED ISSUE #1923: [Watch mode issue] Webpack watch not working with webpack-cli@4
**Describe the bug**

When using watch mode as given in the following `webpack.config.js`:

```
module.exports = () => ({
    entry: path.resolve(__dirname, 'src/index.ts'),
    mode: NODE_ENV,
    watch: true,
    target: 'node',
...
// rest of config (uninportant I think)
...
}
```

with these dependencies for webpack:
```
    "webpack": "4.44.2",
    "webpack-cli": "4.0.0"
```

**Webpack will not run with watch mode on.**
**But with the following deps it will run as expected:**

```
    "webpack": "4.44.2",
    "webpack-cli": "3.3.12"
```

Also should mention that I am using:
```
yarn version - 1.22.4
node version - v14.13.0
```
**What is the current behavior?**

The compilation starts and finishes without any error, but it does not continue to watch for changes.
It acts as if watch is disabled.

**To Reproduce**

1. Clone my  [example repo](https://github.com/zatloeri/webpackWatchTestRepo)
2. run `yarn install`
3. run `yarn test`
    - Observer the problem
4. run `./swapDeps.sh` (or swap deps manually)
5. run `yarn test`
    - Observe functioning watch mode

Alternatively just install the mentioned deps and try to run webpack in watch mode.
Then switch them for the working ones and run again.

**Expected behavior**

Webpack will run in watch mode consistently with `webpack-cli@4.0.0` as 
it works with `webpack-cli@3.3.12`

### PR DESCRIPTION
**Pull request by evilebottnawi**
**What kind of change does this PR introduce?**

bugfix

**Did you add tests for your changes?**

Yes

**If relevant, did you update the documentation?**

No need

**Summary**

fixes #1923

**Does this PR introduce a breaking change?**

No

**Other information**

We need more tests on this, especial multi compiler mode

stdin is broken, I will fix it in other PR

### CODE REVIEW

**Comment by evilebottnawi** [comment]
I hate node and windows

**Comment by gianlucalarizza** [comment]
Good morning.. 
Have you merged by any chance? with the webpack-cli version ":" ^ 4.1.0 ", I always have the problem. Thanks so much for all your work.

**Comment by gianlucalarizza** [comment]
@evilebottnawi Have you merged? With the webpack-cli version ":" ^ 4.1.0 ", I always have the problem. Thanks so much for all your work.

**Comment by evilebottnawi** [comment]
@gianlucalarizza No problems with `4.1.0`

**Comment by gianlucalarizza** [comment]
@evilebottnawi
thanks for the reply but i still have the same problem.

The only place I have the --watch is in the package.json and not in the webpack configuration options
For example: "npm  --progress --watch --config webpack.development.js",

**Comment by evilebottnawi** [comment]
Because `npm` is not our binary

**Comment by gianlucalarizza** [comment]
@evilebottnawi 
sorry for the lack of knowledge and the different questions. What would your binary be? I can try to understand if I can change. thankssss

**Comment by evilebottnawi** [comment]
`webpack --progress --watch --config webpack.development.js`

**Comment by gianlucalarizza** [comment]
@evilebottnawi 
In console:

>npm run watch

webpack  --watch --config webpack.development.js

(node:16064) [DEP_WEBPACK_WATCH_WITHOUT_CALLBACK] DeprecationWarning: A 'callback' argument need to be provided to the 'webpack(options, callback)' function when the 'watch' option is set. There is no way to handle the 'watch' option without a callback.

**Comment by evilebottnawi** [comment]
@gianlucalarizza remove `watch: true` from your config, you don't need this because you already run `--watch`

**Comment by gianlucalarizza** [comment]
@evilebottnawi :) in my package json i have

"scripts": {
    "watch": "webpack --progress --config webpack.development.js",
    "build": "webpack  --progress --mode production --config webpack.production.js",

If in my command line I try to remove --watch, it's works fine  but i don't have [webpack-cli] watching files for updates...

Consider that in the webpack configuration file I have not put the watch option

**Comment by evilebottnawi** [comment]
You need to remove `watch: true` in the config file, please read docs

**Pull request merged**
