### PR TITLE
tests: add test for multiple config in dotfolder

### PR DESCRIPTION
**Pull request by anshumanv**
**What kind of change does this PR introduce?**

tests

**Did you add tests for your changes?**
Yes

**If relevant, did you update the documentation?**
NA

**Summary**
- Add tests when there are multiple configs present in dotfolder

**Does this PR introduce a breaking change?**
No

**Other information**

### CODE REVIEW

**Comment by anshumanv** [comment]
@evilebottnawi we presently only support reading `.dev.js` `.prod.js` files from `.webpack` folder, do we wish to support reading from root as well?

**Comment by anshumanv** [comment]
Presently root only supports webpack.config.*

**Comment by evilebottnawi** [comment]
Yes, need support too

**Comment by anshumanv** [comment]
Will fix 👍

**Comment by evilebottnawi** [comment]
@anshumanv Also webpack has `none` env, so I think we should support `webpack.config.none.js`, very rare case, but I think we should supports + I think we should support full naming like `webpack.config.development.js` and `webpack.config.production.js`

**Comment by anshumanv** [comment]
Sounds good, will fix 👍

**Pull request merged**
