### PR TITLE
chore(opencollective): move opencollective to utils

### PR DESCRIPTION
**Pull request by anshumanv**
move opencollective to utils

ISSUES CLOSED: #800

**What kind of change does this PR introduce?**
minor refactor

**Did you add tests for your changes?**
yes

**If relevant, did you update the documentation?**
NA

**Summary**
Simply fixed the file's path

**Does this PR introduce a breaking change?**
No

**Other information**
I need suggestions whether to move the constants used in opencollective function to be moved to `constants.js` since they're just used once so does it make sense to move them as well?

### CODE REVIEW

**Comment by anshumanv** [comment]
What do you think of the current approach? Can it be improved? How about making a closure and keeping a variable whether it is to be shown?

**Comment by fokusferit** [comment]
@anshumanv what problem was exactly solved? I do get that refactoring. Was there anything reported? Just curious.

**Comment by anshumanv** [comment]
Yeah @fokusferit there's an issue here where we had some discussion - https://github.com/webpack/webpack-cli/issues/800

**Comment by anshumanv** [comment]
Sure thing, can you suggest an approach to refactor or any other change?

**Comment by evenstensberg** [comment]
See issue #800 for explaination. Altough you are the best 💙

**Pull request closed without merging**
