### PR TITLE
chore: remove lint matrix

### PR DESCRIPTION
**Pull request by nschonni**
**What kind of change does this PR introduce?**

**Did you add tests for your changes?**

**If relevant, did you update the documentation?**

**Summary**

Was only setup for a single execution, so most of the values were unused

**Does this PR introduce a breaking change?**

**Other information**

### CODE REVIEW

**Review by alexander-akait — COMMENTED** [review]
Why? Solution before works the same, we prefer to use matrix

**Comment by nschonni** [comment]
> Why? Solution before works the same, we prefer to use matrix

Like the Commit lint job, there is only a single execution of the task, so a matrix doesn't make sense for this job. The Node version in the task name was also confusing your branch policy before (looks like you've unstuck the v12 version)

**Review by evenstensberg — COMMENTED** [review]
Why?

**Comment by nschonni** [comment]
> Why?

https://github.com/webpack/webpack-cli/pull/3047#issuecomment-986940958

**Comment by alexander-akait** [comment]
Sorry, we don't need it, current solution look good for me, anyway thanks

**Pull request closed without merging**
