### PR TITLE
chore: remove redundant packages

### PR DESCRIPTION
**Pull request by rishabh3112**
**What kind of change does this PR introduce?**
Remove packages

**Did you add tests for your changes?**
No
**If relevant, did you update the documentation?**
Yes
**Summary**
Deleted packages no longer needed from >= v4

**Does this PR introduce a breaking change?**
Yes

**Other information**

### CODE REVIEW

**Comment by rishabh3112** [comment]
cc @evenstensberg

**Comment by ematipico** [comment]
Would you mind to add a better description in the pr? I had to look to the commits to understand the packages you're deleting

**Comment by rishabh3112** [comment]
Okay, closing this PR :). Also, there was a `tmp` directory in the root. What's the use of that folder ?

**Comment by rishabh3112** [comment]
Does this PR makes sense now @evenstensberg?

**Pull request closed without merging**
