### PR TITLE
fix: compatibility with webpack@next

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**
tests

**Did you add tests for your changes?**
Yes
**If relevant, did you update the documentation?**
Yes
**Summary**
the latest release have breaking changes

**Does this PR introduce a breaking change?**
NO

**Other information**

### CODE REVIEW

**Review by evilebottnawi — APPROVED** [review]
/cc @snitin315 Can you remove `draft`?

**Comment by snitin315** [comment]
Need to add tests for new `--snapshot-*` flags. but can be added in a separate PR.

**Comment by evilebottnawi** [comment]
@snitin315 Yes, let's do it in separate PR, we need to rc release, maybe we can write test to ensure we do not lost new flags?

**Comment by snitin315** [comment]
I can see the new flags in help output. So we haven't lost them.

Screenshot at 2020-09-01 15-38-35

**Review by anshumanv — APPROVED** [review]

**Pull request merged**
