### PR TITLE
refactor: migrate advanced group

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**
refactor

**Did you add tests for your changes?**
yes refactored tests too
**If relevant, did you update the documentation?**
No
**Summary**

refactor advanced group.

**Does this PR introduce a breaking change?**
No

**Other information**
No

### CODE REVIEW

**Comment by anshumanv** [comment]
Please let me know before starting work, I'll have to stash my local work now 😞

**Comment by rishabh3112** [comment]
@snitin315 @anshumanv there should be either a communication on slack or on github before starting any task to avoid any such disputes in future.

**Review by rishabh3112 — APPROVED** [review]

**Comment by anshumanv** [comment]
> @snitin315 @anshumanv there should be either a communication on slack or on github before starting any task to avoid any such disputes in future.

It's there already 😞

**Review by anshumanv — APPROVED** [review]
LGTM, @snitin315 try not to repeat this.
/cc @evilebottnawi

**Comment by rishabh3112** [comment]
> It's there already

Yes there is, Nitin keep a better check on our chats on slack from the next time.
Anshuman  to avoid clashes on the tasks which need multiple PRs, create issues like this https://github.com/webpack/webpack-cli/issues/1509 so that everyone is up to date on issue on github as well.

**Comment by snitin315** [comment]
> Yes there is, Nitin keep a better check on our chats on slack from the next time

Sorry about that. I will take care next time.

**Pull request merged**
