### PR TITLE
misc: not scaffold 'dist' if the user chooses default

### PR DESCRIPTION
**Pull request by EvsChen**
As mentioned in #708 , we don't need to scaffold the "dist" property in output path if the entry is single and output path is not chosen by the user.

**What kind of change does this PR introduce?**
misc
**Did you add tests for your changes?**
N/A
**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**
No

**Other information**

### CODE REVIEW

**Comment by evenstensberg** [comment]
Yes it will, but the default output path is `dist`. What @TheLarkInn is requesting is that we do not set the option at all in the generated configuration file 👍

**Comment by EvsChen** [comment]
The `dist` will not appear in the output. If the user chooses default output and does not input anything, the `outputTypeAnswer.outputType.length` will be equal to 0 and the output will not be set. 

Did I miss some point here? I think the only place that sets the output option is in this `if` block.

**Comment by evenstensberg** [comment]
If you set multiple entries and press enter you can see the default output option being set regardless. Idea is to remove that setting entirely

**Comment by EvsChen** [comment]
As what mentioned in #708, I think @TheLarkInn only wants to remove it for the single entry case.

**Comment by evenstensberg** [comment]
Webpack will set that property regardless, and it should not be in the generated configuration file if it is set to `dist`

**Pull request merged**
