### PR TITLE
Refactor code

### PR DESCRIPTION
**Pull request by evilebottnawi**
**What kind of change does this PR introduce?**

refactoring

**If relevant, did you update the documentation?**

No need

**Summary**

refactor

**Does this PR introduce a breaking change?**

No

**Other information**

WIP

### CODE REVIEW

**Comment by anshumanv** [comment]
need fix CI

**Comment by evilebottnawi** [comment]
Yep, on it

**Comment by evilebottnawi** [comment]
Fixed:
- extra lines in output for help/version
- exit code with some errors
- remove unused code
- refactor some parts
- reduce initial run

**Review by anshumanv — COMMENTED** [review]
Lets fix CI

**Review by anshumanv — APPROVED** [review]

**Comment by evilebottnawi** [comment]
I will fix skipping test in future

**Comment by evilebottnawi** [comment]
I don't understand what the hell with color on CI

**Comment by snitin315** [comment]
Just pass --no-color in test to avoid it.

**Comment by evilebottnawi** [comment]
We should disable colors for tests by default, and enable them only when we need to test it

**Review by snitin315 — APPROVED** [review]

**Pull request merged**
