### PR TITLE
chore: prefer destructuring approach

### PR DESCRIPTION
**Pull request by jamesgeorge007**
**What kind of change does this PR introduce?**
refactoring

**Did you add tests for your changes?**
Nope

**If relevant, did you update the documentation?**
Nope

**Summary**
Use object destructuring assignment which results in much concise version.

**Does this PR introduce a breaking change?**
Nope

**Other information**
N/A

### CODE REVIEW

**Comment by ematipico** [comment]
Would you mind take all these tiny refactors and bring them all one single PR? It would save time

**Comment by jamesgeorge007** [comment]
@ematipico it just caught my eye while going through the codebase, and I can't find anything similar. Can we land this one?

**Comment by jamesgeorge007** [comment]
We've been following this approach for the entire codebase, and I think the respective stylistic update makes sense in that regard.

**Comment by ematipico** [comment]
@jamesgeorge007 not this time, please.

**Pull request closed without merging**
