### PR TITLE
chore: update generator deps

### PR DESCRIPTION
**Pull request by rishabh3112**
**What kind of change does this PR introduce?**
chore, avoid duplication of package utils **(Just for release)**

**Did you add tests for your changes?**
N/A
**If relevant, did you update the documentation?**

**Summary**
Before:
image

After:
image

**Does this PR introduce a breaking change?**
No

**Other information**
**Not an intended solution. Follow #1752 for it.**

### CODE REVIEW

**Review by evilebottnawi — COMMENTED** [review]
It is break yarn PnP

**Comment by rishabh3112** [comment]
Would adding `@webpack-cli/package-utils`package as a peer dependency solve this?

**Comment by evilebottnawi** [comment]
I think we can solve it using steps:
1. Union `package-utils` and `utils` into `utils`
2. Move out utils for generators into `generators` package
3. Additional step - move `utils` into `webpack-cli`, because we use almost of them in `webpack-cli`

**Comment by rishabh3112** [comment]
> Additional step - move utils into webpack-cli, because we use almost of them in webpack-cli
we don't, we just use `package-utils` in CLI.

**Comment by evilebottnawi** [comment]
I mean this packages unnecessary, because we always install then, no need to keep them in deps

**Comment by rishabh3112** [comment]
Yes, these packages are unnecessary. As this would take long time to refactor it, I thought to doing this so that we can release within this week. Rest, I also support removing these packages.

**Comment by rishabh3112** [comment]
Closing as full refactor is in progress at #1822

**Pull request closed without merging**
