### PR TITLE
fix: no serve when dev-server is false

### PR DESCRIPTION
**Pull request by rishabh3112**
**What kind of change does this PR introduce?**
Fix

**Did you add tests for your changes?**
Yup

**If relevant, did you update the documentation?**
Yes

**Summary**
No dev server when `devServer: false` is supplied.

**Does this PR introduce a breaking change?**
Nope

**Other information**
/cc @alexander-akait

### CODE REVIEW

**Comment by rishabh3112** [comment]
@alexander-akait devServer is `object` in schema, should change/publish that first to support `devServer: false`.

**Comment by alexander-akait** [comment]
We should return before using schema

**Comment by rishabh3112** [comment]
> We should return before using schema

We should not read configuration without validating against schema ideally.

**Review by evenstensberg — APPROVED** [review]
All tests green. LGTM 🧑🏽‍💻

**Comment by alexander-akait** [comment]
We need to revert this, because we should not exit, just run a regular compilation with a warning, I will fix it

**Comment by alexander-akait** [comment]
Also `webpack build` with `devServer: false` should work too without any problems

**Pull request merged**
