### PR TITLE
test: refactor core-flags tests

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**
Refactoring.

**Did you add tests for your changes?**
yes, refactor them.

**If relevant, did you update the documentation?**
No

**Summary**

WIP

Refactor core-flags tests.

**Does this PR introduce a breaking change?**
No

**Other information**
No

### CODE REVIEW

**Comment by alexander-akait** [comment]
Ideally we should not decrease coverage after refactor, i.e. all branches should be passed

**Review by alexander-akait — COMMENTED** [review]
Good work, but we still lose coverage, can you investigate, maybe some kind of small branch is not covered

**Comment by snitin315** [comment]
Hmm, looking into it 👍🏻

**Comment by alexander-akait** [comment]
Looks good, give me time to look at coverage regression

**Comment by alexander-akait** [comment]
Found, I will fix

**Comment by alexander-akait** [comment]
Thanks

**Pull request merged**
