### PR TITLE
build!: the minimum required Node.js version is `18.12.0`

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**
build

**Did you add tests for your changes?**
No

**If relevant, did you update the documentation?**
No

**Summary**

The minimum required Node.js version is `18.12.0`

**Does this PR introduce a breaking change?**
Yes

**Other information**
No

### CODE REVIEW

**Comment by alexander-akait** [comment]
@snitin315 Feel free to continue work in this branch on other `next` changes

**Comment by snitin315** [comment]
@alexander-akait Created separate `next` branch. Are you fine with the minimum version as `18.18.0`?

**Comment by alexander-akait** [comment]
Let's use :
```
"engines": {
    "node": ">= 18.12.0"
  },
```

**Comment by snitin315** [comment]
@alexander-akait Done!

**Pull request merged**
