### PR TITLE
refactor: run `info` under the hood for the `version` command

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**
refactor.

**Did you add tests for your changes?**
Removed tests and updated snapshots.

**If relevant, did you update the documentation?**
No.

**Summary**

Run info under the hood for the version command.

`webpack info` now shows the version of webpack-cli and sub-packages by default - https://github.com/webpack/webpack-cli/pull/3362

**Does this PR introduce a breaking change?**

No

**Other information**
No

### CODE REVIEW

**Review by alexander-akait — CHANGES_REQUESTED** [review]
Let's keep `version` and `--version`, but just run `info` under the hood, it is a good practice to support `version` in CLI applications, you can run any CLI tool and see `--version -v` flags

**Review by evenstensberg — CHANGES_REQUESTED** [review]
Version flags are common in CLIs, so let's keep those

**Comment by snitin315** [comment]
Yes let's keep `version` as separate like it is now but run `info` under the hood.

**Review by alexander-akait — APPROVED** [review]

**Comment by alexander-akait** [comment]
@snitin315 Can you provide output for `version` now (screenshot), thank you

**Comment by snitin315** [comment]
@alexander-akait yes, it's similar to info output.

Screenshot 2022-09-16 at 7 02 23 PM

**Comment by alexander-akait** [comment]
Thank you

**Pull request merged**
