### PR TITLE
chore(deps): update packages deps and lockdown 

### PR DESCRIPTION
**Pull request by anshumanv**
update deps

**What kind of change does this PR introduce?**
Updating app dependencies

**Did you add tests for your changes?**
Not yet, will do soon!

**If relevant, did you update the documentation?**
NA

**Summary**
* Updating core deps
* Updating package deps
* Locking down 

**Does this PR introduce a breaking change?**
Need to test after some iterations

**Other information**
@evenstensberg opening a draft, will be updating and then will open it.

### CODE REVIEW

**Comment by evenstensberg** [comment]
Hmu once tests are green and I'll do a review. There's some deps you can't lock

**Comment by anshumanv** [comment]
> Hmu once tests are green and I'll do a review. There's some deps you can't lock

Sure thanks, fails seems to be about linting errors now, will fix them and jump back on this. 👍

**Comment by anshumanv** [comment]
Will fix after figuring out #938

**Comment by anshumanv** [comment]
Closing, fixed

**Pull request closed without merging**
