### PR TITLE
feat: implement bundle alias

### PR DESCRIPTION
**Pull request by rishabh3112**
**What kind of change does this PR introduce?**
Feature

**Did you add tests for your changes?**
No, will do

**If relevant, did you update the documentation?**
No

**Summary**
Added a bundle command which is alias for `webpack-cli` only. Will be used for further refactoring later on.

**Does this PR introduce a breaking change?**
No

**Other information**
/cc @alexander-akait

### CODE REVIEW

**Review by snitin315 — COMMENTED** [review]
Is there any other way to bundle ??

**Review by alexander-akait — COMMENTED** [review]
We should use arg parsers here no need to hardcode and rerurn bootstrap

**Comment by rishabh3112** [comment]
> Is there any other way to bundle ??

I didn't get your question 😅  (webpack's main job is bundling)
Regarding this PR anyway, `webpack-cli --progress` and `webpack-cli bundle --progress` would result in same output.

**Comment by snitin315** [comment]
> > Is there any other way to bundle ??
> 
> I didn't get your question 😅 (webpack's main job is bundling)
> Regarding this PR anyway, `webpack-cli --progress` and `webpack-cli bundle --progress` would result in same output.

It will be equivalent to `webpack-cli webpack-cli --progress`.

**Comment by alexander-akait** [comment]
Yes, so we should use arg parser here

**Comment by snitin315** [comment]
I get it we want to do it like `webpack-cli--progress` and `bundle --progress`

**Comment by alexander-akait** [comment]
Thanks for help and sorry for delay, solved in master due refactoring

**Pull request closed without merging**
