### PR TITLE
WIP: refactor: standardize command files

### PR DESCRIPTION
**Pull request by PlayMa256**
Refactor command files and how they are invoked.

**What kind of change does this PR introduce?**
Refactor

**Summary**
I recently have seen polymer CLI and how they structured their cli and also saw @ev1stensberg tweet saying that this would be a good refactor to have, so i gave it a shot.

The problem is i just saw the pr list and found #371 which basically does a little bit of this. 

I would like to know about you guys, if this is desirable. From my POV, this looks way clear than what it was before.

It's just more of a "what you guys think? feedback please!!" then a proper PR.

I appreciate any feedback. If it is not desirable, i delete this without any problems.

Again: **WIP** and it still has things to `refactor/rename/move` to make everything more organized.

**Does this PR introduce a breaking change?**
No.

### CODE REVIEW

**Comment by ev1stensberg** [comment]
I don't think we need class instances to run explicit commands. With polymer it makes sense, cause the entire suite is based on yeoman, our isn't.

**Comment by PlayMa256** [comment]
Alright, thanks!
Deleting it!

**Comment by ev1stensberg** [comment]
Thanks for the PR though! Can I point you to another issue?

**Comment by PlayMa256** [comment]
Absolutly!

**Comment by ev1stensberg** [comment]
Could you have a go at this? https://github.com/webpack/webpack-cli/issues/152

**Comment by PlayMa256** [comment]
Sure! Never worked with that, but its worth learning :smile:

I'm going to have a look at that later, i will post there if i have any doubts! 

Btw, did you found out if there is a better option other then spawning another node process, to add that new feature? From further researches, that is basically the way to do. Mocha already does that too. I posted a link to their cli. Let me know what you think and i will proceed the development there!

**Comment by ev1stensberg** [comment]
No I haven't. Can you link to the file mocha does this in?

**Comment by PlayMa256** [comment]
Here you have it!
https://github.com/mochajs/mocha/blob/master/bin/mocha

**Comment by ev1stensberg** [comment]
You can try to do the same

**Pull request closed without merging**
