### PR TITLE
chore(fix): fix clean all script

### PR DESCRIPTION
**Pull request by sendilkumarn**
**What kind of change does this PR introduce?**

build related change 

**Did you add tests for your changes?**
NA
**If relevant, did you update the documentation?**
NA
**Summary**
Remove package-lock.json

**Does this PR introduce a breaking change?**

No
**Other information**
NIL

### CODE REVIEW

**Comment by ematipico** [comment]
Shouldn't we remove the clean:all command from the bootstrap?

**Comment by ematipico** [comment]
Why?

**Comment by sendilkumarn** [comment]
Bootstrap will help to link dependencies in the repo together and it is advisable to remove node modules and install dependencies when the link happens.

**Comment by dhruvdutt** [comment]
@sendilkumarn Can you please link to docs or blog for a detailed explanation? I'm also slightly sceptical about the removal of node_modules.

**Comment by sendilkumarn** [comment]
Okay here is the brief overview, I cannot find the exact ticket (or) issue where it was discussed. 

running `npm install` across packages / in the root cause some symlinks & installed dependencies across packages in `lerna`. This causes dependencies to break when you run `npm i` multiple times or even with concurrency in `npm i`

On the other hand, `npm i` will remove any `npm link` that is already in that package. As a matter of fact `lerna` depends mostly on the linked npm packages.

So it is advised to clean up `node_modules`, before running `bootstrap`. Take any package that is using lerna for example, it does clean the dependencies and recreate them. 

I am not sure, what is the loss here, of course when you are bootstrapping, you might need to install the packages (freshly).

**Pull request merged**
