### PR TITLE
fix: yeoman-generator fork issue

### LINKED ISSUE #291: webpack-cli init command error
**webpack-cli version**

Latest tree. (2.0.9) Using symlink.

**What is the current behavior?**

Using `webpack-cli init` with mostly default recommended options.

screenshot_20180227_032131

After all dependencies are installed, I get this error:

image

Generated package.json

image

**Steps to reproduce**
```bash
mkdir test-dir && cd test-dir;
mkdir src && touch src/index.js;
webpack-cli init
```

**What is the expected behavior?**

`webpack-cli init` should run and create a webpack project with a config file.

### PR DESCRIPTION
**Pull request by dhruvdutt**
**What kind of change does this PR introduce?**

Fixes the issue with yeoman-generator fork. Fixes #291 :bug: 
- Update `yeoman-generator` module path in package.json to match the syntax [recommended by npm](https://docs.npmjs.com/files/package.json#repository). 
- Change the module name and usage from `"webpack-fork-yeoman-generator"` to `"yeoman-generator"` across all files.

**Tests**

All tests pass. :100: Also, did a quick test with:
```bash
mkdir test-dir && cd test-dir;
mkdir src && touch src/index.js;
webpack-cli init
```

> (Update): Added a temp `eslint-disable-line` to pass CI. For more description check comments.

**Summary**

Also, now we don't need to [published](https://www.npmjs.com/package/webpack-fork-yeoman-generator) the fork separately.

Related commit (https://github.com/webpack/webpack-cli/commit/0b4269c7eb25c61908cf2aa56b23eb017036dd28)

**Does this PR introduce a breaking change?**
No

### CODE REVIEW

**Comment by dhruvdutt** [comment]
@ev1stensberg Can you please review this?

Also, the tests are failing because of some issue with how prettier formats and writes our code.

When `yarn format` runs, prettier tries to indent and adds an extra space (highlighted in screenshot) which causes `yarn lint` to fail throwing `no-mixed-spaces-and-tabs`

screenshot_20180227_155940

I think we did not catch this earlier because these files were not being changed and hence prettier or eslint might be skipping them while checks but this PR contains change in those files.

screenshot_20180227_155640

**Comment by dhruvdutt** [comment]
@ev1stensberg Can you please review this?

Also, the tests are failing because of some issue with how prettier formats and writes our code.

When `yarn format` runs, prettier tries to indent and adds an extra space (highlighted in screenshot) which causes `yarn lint` to fail throwing `no-mixed-spaces-and-tabs`

screenshot_20180227_155940

I think we did not catch this earlier because these files were not being changed and hence prettier or eslint might be skipping them while checks but this PR contains change in those files.

screenshot_20180227_155640

**Comment by justerest** [comment]
it fixs  #291

**Comment by dhruvdutt** [comment]
@ev1stensberg Updated. :100:

**Comment by ev1stensberg** [comment]
Okay nice, so you can reimpl the disables, weird they weren't throwing earlier

**Comment by montogeek** [comment]
@ev1stensberg Please apologies in advance, Why is yeoman necessary in this project? And also why a forked was needed?

**Comment by ev1stensberg** [comment]
It's to grab arguments from a generator ( the config we're scaffolding ). The fork implements a way to do that, yeoman doesn't support it

**Comment by montogeek** [comment]
Isn't it possible to implement it from scratch of using another library that supports it?
What it is exactly doing? Replacing values in templates and creating directory/files?

**Comment by ev1stensberg** [comment]
Possibly, needs investigation anyhow :(

**Comment by LukeChannings** [comment]
@ev1stensberg 

Is there a way to avoid the custom `yeoman-generator` dependency? I'm working in an environment that loads all dependencies through a [Nexus](https://www.sonatype.com/nexus-repository-oss) repo and blocks github.com. The latest `webpack-cli` is not installable for me because of this.

**Comment by ev1stensberg** [comment]
I'm having a lot to do until thursday +-, will try to get something up after that. We're gonna use yeoman, but not the fork. Right now, we avoid writing to a temp `yeoman-rc` file, and get the config from the generator instead. To fix this, we probably need to make a temp config and parse it ( sigh ).

**Pull request merged**
