### PR TITLE
chore(notifier): update notifier frequency

### PR DESCRIPTION
**Pull request by jamesgeorge007**
**What kind of change does this PR introduce?**

feature

**Did you add tests for your changes?**
Nope

**If relevant, did you update the documentation?**
N/A

**Summary**
Set the update interval to be 1 week.
As per this [comment](https://github.com/webpack/webpack-cli/pull/888#issuecomment-495177892)

**Does this PR introduce a breaking change?**

Nope

**Other information**
related #888

### CODE REVIEW

**Comment by jamesgeorge007** [comment]
cc @ematipico @evenstensberg

**Comment by jamesgeorge007** [comment]
cc @ematipico @evenstensberg

**Comment by ematipico** [comment]
The message shown by the library: does it appear also in the CI? (travis, azure)

**Comment by jamesgeorge007** [comment]
@ematipico It doesn't seem to be :thinking:

**Comment by jamesgeorge007** [comment]
cc @EugeneHlushko

**Comment by jamesgeorge007** [comment]
cc @evenstensberg

**Pull request merged**
