### PR TITLE
feat: union loader and plugin generators to single package

### PR DESCRIPTION
**Pull request by anshumanv**
**What kind of change does this PR introduce?**

feat

**Did you add tests for your changes?**
Not yet

**If relevant, did you update the documentation?**
Not yet

**Summary**
- Unions loader and plugin generator packages to generator package since it doesn't make sense to keep a single function package

**Does this PR introduce a breaking change?**
Yep, it will deprecate 2 packages

**Other information**
NA

### CODE REVIEW

**Review by evilebottnawi — COMMENTED** [review]
I like this idea, ideally we should have on `generators` package for any generations

**Comment by anshumanv** [comment]
> I like this idea, ideally we should have on generators package for any generations

Yep, `generate-loader` and plugin packages have a single function so haveing a separate package for it doesn't make sense, will fix tests today

**Comment by anshumanv** [comment]
facing some local build issues, revisiting in a while

**Comment by anshumanv** [comment]
complete today

**Comment by anshumanv** [comment]
strange errors 😞

**Comment by anshumanv** [comment]
After huge time I think this is ready now

**Review by alexander-akait — APPROVED** [review]
/cc @webpack/cli-team please review

**Comment by alexander-akait** [comment]
Need rebase

**Comment by anshumanv** [comment]
@alexander-akait evilebott done

**Review by alexander-akait — APPROVED** [review]

**Pull request merged**
