### PR TITLE
fix: enable passing silent flag to the compiler

### LINKED ISSUE #1324: webpack-cli: Passing silent flag doesn't work
**Describe the bug**

Still seeing webpack output when the silent flag is passed.

**What is the current behavior?**

Passing silent flag still logs webpack build data.

**To Reproduce**
`webpack-cli --silent`

**Expected behavior**

Should disable all logs. We should still log errors right?

**Screenshots**
when there are no errs - 
image

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

**Additional context**

### PR DESCRIPTION
**Pull request by anshumanv**
Fixes #1324 

**What kind of change does this PR introduce?**
fix

**Did you add tests for your changes?**
Yes

**If relevant, did you update the documentation?**
NA

**Summary**
- Allow passing the silent flag to the compiler

**Does this PR introduce a breaking change?**
No

**Other information**
NA

### CODE REVIEW

**Comment by anshumanv** [comment]
This is like a shorthand for `--stats none` like `--verbose` is for `--stats verbose`

**Comment by anshumanv** [comment]
> I would suggest not to block the flag for this purpose. Instead we can implement --silent flag for the purpose stated above (if we need it).

Did you test it? What are the changes needed here then?

**Comment by rishabh3112** [comment]
Currently it disables only webpack's output. IMO it should disable every possible output
( For example, warnings displayed by CLI, disable progress bar when `--progress` is supplied, etc.). That way consistency isn't compromised.

**Comment by snitin315** [comment]
We already support `webpack --stats=none` and `webpack --no-stats` both to disable output. Maybe we don't need `--silent`? was it present in the old CLI?

**Comment by anshumanv** [comment]
```js
silent: {
				type: "boolean",
				describe: "Prevent output from being displayed in stdout"
			},
```

I think this overlaps with stats-none, let's proceed to remove this, we can add it later if users ask. Will do in near future.

/cc @evilebottnawi

**Pull request closed without merging**
