### PR TITLE
chore(deps): remove unused ansi-escapes

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**
chore

**Did you add tests for your changes?**
No need
**If relevant, did you update the documentation?**
No need

**Summary**
remove unused dep `ansi-escapes`

**Does this PR introduce a breaking change?**

No
**Other information**
No

### CODE REVIEW

**Review by evilebottnawi — APPROVED** [review]

**Review by anshumanv — COMMENTED** [review]
This may be required in interactive support PR, will need to add again, so not sure if we should go ahead with this

**Comment by snitin315** [comment]
> This may be required in interactive support PR, will need to add again, so not sure if we should go ahead with this

But this isn't required right now 😄 .
Also, no idea when `interactive` will be implemented.

**Comment by anshumanv** [comment]
I think @rishabh3112 was wip on it?

**Comment by rishabh3112** [comment]
Yes, i am working on it.

**Comment by snitin315** [comment]
on #586 ?

**Comment by rishabh3112** [comment]
> on #586 ?

No not this one. You may go ahead with this change for now. I didn't had context to the issue when I earlier commented.

**Review by rishabh3112 — APPROVED** [review]

**Pull request merged**
