### PR TITLE
fix: improve error message

### LINKED ISSUE #2479: Help on certain commands is not available
**Describe the bug**

Documentation on certain commands (init, loader, migrate, plugin) are not available using the help command.

**What is the current behavior?**

Help on certain commands are not available

**To Reproduce**

* create a new project, add webpack, webpack-cli.
* check the help command (notice missing of some commands)
* check the detailed documentation using help commands on init, loader, migrate, plugin

**Expected behavior**

To show all available commands

**Screenshots**

Screenshot 2021-03-03 at 9 41 18 PM
Screenshot 2021-03-03 at 9 33 13 PM

**Please paste the results of `webpack-cli info` here, and mention other relevant information**
    webpack: ^5.24.2 => 5.24.2
    webpack-cli: ^4.5.0 => 4.5.0
    
**Additional context**

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**
bugfix

**Did you add tests for your changes?**
WIP on tests
**If relevant, did you update the documentation?**
No
**Summary**

Fixes #2479 

**Does this PR introduce a breaking change?**
No

**Other information**
No

### CODE REVIEW

**Review by alexander-akait — COMMENTED** [review]
Can you add test?

**Comment by snitin315** [comment]
Hard to test 😞, WIP.

**Comment by rishabh3112** [comment]
> Hard to test, WIP.

Should be a simple smoketest, I am testing now and will send  PR.

**Comment by rishabh3112** [comment]
> > Hard to test, WIP.
> 
> Should be a simple smoketest, I am testing now and will send commits to this PR.

Done.

**Comment by snitin315** [comment]
> > Should be a simple smoketest, I am testing now and will send commits to this PR.
> 
> Done.

Thanks 🚀

**Review by alexander-akait — APPROVED** [review]

**Comment by alexander-akait** [comment]
Thanks

**Pull request merged**
