### PR TITLE
require validateSchema and optionsValidationError from webpack

### PR DESCRIPTION
**Pull request by juliantellez**
**What kind of change does this PR introduce?**

### Bug Fix: 

The new version of webpack-cli adds webpack to the global process object. 
This causes applications such as webpack-dev-derver to break since it assumes that `process.webpackModule` is available in the current process.
This pr simply reverts this assumption.

**Did you add tests for your changes?**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

### CODE REVIEW

**Comment by ev1stensberg** [comment]
Is there any way to keep webpack on the process variable? Global vs local installations was failing cause local/global paths wasn't resolving correctly.

**Comment by ev1stensberg** [comment]
Thanks! Gotta do some more work on this before we can submit the fix!

**Comment by juliantellez** [comment]
Thanks @ev1stensberg ! glad to have put in my two pennies worth 👍

**Comment by ev1stensberg** [comment]
Helped us triage the bug in order to fix that quickly, thanks again @juliantellez !

**Pull request merged**
