### PR TITLE
chore: upgrade eslint plugins

### PR DESCRIPTION
**Pull request by anshumanv**
**What kind of change does this PR introduce?**
chore: upgrade eslint plugins

**Did you add tests for your changes?**
NA

**If relevant, did you update the documentation?**
NA

**Summary**
wip

**Does this PR introduce a breaking change?**

no

**Other information**

### CODE REVIEW

**Comment by anshumanv** [comment]
fixing types now

**Comment by anshumanv** [comment]
@alexander-akait fixed all types

**Review by alexander-akait — COMMENTED** [review]
Can we fix some warnings? Right now we can use `any` for them

**Comment by alexander-akait** [comment]
I can't understand what is wrong with windows webpack v5 and Node.js, other CIs are always success

**Comment by anshumanv** [comment]
> Can we fix some warnings? Right now we can use any for them

Yes let's do it

**Comment by alexander-akait** [comment]
> Error:   1:38  error  "mini-css-extract-plugin" is not found  node/no-missing-require

**Comment by anshumanv** [comment]
Fixed

**Comment by anshumanv** [comment]
@evilebottwani @alexander-akait windows CI still red 😞

**Comment by alexander-akait** [comment]
I am really don't know why it happens only on windows with webpack v5 and node v12, I can't reproduce it on windows :disappointed:

**Comment by alexander-akait** [comment]
Let's ignore, I will try to investigate deeply in future

**Pull request merged**
