### PR TITLE
docs: update serve options to v4

### PR DESCRIPTION
**Pull request by anshumanv**
**What kind of change does this PR introduce?**
docs

**Did you add tests for your changes?**
N/A

**If relevant, did you update the documentation?**
it is docs

**Summary**
Dev Server is in rc so updated serve options

**Does this PR introduce a breaking change?**
no

**Other information**

### CODE REVIEW

**Review by alexander-akait — COMMENTED** [review]
Better to keep v3 and add v4 options until we drop v3

**Comment by anshumanv** [comment]
let's keep both 👍

**Review by snitin315 — APPROVED** [review]

**Review by alexander-akait — COMMENTED** [review]
Let's rename `SERVE-OPTIONS.md` to `SERVER-OPTIONS-v3.md`

**Comment by anshumanv** [comment]
@alexander-akait already did 😄

**Comment by snitin315** [comment]
> Let's rename `SERVE-OPTIONS.md` to `SERVER-OPTIONS-v3.md`

Already done.

**Review by alexander-akait — APPROVED** [review]
My mistake :smile:

**Pull request merged**
