### PR TITLE
fix: conditionally install terser-webpack-plugin for webpack@next

### PR DESCRIPTION
**Pull request by anshumanv**
**What kind of change does this PR introduce?**

fix

**Did you add tests for your changes?**
No

**If relevant, did you update the documentation?**
NA

**Summary**
Conditionally install terser plugin for webpack@next

**Does this PR introduce a breaking change?**
No

**Other information**
https://github.com/webpack/webpack-cli/pull/1731#issuecomment-668652172

### CODE REVIEW

**Comment by anshumanv** [comment]
Skipped in stable 👍 
image

**Comment by evilebottnawi** [comment]
Yep, it should be skipped for stable

**Comment by anshumanv** [comment]
@snitin315 had to include your optimization tests else CI fail 😄

**Comment by evilebottnawi** [comment]
We need to remove it after the next beta release, please update other PRs, thanks

**Comment by anshumanv** [comment]
Will remove once released

**Pull request merged**
