### PR TITLE
Make use of utils for the ast transformations

### PR DESCRIPTION
**Pull request by pksjce**
Would be great if you were able to replicate in the other transformations as well. Will try to cover a couple here.

### CODE REVIEW

**Comment by pksjce** [comment]
@ev1stensberg - I hope this helps!

**Comment by ev1stensberg** [comment]
Would be great, but we're creating a property first on the module.exports, needs to be done before the `filter`. Which again means we're creating dupe nodes ( when I tried using `filter` and `forEach`). I used filter as a safe-mechanism for creating the value once.

**Comment by ev1stensberg** [comment]
I like the approach you've made, so it's worth implementing, nonetheless.

**Comment by ev1stensberg** [comment]
Run `webpack-cli --init webpack-addons-pwa` to see if your changes is viable. Needs a rebase first though

**Pull request closed without merging**
