### PR TITLE
tests: add tests for project root finder util

### LINKED ISSUE #967: [test]: Add tests for utils to find project root
**Do you want to request a *feature* or report a *bug*?**
I think we should have tests for util to find project root present in `path-utils` - https://github.com/webpack/webpack-cli/blob/master/packages/utils/path-utils.ts

**What is the current behavior?**
No tests for the function

**If the current behavior is a bug, please provide the steps to reproduce.**
NA

**What is the expected behavior?**
Have some tests to test behavior in various cases.

**If this is a feature request, what is motivation or use case for changing the behavior?**
NA

**Please paste the results of `webpack-cli info` here, and mention other relevant information such as programming language.**
```sh
  System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 75.0.3770.100
    Safari: 12.1.1
  npmPackages:
    webpack: 4.x.x => 4.33.0
    webpack-dev-server: 3.7.1 => 3.5.1
  npmGlobalPackages:
    webpack-cli: 3.3.4
    webpack: 4.30.0
```

### PR DESCRIPTION
**Pull request by anshumanv**
**What kind of change does this PR introduce?**
Test

**Did you add tests for your changes?**
Yes

**If relevant, did you update the documentation?**
NA

**Summary**
- Add tests for project root finder util
- Closes #967 

**Does this PR introduce a breaking change?**
No

**Other information**
Any suggestions are appreciated.

### CODE REVIEW

**Comment by anshumanv** [comment]
@rishabh3112 init tests seem to fail for some reason, when I was debugging it yesterday it seems that we're checking yarn.lock file too soon before it's created. You can follow - https://github.com/webpack/webpack-cli/pull/1478

**Comment by rishabh3112** [comment]
@anshumanv the reason you specified isn't possible as currently `runPromptWithAnswers` didn't exit the process until it exit on it's own. So, it should be there if this has to be there after it exits.

You may add debug logs to check which files are created while we are testing the existance of `yarn.lock` ( may be npm is being used during installation and `package-lock.json` created instead ).

**Comment by anshumanv** [comment]
> You may add debug logs to check which files are created while we are testing the existance of yarn.lock ( may be npm is being used during installation and package-lock.json created instead ).

Already did in plugin PR, yarn.lock wasn't found and no package-lock wasn't created either, I think there's some IO gap in the time it takes to write the file on disk and we may be checking before that.

**Comment by anshumanv** [comment]
This is happening in several PRs, you can check those too

**Comment by anshumanv** [comment]
For example check here - https://github.com/webpack/webpack-cli/pull/1480 @rishabh3112

**Comment by rishabh3112** [comment]
> Already did in plugin PR, yarn.lock wasn't found and no package-lock wasn't created either, I think there's some IO gap in the time it takes to write the file on disk and we may be checking before that.

That is only possible if yarn exits its install process without waiting for `yarn.lock` file to be created. Is that the case?

Anyway, to find actual reason,
Try debug logging before tests to find the exact reason.
- Use `fs.readdir` for looking at files being created in macos container. (As test fail at macos only).
- This could also be possible that some error was encountered and process ended in between, so try logging `stdout` too to check if thats the case.
- Look at the commits being added to next branch that change the behavior of `runInitWithAnswers` after I added these tests. As init tests were passing in CI at that point of time.

Hope this helps :)

**Comment by anshumanv** [comment]
> That is only possible if yarn exits its install process without waiting for yarn.lock file to be created. Is that the case?

> Anyway, to find actual reason, Try debug logging before tests to find the exact reason.  

Did all of that already at https://github.com/webpack/webpack-cli/pull/1478

> This could also be possible that some error was encountered and process ended in between, so try logging stdout too to check if thats the case.    

The process completes, no issue with process, once you remove yarn.lock from tests, it passes, 😕 

> Look at the commits being added to next branch that change the behavior of runInitWithAnswers after I added these tests. As init tests were passing in CI at that point of time.

No major changes

**Comment by evilebottnawi** [comment]
CI still broken :disappointed:

**Comment by anshumanv** [comment]
Checking @evilebottnawi 😄

**Pull request merged**
