### PR TITLE
chore(format): format all files via prettier

### PR DESCRIPTION
**Pull request by anshumanv**
Somehow all files were not formatted and thus on each commit all these files are changes so fixed that. Not sure how they crept in @evenstensberg 

**What kind of change does this PR introduce?**
Format code as per config

**Did you add tests for your changes?**
yes

**If relevant, did you update the documentation?**
NA

**Summary**
* Format all files using prettier
* All these changes are coming in while pre commit.
* Somehow these were not formatted from previous PR

**Does this PR introduce a breaking change?**
No

**Other information**

### CODE REVIEW

**Comment by anshumanv** [comment]
Maybe @ematipico has an idea?

**Comment by anshumanv** [comment]
Where is it conflicting 😕

**Comment by anshumanv** [comment]
@ematipico you think not having official support is going against us? 

image

**Comment by anshumanv** [comment]
Closing this sorry, will wait for further discussion

**Comment by evenstensberg** [comment]
Not really, feel free to rebase & reopen

**Comment by anshumanv** [comment]
> Not really, feel free to rebase & reopen

Sounds good, I think there is a conflict in eslint config and the prettier defaults, would it make sense to remove the eslint rules which are picked up by prettier? 🤔 Can't think of other workarounds right now.

**Comment by anshumanv** [comment]
Reopening to run some checks.

**Comment by ematipico** [comment]
If you want to format ALL the files, you have to run eslint fix with the correct folder/extension pattern.

You can't use the lint staged because it just applies the commands to the files that are modified in the commit.

**Comment by anshumanv** [comment]
> You can't use the lint staged because it just applies the commands to the files that are modified in the commit.

Yes correct, but `npm run format` formats all files and not just staged ✨

**Comment by ematipico** [comment]
The issue has been fixed

**Pull request closed without merging**
