### PR TITLE
chore(webpack-cli): improve import-local

### LINKED ISSUE #1318: import-local doesn't make sense
**Describe the bug**

import-local package does not prefer the local installation of webpack-cli, it only allows you to check whether the local launch or global

**What is the current behavior?**

Code exists and does nothing

**To Reproduce**

1. `webpack` or `node packages/webpack-cli/bin/cli.js`

**Expected behavior**

Code should be removed or improved, example of the improvement https://github.com/avajs/ava/blob/master/cli.js

**Screenshots**

No need

```
  System:
    OS: Linux 5.3 Ubuntu 19.10 (Eoan Ermine)
    CPU: (6) x64 AMD FX(tm)-6300 Six-Core Processor
    Memory: 1.05 GB / 11.73 GB
  Binaries:
    Node: 10.15.2 - /usr/bin/node
    Yarn: 1.13.0 - /usr/bin/yarn
    npm: 6.14.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 80.0.3987.132
    Firefox: 73.0.1
  npmPackages:
    webpack: ^4.42.0 => 4.42.0 
  npmGlobalPackages:
    webpack-cli: 3.3.6
```

**Additional context**

No

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**

removed stale import-local

**Did you add tests for your changes?**
NA
**If relevant, did you update the documentation?**
NA
**Summary**
Fixes #1318 

**Does this PR introduce a breaking change?**

NO

**Other information**

### CODE REVIEW

**Comment by snitin315** [comment]
> Update lock file too

lock file is not present,  all lock files are being ignored except the root lock file

**Comment by evilebottnawi** [comment]
And we still should update lock file, when something changes in dependencies/devDependencies in `package.json` you always need regenerate lock file

**Comment by snitin315** [comment]
> And we still should update lock file, when something changes in dependencies/devDependencies in `package.json` you always need regenerate lock file

I did generate again,  but no changes to stage and commit.

**Comment by snitin315** [comment]
unable to commit changes, getting the following error -

Screenshot from 2020-03-17 22-15-46

Tried disabling eslint for the line, doesn't work as well

**Comment by evilebottnawi** [comment]
> Do I have to make changes in eslint conf?

Yes, only for that file, use `overrides` https://eslint.org/docs/user-guide/configuring

**Comment by snitin315** [comment]
Still unable to commit, when I am writing overrides in `.eslintrc.js` it throws the error -
```
0:0 warning File ignored by default. Use a negated ignore pattern (like "--ignore-pattern '!<relative/path/to/filename>'") to override
```

Maybe that's why it was commented out.

**Comment by snitin315** [comment]
overrides were throwing warning as well, 
```
    overrides: [
        {
            files: ['./bin/cli.js'],
            parserOptions: {
                ecmaFeatures: {
                    globalReturn: true,
                },
            },
        },
    ],
```

Screenshot from 2020-03-18 09-05-22

So, I wrapped the logic inside `IIFE`.

**Comment by evilebottnawi** [comment]
> overrides were throwing warning as well,

Eslint have cli args to check what rules used for file, okay, I will fix it soon

> So, I wrapped the logic inside IIFE. please check if it's ok to do so.

No, it is wrong

**Comment by evilebottnawi** [comment]
Please remove IIFE and wait merge https://github.com/webpack/webpack-cli/pull/1348

**Comment by evilebottnawi** [comment]
Tested locally and all fine, we will need to add tests in the future (when we starts increase coverage)

**Pull request merged**
