### PR TITLE
fix typo

### LINKED ISSUE #2221: Typo in webpack-cli/packages/webpack-cli/bin/cli.js
`sucessfully` is written instead of `successfully`. 
<br/>
<br/>
ss

### PR DESCRIPTION
**Pull request by gauravdas014**
**What kind of change does this PR introduce?**
Typo fix

**Did you add tests for your changes?**
N/A
**If relevant, did you update the documentation?**
N/A
**Summary**
fixes #2221

**Does this PR introduce a breaking change?**
No

### CODE REVIEW

**Review by anshumanv — CHANGES_REQUESTED** [review]
Please refer commit guidelines

**Review by snitin315 — CHANGES_REQUESTED** [review]
Please sign CLA

**Comment by gauravdas014** [comment]
> Please sign CLA

I have signed it. Seems it will take some time to pass the check.

**Comment by snitin315** [comment]
> > Please sign CLA
> 
> I have signed it. Seems it will take some time to pass the check.

yeah, that thing is a bit buggy.

**Review by snitin315 — APPROVED** [review]

**Review by anshumanv — APPROVED** [review]

**Pull request closed without merging**
