### PR TITLE
cli: Fix file lookup on generators & missing module

### LINKED ISSUE #679: [BUG] : webpack-cli does not honor webpack-config file passed as param
**Describe the bug**

**What is the current behavior?**

I have used webpack, however this is the first time I'm using webpack-cli.

**To Reproduce**
1. create webpack-config file `webpack.foo.js`
2. use command `npx webpack-cli remove webpack.foo.js`
3. It throws the error --> 
**ERROR webpack.config.js** not found. Please specify a valid path to your webpack config like `$ webpack-cli remove webpack.dev.js`

**Expected behavior**
1. It should honor the file supplied by the CLI, instead always searching for `webpack.config.js`
2. Current error is completely misleading. It can be improvised. The error could be : `ERROR [passed filename] not found. Please specify a valid path to your webpack config like ...`

**Debugging Info**
1. [modify-config-helper](https://github.com/webpack/webpack-cli/blob/master/packages/utils/modify-config-helper.ts#L44) takes param configFile, which defaults to [webpack.config.js](https://github.com/webpack/webpack-cli/blob/master/packages/utils/modify-config-helper.ts#L27)
2. We are not passing `configFile` param to it while calling [remove](https://github.com/webpack/webpack-cli/blob/master/packages/remove/index.ts#L13)

### PR DESCRIPTION
**Pull request by evenstensberg**
**What kind of change does this PR introduce?**
Fixes errors thrown when trying to invoke `update`, `remove` and scaffold commands with a config name.

**Did you add tests for your changes?**
Yea
**If relevant, did you update the documentation?**
N/A
**Summary**
N/A

**Does this PR introduce a breaking change?**
No

**Other information**
Fixes #679

### CODE REVIEW

**Comment by evenstensberg** [comment]
API from devserver has changed, so https://github.com/webpack/webpack-dev-server/blob/master/lib/options.json needs to be used on the scaffold generators before this can be merged

**Comment by evenstensberg** [comment]
Would be nice if we can do this https://hackernoon.com/import-json-into-typescript-8d465beded79 @dhruvdutt

**Comment by evenstensberg** [comment]
Why does it fail then? 🤔

**Comment by dhruvdutt** [comment]
Not sure, it was working at the time I implemented it.

**Comment by dhruvdutt** [comment]
Let's merge this.

**Pull request merged**
