### PR TITLE
feat: add pnpm support for package installation

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**
feature

**Did you add tests for your changes?**
Yes
**If relevant, did you update the documentation?**
No
**Summary**

add `pnpm` support for package installation

**Does this PR introduce a breaking change?**
No

**Other information**
No

### CODE REVIEW

**Review by evilebottnawi — APPROVED** [review]
Good job!

**Review by rishabh3112 — CHANGES_REQUESTED** [review]
looks good to me, needs coverage bump.

**Comment by evilebottnawi** [comment]
@rishabh3112 Changing  `Coverage   69.01%   69.01%   -0.01%` is normal

**Review by rishabh3112 — APPROVED** [review]

**Comment by evilebottnawi** [comment]
@snitin315 Let's improve it in webpack too for webpack-cli https://github.com/webpack/webpack/blob/master/bin/webpack.js, big thanks for helping

**Comment by snitin315** [comment]
> @snitin315 Let's improve it in webpack too for webpack-cli https://github.com/webpack/webpack/blob/master/bin/webpack.js, big thanks for helping

Sure, I will send a PR.

**Comment by evilebottnawi** [comment]
@snitin315 big thanks

**Pull request merged**
