### PR TITLE
docs: Add roadmap and format readme

### PR DESCRIPTION
**Pull request by DanielaValero**
**What kind of change does this PR introduce?**
Only adds the roadmap to the readme, so we all have the clear goal of the project.

**Did you add tests for your changes?**
N/A

**Summary**
In order to have a clear Roadmap to all users and
contributors, adding now a section for it in the
Readme.

**Does this PR introduce a breaking change?**

No

### CODE REVIEW

**Comment by ev1stensberg** [comment]
Let's hold on to this until there's more to add.

**Comment by ev1stensberg** [comment]
@DanielaValero Add Travis build status and we should introduce coverage soon

**Comment by DanielaValero** [comment]
I would not like to introduce something to the readme when we don't have it yet. As soon as we have enabled all the coverage and build status, we can add it.

**Comment by ev1stensberg** [comment]
You can add travis, it's been used since **T minus 10**

**Comment by DanielaValero** [comment]
Hi @ev1stensberg let us wait for the call we will have this week to have this updated and merged. After our call, we might tweak the roadmap. Does it make sense for you?

**Comment by DanielaValero** [comment]
Hello @ev1stensberg 

Would you be more explicit with these changes ?

> Remove some boilerplate copied from webpack/webpack that is unceccecary from this
> Add contribution section
> Add testing section
> Add more description to the readme

**Comment by ev1stensberg** [comment]
Sure! 

### Add Contribution Section

Elaborate a bit on how to contribute to the project in relation to issues we submit and labels. Also add some tips to first contribution.

### Add Testing Section

Add Section describing our test procedure and how to write good and clean tests, this makes it easier to contribute with tests and also to write them for us.

### Add More Description to Readme

This should elaborate a bit more about the tool in general and some other required fields in a readme. Look at the webpack readme for inspiration.

**Comment by DanielaValero** [comment]
Hello @ev1stensberg 

Would you check again? I've added your feedback

**Comment by ev1stensberg** [comment]
Hey @DanielaValero Mind linking to the contribution doc somewhere in the readme? After that it should be mergable

**Comment by DanielaValero** [comment]
Hi @ev1stensberg, the cross linking to the CONTRIBUTING.md is not really necessary, when the file is there, people who wants to contribute knows that in there are the instructions about how to contribute. It's the same with the LICENSE or the README files, they are a well known standard, which we don't need to explain anymore.

**Comment by ev1stensberg** [comment]
Thanks for the correction! Merged 🎉

**Pull request merged**
