### PR TITLE
misc(grammar): revise spelling and incorrect syntax

### PR DESCRIPTION
**Pull request by jsoref**
**What kind of change does this PR introduce?**

Spelling fixes

**Did you add tests for your changes?**

No. It's possible to write a test using `fchurn`, but I'm not currently providing code for that in my PRs.

**Summary**

Misspellings are embarrassing.

**Does this PR introduce a breaking change?**

`runSingleTransform` is a breaking change.
I can provide a shim if required.

**Other information**

Generated by https://github.com/jsoref/spelling `f`; to maintain your repo, please consider `fchurn`

### CODE REVIEW

**Comment by ev1stensberg** [comment]
You need to change your commit style as well as you might have broken some logic in the binTestCases as you renamed some files

**Comment by jsoref** [comment]
@ev1stensberg: I can't understand the builder's output...

**Comment by ev1stensberg** [comment]
okay so you need to rebase your commits like: `chore(spelling): something`

**Comment by jsoref** [comment]
@ev1stensberg: thanks, that worked

**Pull request merged**
