### PR TITLE
fix: only set output path on passing flag

### PR DESCRIPTION
**Pull request by anshumanv**
**What kind of change does this PR introduce?**
- convert `output` to `output-path`
- only assign output path when supplied

**Did you add tests for your changes?**
Yes

**If relevant, did you update the documentation?**
Yes

**Summary**
Previously we were assigning output file and path which was not correct so fixed that and converted output flag to output-path

**Does this PR introduce a breaking change?**
Yes

**Other information**
Fixes https://github.com/webpack/webpack-cli/issues/1844

### CODE REVIEW

**Review by evilebottnawi — APPROVED** [review]
/cc @webpack/cli-team 

Good work!

**Review by snitin315 — APPROVED** [review]

**Comment by Rob--W** [comment]
This should have been called `feat: Rename --output flag to --output-path`.

It is a breaking change, and quite a late one to make after beta, before RC...

**Comment by Rob--W** [comment]
Actually, it seems that `--output` has been split into `--output-path` (=output directory) and `--output-filename` (=file name only). The ability to direct output to a specific absolute location has been lost.

**Comment by evilebottnawi** [comment]
@Rob--W you have configurations so you can setup this, it is breaking change and described

**Comment by Rob--W** [comment]
It seems that there is no way to pass an absolute file path via the command line any more, is there?
I fixed my use case by splitting the path and separately passing `--output-path` and `--output-filename`: https://github.com/mozilla/webextension-polyfill/pull/245/files

This limitation is strange though. Most tools that I can recall supporting a parameter to an output file accept an absolute path, whereas this tool now requires to separate flags. Is there any reason for this change?

**Comment by evilebottnawi** [comment]
@Rob--W because path and filename is different thing, you can use palceholders in filename, so we don't know in `--output path/to/[hash][ext]` `[hash][ext]` is filename or placeholders, so we separate this

**Comment by Rob--W** [comment]
`-o /path/to/plain/file/without/webpack/placeholders.js` is unambiguous. If the `[hash]` and `[ext]` are the primary reason for this breaking change, then I think that restoring support for `--output [absolute path here]` makes sense.

The meaning of the `-o` flag has also changed by this PR. It used to be a file path, now it's supposedly a directory path.

If you consciously accepted these breaking, backwards-incompatible changes, then feel free to ignore my comment.

**Pull request merged**
