### PR TITLE
docs: fix a typo at contrbuting readme file

### PR DESCRIPTION
**Pull request by sumukhah**
**What kind of change does this PR introduce?**
docs

**Did you add tests for your changes?**
No

**If relevant, did you update the documentation?**
Yes

**Summary**
Removed an extra line space in the commit message format guide.

**Does this PR introduce a breaking change?**
No

**Other information**
No

### CODE REVIEW

**Review by alexander-akait — DISMISSED** [review]

**Comment by alexander-akait** [comment]
Thanks

**Review by snitin315 — COMMENTED** [review]
@sumukhah can you fix lint issue?

**Comment by sumukhah** [comment]
@snitin315 Done 👍

**Review by alexander-akait — APPROVED** [review]

**Comment by alexander-akait** [comment]
Thanks

**Pull request merged**
