### PR TITLE
feat: configure codecov reporting

### PR DESCRIPTION
**Pull request by rishabh3112**
**What kind of change does this PR introduce?**
feature

**Did you add tests for your changes?**
N/A
**If relevant, did you update the documentation?**
No
**Summary**
Configure reporting of codecov

**Does this PR introduce a breaking change?**
No

**Other information**
related to #1899

### CODE REVIEW

**Comment by snitin315** [comment]
CI seems super slow 😞

**Comment by rishabh3112** [comment]
> CI seems super slow

Yup, but unrelated to this PR as individual jobs are taking same amount of time as they where before. Issue is that the less number of jobs are not running simultaneously per PR because of sudden increase of commits in repository as a whole.

**Comment by snitin315** [comment]
hmm, I think we should cancel the previous run manually if we push a new commit.

**Review by snitin315 — APPROVED** [review]

**Review by evilebottnawi — APPROVED** [review]
Great job!

**Review by anshumanv — APPROVED** [review]

**Comment by evilebottnawi** [comment]
@rishabh3112 Can we focus on `skip` test

@webpack/cli-team Also we should improve coverage - just more tests, ideally have 95-100% coverage

**Pull request merged**
