### PR TITLE
fix: multiple config compilation error

### LINKED ISSUE #887: [BUG]: Multiple config throws error calling tap on undefined in webpack-cli
# Bug report

**What is the current behavior?**
When running webpack with `--info-verbosity verbose` and multiple configs the following error is thrown.  The MultiCompiler does not define a beforeRun hook.

```node_modules/webpack-cli/bin/cli.js:281
    compiler.hooks.beforeRun.tap("WebpackInfo", compilation => {
					        ^

TypeError: Cannot read property 'tap' of undefined
    at processOptions (node_modules/webpack-cli/bin/cli.js:281:31)
    at yargs.parse (node_modules/webpack-cli/bin/cli.js:373:3)
    at Object.parse (node_modules/webpack-cli/node_modules/yargs/yargs.js:567:18)
    at node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (node_modules/webpack-cli/bin/cli.js:375:3)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (node_modules/webpack/bin/webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Create a multiple config webpack and run webpack with --info-verbosity verbose.

**What is the expected behavior?**
MultiCompiler should define a beforeRun hook.

**Other relevant information:**
webpack version:  4.32.1
Node.js version: v10.15.3
Operating System: MacOS 10.14.4
Additional tools:

### PR DESCRIPTION
**Pull request by aman29271**
**What kind of change does this PR introduce?**
This is a bufix request which closes #887 

**Did you add tests for your changes?**
Yes
**If relevant, did you update the documentation?**
no
**Summary**

**Does this PR introduce a breaking change?**
no

**Other information**

### CODE REVIEW

**Comment by evilebottnawi** [comment]
Please rebase your github fork

**Comment by aman29271** [comment]
Done. :pray:

**Comment by evilebottnawi** [comment]
Can you send a fix to next branch too?

**Comment by aman29271** [comment]
Sure. In different PR right?

**Comment by evilebottnawi** [comment]
@aman29271 Yes

**Pull request closed without merging**
