### PR TITLE
fix: show default value in help output if available

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**
fix

**Did you add tests for your changes?**
Manual testing
**If relevant, did you update the documentation?**

**Summary**
show default value in help output if provided in the `option` object.

**Does this PR introduce a breaking change?**
None

**Other information**
No

### CODE REVIEW

**Review by evenstensberg — COMMENTED** [review]
is there tests for this?

**Comment by snitin315** [comment]
None at present. I will see if I can add one.

**Comment by alexander-akait** [comment]
@snitin315 yep, let's add test, we can do it in `api` directory of tests

**Comment by alexander-akait** [comment]
@snitin315 friendly ping

**Review by alexander-akait — APPROVED** [review]

**Review by rishabh3112 — APPROVED** [review]

**Pull request merged**
