### PR TITLE
ci: add Node.js v20

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**

**Did you add tests for your changes?**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

### CODE REVIEW

**Comment by alexander-akait** [comment]
Hm, do we have deprecations output there?

**Comment by snitin315** [comment]
I'll check this locally.

**Comment by alexander-akait** [comment]
magic :mage: locally all works perfectly

**Comment by snitin315** [comment]
There is a bug report in v20 https://github.com/nodejs/node/issues/47614. It may be related.

**Comment by alexander-akait** [comment]
@snitin315 hm, I don't think, because it works locally using node v20 on ubuntu

**Comment by alexander-akait** [comment]
Problem with nyc here... trying to solve it

**Review by alexander-akait — APPROVED** [review]

**Pull request merged**
