### PR TITLE
feat(webpack-cli): add --stdin flag

### LINKED ISSUE #789: [Feature]: --stdin as option in config file
This is a duplicate of [issue #1712 on webpack-dev-server](https://github.com/webpack/webpack-dev-server/issues/1712), it was requested that I post it here :) 

  System:
    OS: macOS 10.14.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  Binaries:
    Node: 8.10.0 - ~/.nvm/versions/node/v8.10.0/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.10.0/bin/npm
  Browsers:
    Chrome: 72.0.3626.121
    Firefox: 65.0.1
    Safari: 12.0.3

- [ ] This is a **bug**
- [x] This is a **modification** request

### Code

Would be really useful to be able to do:
```
module.exports = {
  //...
  devServer: {
    stdin: true
  }
};
```

instead of having to run webpack-dev-server with --stdin on CLI only [as specified in the docs](https://webpack.js.org/configuration/dev-server/#devserverstdin---cli-only)

### For Features; What is the motivation and/or use-case for the feature?

Some popular dev tools (like vue-cli) have opinionated wrappers around webpack-dev-server that make it only possible to configure webpack via their own config files (where they pass along options to webpack-dev-server's `devServer` configuration object).

Unfortunately, this obscures really useful flags like stdin

Thank you for the amazing software!

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**
feature

**Did you add tests for your changes?**
no
**If relevant, did you update the documentation?**
yes
**Summary**
Fixes #789 

**Does this PR introduce a breaking change?**

**Other information**

### CODE REVIEW

**Comment by snitin315** [comment]
I'm not sure how to write tests for this one. any suggestions?

**Comment by anshumanv** [comment]
@evilebottnawi do you have any good approach to test it?

**Comment by evilebottnawi** [comment]
Let's focus on CLI flags from core, and return to this late, no high priority

**Comment by anshumanv** [comment]
Makes sense to revisit later 👍

**Comment by angelikatyborska** [comment]
Hi! Is there a chance this PR will be revisited soon? The lack of this flag is blocking my project from migrating from 3.3 to 4.0.

**Comment by alexander-akait** [comment]
Close in favor https://github.com/webpack/webpack-cli/pull/2217, we should respect `--watch-options-stdin`, I will improve this

**Pull request closed without merging**
