### PR TITLE
Coverage

### PR DESCRIPTION
**Pull request by evilebottnawi**
**What kind of change does this PR introduce?**

Enable coverage

**Did you add tests for your changes?**

No

**If relevant, did you update the documentation?**

No need

**Summary**

Enable coverage

**Does this PR introduce a breaking change?**

No

**Other information**

We need nyc because https://github.com/facebook/jest/issues/3190

### CODE REVIEW

**Comment by anshumanv** [comment]
Conflicts

**Comment by evilebottnawi** [comment]
@anshumanv Still WIP

**Comment by evilebottnawi** [comment]
@evenstensberg Late, but you can pick up it and finish

**Comment by evilebottnawi** [comment]
Done

**Pull request closed without merging**
