### PR TITLE
reduce coupling between webpack and webpack-cli

### PR DESCRIPTION
**Pull request by sokra**
**What kind of change does this PR introduce?**
refactoring

**Did you add tests for your changes?**
existing tests

**If relevant, did you update the documentation?**
N/A

**Summary**
* reduce coupling between webpack and webpack-cli
* `require("webpack/lib/DefinePlugin")` -> `require("webpack").DefinePlugin`
* move two files from webpack to webpack-cli. They are only used by webpack-cli.

**Does this PR introduce a breaking change?**

yes, since `webpack.Stats` is not exposed by webpack versions <= 4.0.0-alpha.2, this change will only work with higher versions. It was exposed by https://github.com/webpack/webpack/commit/289ba67ed68483a3e41204091148eb55ceb49e01

**Other information**
The goal is to reduce the coupling between webpack and webpack-cli.
webpack-cli should only use the public webpack API.

### CODE REVIEW

**Comment by sokra** [comment]
This can only be merged when the next webpack alpha/beta is released.

**Comment by sokra** [comment]
lastest alpha has been published, but PR is now conflicting...

**Comment by ev1stensberg** [comment]
I'll check it out later and fix the conflict

**Comment by ev1stensberg** [comment]
@sokra Rebased and reinstalled webpack ( `webpack@alpha.4.0.0-alpha.2`, but test suits are failing. Is it related to @TheLarkInn 's missing tests on 0CJS? If so, then #238 should be reviewed and merged first, then we'll do a rebase.

Also, when rebasing, the entire `bin/webpack.js` got a whole lot different than from `master` and your branch. May be better to open a new PR if it's comparing old hashes instead of the latest ones

**Comment by ev1stensberg** [comment]
Following up on this, this week

**Comment by ev1stensberg** [comment]
I tried to rebase the `execHelpers` change, but realized that it has been implemented in #251 . Closing in favor

**Pull request closed without merging**
