### PR TITLE
tests(output): add test case for defaults flag

### PR DESCRIPTION
**Pull request by anshumanv**
**What kind of change does this PR introduce?**
Added a test case for --defaults flag

**Did you add tests for your changes?**
Yes

**If relevant, did you update the documentation?**
NA

**Summary**
* Added a case when --defaults flag is used to indicate compiler to use webpack defaults.

**Does this PR introduce a breaking change?**
No

**Other information**

### CODE REVIEW

**Comment by anshumanv** [comment]
I think defaults tests can be moved a folder up since they're not really output but rather a way to indicate compiler about the config, what say @ematipico?

**Comment by ematipico** [comment]
Yes it makes totally sense! Feel free to move them around

**Comment by anshumanv** [comment]
Thanks for the heads up! Will do. ✨

**Comment by anshumanv** [comment]
Will do it in a separate PR, have more tests and cleanup in mind.

**Pull request merged**
